/// Evaluates `source` in the (per-thread) global QuickJS context. Top-level
/// function declarations become callable afterwards via `thaw_js_call`.
/// Returns `1` on success, `0` on failure (syntax error, thrown exception).
#[no_mangle]
pub extern "C" fn thaw_js_load(source: *const c_char) -> u8 {
    let source = to_str(source);
    with_context(|ctx| match load_impl(ctx, &source) {
        Ok(()) => 1,
        Err(reason) => {
            eprintln!("thaw-quickjs: failed to load script: {reason}");
            0
        }
    })
}

/// Real error message for a failed `eval`, extracted the same way
/// `call_impl` already does for a thrown exception -- without this,
/// `rquickjs::Error::Exception`'s own `Display` is just a generic
/// placeholder ("Exception generated by QuickJS"), which made a real
/// npm package's load-time failure (e.g. a top-level `require(...)` call
/// this crate's stub rejects, see thaw-bridge's `wrap_as_commonjs_module`)
/// undiagnosable.
fn load_impl(ctx: Ctx<'_>, source: &str) -> Result<(), String> {
    ctx.eval::<(), _>(source).map_err(|e| match e {
        rquickjs::Error::Exception => describe_exception(&ctx),
        e => e.to_string(),
    })?;
    if let Ok(ready) = ctx
        .globals()
        .get::<_, rquickjs::Promise>("__thaw_module_ready")
    {
        finish_with_platform_events(&ctx, &ready).map_err(|error| match error {
            rquickjs::Error::Exception => describe_exception(&ctx),
            error => format!("module initialization failed: {error}"),
        })?;
        while ctx.execute_pending_job() {}
        let _ = ctx
            .globals()
            .set("__thaw_module_ready", Value::new_undefined(ctx.clone()));
    }
    Ok(())
}

/// Evaluates a script in the shared embedded context and returns its result as
/// JSON. JavaScript values for which `JSON.stringify` returns `undefined`
/// produce `None`; exceptions retain their JavaScript message.
pub fn eval_json(source: &str) -> Result<Option<String>, String> {
    with_context(|ctx| {
        let value = ctx
            .eval::<Value<'_>, _>(source)
            .map_err(|error| match error {
                rquickjs::Error::Exception => describe_exception(&ctx),
                error => error.to_string(),
            })?;
        ctx.json_stringify(value)
            .map(|value| value.map(|value| value.to_string().unwrap_or_default()))
            .map_err(|error| match error {
                rquickjs::Error::Exception => describe_exception(&ctx),
                error => error.to_string(),
            })
    })
}

/// Calls a top-level function (previously loaded via `thaw_js_load`) named
/// `func_name`, with `args_json` a JSON-encoded array of arguments.
/// Returns the JSON-encoded result (or an error object -- see the module
/// doc comment).
#[no_mangle]
pub extern "C" fn thaw_js_call(
    func_name: *const c_char,
    args_json: *const c_char,
) -> *const c_char {
    let func_name = to_str(func_name);
    let args_json = to_str(args_json);

    let text = with_context(|ctx| match call_impl(ctx, &func_name, &args_json) {
        Ok(text) => text,
        Err(reason) => format!("{{\"__thaw_error__\":{}}}", json_escape_string(&reason)),
    });

    CString::new(text).unwrap_or_default().into_raw() as *const c_char
}

#[no_mangle]
/// Calls a QuickJS function retained by the N-API argument bridge.
///
/// # Safety
///
/// `context` must contain a reference identifier previously issued by the
/// bridge and `args_json` must point to a live NUL-terminated string.
pub unsafe extern "C" fn thaw_js_call_reference(
    context: *mut std::ffi::c_void,
    args_json: *const c_char,
) -> *const c_char {
    let name = format!("__thaw_napi_reference_{}", context as usize);
    let args_json = to_str(args_json);
    let text = ACTIVE_NAPI_CONTEXT.with(|active| {
        let active = active.get();
        if active.is_null() {
            with_context(|ctx| match call_impl(ctx, &name, &args_json) {
                Ok(text) => text,
                Err(reason) => {
                    format!("{{\"__thaw_error__\":{}}}", json_escape_string(&reason))
                }
            })
        } else {
            match call_impl(
                (*(active as *const Ctx<'static>)).clone(),
                &name,
                &args_json,
            ) {
                Ok(text) => text,
                Err(reason) => {
                    format!("{{\"__thaw_error__\":{}}}", json_escape_string(&reason))
                }
            }
        }
    });
    CString::new(text).unwrap_or_default().into_raw()
}

/// Result-ABI companion to [`thaw_js_call`]. Unlike the legacy JSON error
/// object API, failures occupy the error channel so generated Thaw code can
/// route JavaScript throws and Promise rejections through `try`/`catch`.
#[no_mangle]
pub extern "C" fn thaw_js_call_result(
    func_name: *const c_char,
    args_json: *const c_char,
) -> ThawResult {
    let func_name = to_str(func_name);
    let args_json = to_str(args_json);
    match with_active_or_context(|ctx| call_impl(ctx, &func_name, &args_json)) {
        Ok(text) => ThawResult {
            value: CString::new(text).unwrap_or_default().into_raw(),
            error: std::ptr::null(),
        },
        Err(reason) => ThawResult {
            value: std::ptr::null(),
            error: CString::new(reason).unwrap_or_default().into_raw(),
        },
    }
}

fn call_impl(ctx: Ctx<'_>, func_name: &str, args_json: &str) -> Result<String, String> {
    let target: Function = ctx
        .globals()
        .get(func_name)
        .map_err(|_| format!("no such function `{func_name}` (was it loaded via loadScript?)"))?;
    invoke_impl(ctx, target, func_name, args_json)
}

fn invoke_impl<'js>(
    ctx: Ctx<'js>,
    target: Function<'js>,
    label: &str,
    args_json: &str,
) -> Result<String, String> {
    let to_string_err = |e: rquickjs::Error| e.to_string();

    let json: Object = ctx.globals().get("JSON").map_err(to_string_err)?;
    let parse: Function = json.get("parse").map_err(to_string_err)?;
    // Reconstructs a real `Date` from Thaw's native `{"timestamp": N}`
    // wire shape (see `platform_globals/dates.js`) at every nesting depth
    // -- `JSON.parse`'s reviver runs bottom-up over the whole parsed
    // value, so a `Date`-typed field nested inside an array/object
    // argument is revived just like a top-level one.
    let date_reviver: Function = ctx
        .globals()
        .get("__thaw_json_date_reviver")
        .map_err(to_string_err)?;

    let args_array: Array = parse
        .call((args_json, date_reviver))
        .map_err(|e| format!("args_json is not a valid JSON array: {e}"))?;

    let mut call_args = Args::new_unsized(ctx.clone());
    for i in 0..args_array.len() {
        let arg: Value = args_array.get(i).map_err(to_string_err)?;
        call_args.push_arg(arg).map_err(to_string_err)?;
    }

    let result: Value = target.call_arg(call_args).map_err(|e| match e {
        rquickjs::Error::Exception => format!("`{label}` threw: {}", describe_exception(&ctx)),
        e => format!("`{label}` threw: {e}"),
    })?;

    resolve_value_impl(ctx, result, label)
}

/// Always passes `result` through the realm's Promise resolution
/// procedure, returning the *resolved* value (not JSON-encoded --
/// callers that need JSON should go through `resolve_value_impl`
/// instead, which wraps this). `Value::as_promise` only recognizes
/// native Promise objects; `Promise.resolve` also assimilates arbitrary
/// foreign thenables, handles throwing `then` accessors/calls, and obeys
/// the first-settlement-wins rule required by JavaScript.
///
/// Needed anywhere a result gets **retained as a live handle** rather
/// than JSON-encoded (`callDynamicMethodHandle`'s own native side,
/// `thaw_js_call_method_handle_result`) -- without this, an async
/// method's real result (a still-pending Promise, e.g. real hono's own
/// `app.request(...)`/`.fetch(...)`) would get retained *as the Promise
/// itself*, not the value it resolves to, and reading a property off it
/// afterward (`res.status`) silently reads `undefined` off the wrong
/// object instead of erroring -- confirmed via a direct repro. Thaw's own
/// `await` keyword doesn't help here either: it's a no-op pass-through
/// for anything but `sleep(...)` (`compile_await`'s own doc comment --
/// "User-defined async functions still use the V1 synchronous ABI"),
/// since it doesn't know a `JsValue` might represent a pending QuickJS-
/// side Promise at all.
fn resolve_promise_value<'js>(
    ctx: &Ctx<'js>,
    result: Value<'js>,
    label: &str,
) -> Result<Value<'js>, String> {
    let to_string_err = |e: rquickjs::Error| e.to_string();
    let assimilate: Function = ctx
        .eval("(value) => Promise.resolve(value)")
        .map_err(to_string_err)?;
    let promise: rquickjs::Promise = assimilate.call((result,)).map_err(|e| match e {
        rquickjs::Error::Exception => {
            format!(
                "`{label}` could not resolve its result: {}",
                describe_exception(ctx)
            )
        }
        e => format!("`{label}` could not resolve its result: {e}"),
    })?;
    finish_with_platform_events(ctx, &promise).map_err(|e| match e {
        rquickjs::Error::Exception => {
            format!("`{label}`'s promise rejected: {}", describe_exception(ctx))
        }
        e => format!("`{label}`'s promise rejected or stalled: {e}"),
    })
}

fn resolve_value_impl<'js>(
    ctx: Ctx<'js>,
    result: Value<'js>,
    label: &str,
) -> Result<String, String> {
    let result = resolve_promise_value(&ctx, result, label)?;

    // `ctx.json_stringify` (rather than calling the JS `JSON.stringify`
    // function directly and coercing its return value straight to a Rust
    // `String`) surfaces `JSON.stringify`'s "not representable" case as
    // `Ok(None)` instead of a real JS `undefined` value that a direct
    // `String` conversion would just fail on. That case is not rare here:
    // it's exactly what a genuinely `void`-returning (or otherwise
    // undefined-returning) Fallback function's real result looks like --
    // `null` is the universal placeholder every typed decoder on the
    // other side already tolerates (a `Void`-declared return, notably,
    // never even inspects the JSON it's handed).
    match ctx
        .json_stringify(result)
        .map_err(|e| format!("failed to JSON-encode the result: {e}"))?
    {
        Some(text) => text
            .to_string()
            .map_err(|e| format!("failed to JSON-encode the result: {e}")),
        None => Ok("null".to_string()),
    }
}

fn finish_with_platform_events<'js>(
    ctx: &Ctx<'js>,
    promise: &rquickjs::Promise<'js>,
) -> rquickjs::Result<Value<'js>> {
    loop {
        if let Ok(poll_platform_events) = ctx
            .globals()
            .get::<_, Function>("__thaw_poll_platform_events")
        {
            poll_platform_events.call::<_, ()>(())?;
        }
        poll_napi_bridge(ctx);
        if let Some(result) = promise.result() {
            return result;
        }
        if ctx.execute_pending_job() {
            continue;
        }

        let next_delay: Function = ctx.globals().get("__thaw_next_timer_delay")?;
        let delay: i64 = next_delay.call(())?;
        if delay < 0 {
            let active = ctx
                .globals()
                .get::<_, Function>("__thaw_worker_active")
                .ok()
                .and_then(|probe| probe.call::<_, bool>(()).ok())
                .unwrap_or(false)
                || ctx
                    .globals()
                    .get::<_, Function>("__thaw_child_process_active")
                    .ok()
                    .and_then(|probe| probe.call::<_, bool>(()).ok())
                    .unwrap_or(false);
            if active {
                std::thread::sleep(Duration::from_millis(1));
                continue;
            }
            return Err(rquickjs::Error::WouldBlock);
        }
        if delay > 0 {
            std::thread::sleep(Duration::from_millis(delay as u64));
        }
        let run_due: Function = ctx.globals().get("__thaw_run_due_timers")?;
        run_due.call::<_, usize>(())?;
    }
}

#[no_mangle]
pub extern "C" fn thaw_js_run_event_loop() {
    with_context(|ctx| loop {
        if let Ok(poll) = ctx
            .globals()
            .get::<_, Function>("__thaw_poll_platform_events")
        {
            let _ = poll.call::<_, ()>(());
        }
        poll_napi_bridge(&ctx);
        while ctx.execute_pending_job() {}
        let Ok(next_delay) = ctx.globals().get::<_, Function>("__thaw_next_timer_delay") else {
            return;
        };
        let Ok(delay) = next_delay.call::<_, i64>(()) else {
            return;
        };
        if delay < 0 {
            return;
        }
        if delay > 0 {
            std::thread::sleep(Duration::from_millis(delay as u64));
        }
        let Ok(run_due) = ctx.globals().get::<_, Function>("__thaw_run_due_timers") else {
            return;
        };
        let _ = run_due.call::<_, usize>(());
    });
}

/// Retains a global JavaScript value in the realm and returns a stable opaque
/// handle. Zero denotes failure or a missing value.
#[no_mangle]
pub extern "C" fn thaw_js_get_global(name: *const c_char) -> u64 {
    let name = to_str(name);
    with_active_or_context(|ctx| {
        let Ok(value) = ctx.globals().get::<_, Value>(name.as_str()) else {
            return 0;
        };
        retain_value(&ctx, value).unwrap_or(0)
    })
}

#[no_mangle]
pub extern "C" fn thaw_js_handle_to_string(handle: u64) -> *const c_char {
    let text = with_active_or_context(|ctx| -> Result<String, String> {
        let value = value_for_handle(&ctx, handle)?;
        let string: Function = ctx
            .globals()
            .get("String")
            .map_err(|error| error.to_string())?;
        string.call((value,)).map_err(|error| match error {
            rquickjs::Error::Exception => describe_exception(&ctx),
            error => error.to_string(),
        })
    })
    .unwrap_or_else(|_| "[invalid JsValue]".to_string());
    CString::new(text).unwrap_or_default().into_raw()
}

fn handle_array<'js>(ctx: &Ctx<'js>) -> Result<Array<'js>, String> {
    ctx.globals()
        .get("__thaw_value_handles")
        .map_err(|_| "JavaScript value handle registry is empty".to_string())
}

fn value_for_handle<'js>(ctx: &Ctx<'js>, handle: u64) -> Result<Value<'js>, String> {
    if handle == 0 {
        return Err("invalid JavaScript value handle 0".to_string());
    }
    let live: Array = ctx
        .globals()
        .get("__thaw_value_handle_live")
        .map_err(|_| "JavaScript value handle liveness registry is empty".to_string())?;
    if !live.get::<bool>((handle - 1) as usize).unwrap_or(false) {
        return Err(format!("released JavaScript value handle {handle}"));
    }
    let value: Value = handle_array(ctx)?
        .get((handle - 1) as usize)
        .map_err(|_| format!("invalid JavaScript value handle {handle}"))?;
    Ok(value)
}

fn object_for_handle<'js>(ctx: &Ctx<'js>, handle: u64) -> Result<Object<'js>, String> {
    let value = value_for_handle(ctx, handle)?;
    value
        .as_object()
        .cloned()
        .or_else(|| {
            value
                .as_function()
                .map(|function| AsRef::<Object>::as_ref(function).clone())
        })
        .or_else(|| {
            value
                .as_proxy()
                .map(|proxy| AsRef::<Object>::as_ref(proxy).clone())
        })
        .ok_or_else(|| {
            format!(
                "JavaScript value handle {handle} has non-object type {:?}",
                value.type_of()
            )
        })
}

/// Retains `value` in the realm-global handle registry and returns a
/// stable opaque handle, lazily creating the registry itself (`__thaw_
/// value_handles`/`__thaw_value_handle_live`) on first use -- unlike
/// `handle_array` (a *lookup*, used once something is already known to be
/// registered), this is the sole *write* path into the registry, so it
/// must not assume some earlier call already bootstrapped it. Real
/// example: a program whose first-ever touch of a JsValue handle is
/// registering a native closure as a callback
/// (`thaw_js_register_native_callback`) passed straight into an ordinary
/// top-level Fallback function call, with no prior dynamic-value-
/// returning call (e.g. no `makeHolder(): JsValue`-style call) to have
/// bootstrapped the registry first -- previously failed with "JavaScript
/// value handle registry is empty" even though this was really the very
/// first legitimate retain.
fn retain_value<'js>(ctx: &Ctx<'js>, value: Value<'js>) -> Result<u64, String> {
    let globals = ctx.globals();
    let handles: Array = match globals.get("__thaw_value_handles") {
        Ok(handles) => handles,
        Err(_) => {
            let handles = Array::new(ctx.clone()).map_err(|error| error.to_string())?;
            globals
                .set("__thaw_value_handles", handles.clone())
                .map_err(|error| error.to_string())?;
            let live = Array::new(ctx.clone()).map_err(|error| error.to_string())?;
            globals
                .set("__thaw_value_handle_live", live)
                .map_err(|error| error.to_string())?;
            handles
        }
    };
    let index = handles.len();
    handles
        .set(index, value)
        .map_err(|error| error.to_string())?;
    let live: Array = globals
        .get("__thaw_value_handle_live")
        .map_err(|_| "JavaScript value handle liveness registry is empty".to_string())?;
    live.set(index, true).map_err(|error| error.to_string())?;
    Ok(index as u64 + 1)
}

fn invoke_raw<'js>(
    ctx: Ctx<'js>,
    target: Function<'js>,
    args_json: &str,
) -> Result<Value<'js>, String> {
    let json: Object = ctx
        .globals()
        .get("JSON")
        .map_err(|error| error.to_string())?;
    let parse: Function = json.get("parse").map_err(|error| error.to_string())?;
    // The reviver (see its own doc comment in `dates.js`) also splices a
    // `JsValue` back in wherever `compile_dynamic_value_placeholder`
    // (thaw-llvm's `json_bridge.rs`) had to leave a
    // `{"__thaw_js_handle_id__": N}` placeholder in the JSON -- real
    // example: zod's `z.optional(z.string())`, where `z.string()`'s
    // schema object is a live value, not JSON.
    let reviver: Function = ctx
        .globals()
        .get("__thaw_json_date_reviver")
        .map_err(|error| error.to_string())?;
    let args_array: Array = parse
        .call((args_json, reviver))
        .map_err(|error| format!("args_json is not a valid JSON array: {error}"))?;
    let mut call_args = Args::new_unsized(ctx.clone());
    for index in 0..args_array.len() {
        let arg: Value = args_array.get(index).map_err(|error| error.to_string())?;
        call_args.push_arg(arg).map_err(|error| error.to_string())?;
    }
    target.call_arg(call_args).map_err(|error| match error {
        rquickjs::Error::Exception => describe_exception(&ctx),
        error => error.to_string(),
    })
}

unsafe fn native_handle_slice<'a>(array: *const u8) -> Result<&'a [u64], String> {
    if array.is_null() {
        return Err("null JsValue array".into());
    }
    let length = unsafe { *(array.cast::<u64>()) } as usize;
    Ok(unsafe { std::slice::from_raw_parts(array.add(8).cast::<u64>(), length) })
}

unsafe fn invoke_mixed<'js>(
    ctx: Ctx<'js>,
    target: Function<'js>,
    args_json: &str,
    handles: *const u8,
) -> Result<Value<'js>, String> {
    let json: Object = ctx
        .globals()
        .get("JSON")
        .map_err(|error| error.to_string())?;
    let parse: Function = json.get("parse").map_err(|error| error.to_string())?;
    let arguments: Array = parse
        .call((args_json,))
        .map_err(|error| error.to_string())?;
    let mut call_args = Args::new_unsized(ctx.clone());
    for index in 0..arguments.len() {
        call_args
            .push_arg(
                arguments
                    .get::<Value>(index)
                    .map_err(|error| error.to_string())?,
            )
            .map_err(|error| error.to_string())?;
    }
    for handle in unsafe { native_handle_slice(handles)? } {
        call_args
            .push_arg(value_for_handle(&ctx, *handle)?)
            .map_err(|error| error.to_string())?;
    }
    target.call_arg(call_args).map_err(|error| match error {
        rquickjs::Error::Exception => describe_exception(&ctx),
        error => error.to_string(),
    })
}

#[no_mangle]
/// Calls a retained function with JSON arguments followed by retained values.
///
/// # Safety
///
/// `handles` must point to a live Thaw array buffer containing an initial
/// `u64` length followed by that many aligned `u64` handle identifiers.
pub unsafe extern "C" fn thaw_js_call_handle_mixed_result(
    handle: u64,
    args_json: *const c_char,
    handles: *const u8,
) -> ThawResult {
    let args_json = to_str(args_json);
    let result = with_active_or_context(|ctx| {
        let target = Function::from_value(value_for_handle(&ctx, handle)?)
            .map_err(|_| format!("JavaScript value handle {handle} is not callable"))?;
        let value = unsafe { invoke_mixed(ctx.clone(), target, &args_json, handles)? };
        resolve_value_impl(ctx, value, &format!("JavaScript value #{handle}"))
    });
    match result {
        Ok(value) => ThawResult {
            value: CString::new(value).unwrap_or_default().into_raw(),
            error: std::ptr::null(),
        },
        Err(error) => ThawResult {
            value: std::ptr::null(),
            error: CString::new(error).unwrap_or_default().into_raw(),
        },
    }
}

#[no_mangle]
pub extern "C" fn thaw_js_construct_handle_result(
    handle: u64,
    args_json: *const c_char,
) -> ThawHandleResult {
    let args_json = to_str(args_json);
    match with_active_or_context(|ctx| {
        let constructor = value_for_handle(&ctx, handle)?
            .into_constructor()
            .ok_or_else(|| format!("JavaScript value handle {handle} is not a constructor"))?;
        let json: Object = ctx
            .globals()
            .get("JSON")
            .map_err(|error| error.to_string())?;
        let parse: Function = json.get("parse").map_err(|error| error.to_string())?;
        // See the matching comment in `invoke_raw`: revives a `JsValue`
        // wherever `compile_dynamic_value_placeholder` had to leave a
        // `{"__thaw_js_handle_id__": N}` placeholder for a class
        // constructor argument, not just a `Date`.
        let reviver: Function = ctx
            .globals()
            .get("__thaw_json_date_reviver")
            .map_err(|error| error.to_string())?;
        let arguments: Array = parse
            .call((args_json, reviver))
            .map_err(|error| error.to_string())?;
        let mut args = Args::new_unsized(ctx.clone());
        for index in 0..arguments.len() {
            args.push_arg(
                arguments
                    .get::<Value>(index)
                    .map_err(|error| error.to_string())?,
            )
            .map_err(|error| error.to_string())?;
        }
        let value: Value = constructor
            .construct_args(args)
            .map_err(|error| match error {
                rquickjs::Error::Exception => describe_exception(&ctx),
                error => error.to_string(),
            })?;
        retain_value(&ctx, value)
    }) {
        Ok(value) => ThawHandleResult {
            value,
            error: std::ptr::null(),
        },
        Err(error) => ThawHandleResult {
            value: 0,
            error: CString::new(error).unwrap_or_default().into_raw(),
        },
    }
}

/// The generic ABI every adapter thaw-llvm's `compile_napi_value_callback`
/// builds shares, regardless of the real (native) closure's own signature
/// -- the adapter itself already handles all the type-specific arg/return
/// marshaling internally, exposing only this one uniform shape outward.
/// `context` is the closure's own captured-environment pointer (opaque
/// here, passed straight back to the adapter unexamined); the returned
/// pointer is a NUL-terminated JSON string owned by the adapter's own
/// caller-frees-nothing convention (mirrors `thaw_js_call`'s own return),
/// so `to_str` below copies it out immediately and nothing is freed here.
type NativeCallbackAdapter = unsafe extern "C" fn(*const c_void, *const c_char) -> *const c_char;

/// Wraps a real compiled (native) closure -- already bridged into a
/// generic `(context, args_json) -> result_json` adapter by thaw-llvm's
/// `compile_napi_value_callback` -- as a live, retained QuickJS-NG
/// function value the Fallback dynamic-call path can hand off like any
/// other `JsValue`. Real example: zod's `z.number().refine((n: number) =>
/// n > 0, {...})`, whose predicate has nowhere else to go.
///
/// `adapter`/`closure` are captured by the returned JS function's own
/// closure as plain `usize` (not `Send`-problematic raw pointers) --
/// transmuted back to the real function-pointer type only at call time.
/// Safe because every adapter `compile_napi_value_callback` ever produces
/// shares this exact ABI unconditionally; there is no way to construct a
/// `NativeCallbackAdapter`-typed value here except from that one
/// generator.
///
/// Argument/return marshaling for the *inner* call (JS call args ->
/// `args_json`, `result_json` -> the JS return value) reuses the exact
/// same `JSON.stringify`/`JSON.parse`-with-reviver convention every other
/// dynamic-call boundary here already uses, so a `Date`/`JsValue`/
/// `undefined` argument or return value round-trips the same way it does
/// crossing any other dynamic-call boundary.
/// Retains a JS value and returns its permanent handle id, exposed to JS
/// as `__thaw_retain_dynamic_value` for `thaw_js_register_native_
/// callback`'s own wrapper to call. A plain named function, not a
/// closure -- see the call site's own comment for why.
fn retain_dynamic_value_for_js<'js>(ctx: Ctx<'js>, value: Value<'js>) -> u64 {
    retain_value(&ctx, value).unwrap_or(0)
}

#[no_mangle]
pub extern "C" fn thaw_js_register_native_callback(
    adapter: *const c_void,
    closure: *const c_void,
    jsvalue_param_mask: u64,
    finish: *const c_void,
) -> ThawHandleResult {
    let adapter = adapter as usize;
    let closure = closure as usize;
    let finish = finish as usize;
    let result: Result<u64, String> = with_context(|ctx| {
        // The Rust-backed half stays a plain `String -> String` closure --
        // no `Value<'js>` anywhere in its own signature -- deliberately:
        // an `IntoJsFunc` closure returning a value borrowed from `Ctx<'js>`
        // needs every `'_` in its own signature unified with the *call-
        // time* `Ctx<'js>` (not the outer one this function registers it
        // with), which an ordinary closure literal doesn't infer on its
        // own here. A thin JS-side wrapper (below) does the real
        // JSON-encode-args / JSON.parse-with-reviver-result work instead,
        // exactly the same convention `install_napi_bridge`'s own
        // string-only closures already use for the identical reason.
        static NEXT_NATIVE_CALLBACK_ID: std::sync::atomic::AtomicU64 =
            std::sync::atomic::AtomicU64::new(0);
        let id = NEXT_NATIVE_CALLBACK_ID.fetch_add(1, std::sync::atomic::Ordering::Relaxed);
        let raw = Function::new(ctx.clone(), move |ctx: Ctx<'_>, args_json: String| -> String {
            let args_json = CString::new(args_json).unwrap_or_default();
            // Enters the same "currently active `Ctx`" guard `install_
            // napi_bridge`'s own `call`/`handle` closures already use --
            // needed because the native closure this adapter is about to
            // invoke may itself call back into another dynamic operation
            // (a further `callDynamicMethod`/etc., real example: zod's
            // `.superRefine((val, ctx) => { ctx.addIssue(...); })`), which
            // would otherwise try to `with_context` a *second* time while
            // the outer call (the one that invoked *this* callback in the
            // first place) is still on the stack, panicking ("RefCell
            // already borrowed") since `with_context`'s own thread-local
            // slot has no reentrant-borrow support. See `thaw_js_call_
            // method_result`'s own matching `ACTIVE_NAPI_CONTEXT` check,
            // the consuming half of this -- despite the "napi" name, this
            // guard is a generic "currently active Ctx" mechanism, not
            // N-API-specific.
            let _active = ActiveNapiContext::enter(&ctx);
            // SAFETY: `adapter` was produced by `compile_napi_value_
            // callback` and always has exactly this ABI; `closure` is its
            // matching, still-live captured-environment pointer (the
            // compiled program keeps the whole closure alive for as long
            // as this registered callback might be called).
            let adapter_fn: NativeCallbackAdapter = unsafe { std::mem::transmute(adapter) };
            let result = unsafe { adapter_fn(closure as *const c_void, args_json.as_ptr()) };
            if finish == 0 {
                to_str(result)
            } else {
                format!("promise:{:x}", result as usize)
            }
        })
        .map_err(|error| error.to_string())?;
        let raw_name = format!("__thaw_native_callback_raw_{id}");
        ctx.globals()
            .set(raw_name.as_str(), raw)
            .map_err(|error| error.to_string())?;
        let poll_name = format!("__thaw_native_callback_poll_{id}");
        if finish != 0 {
            let poll = Function::new(ctx.clone(), move |ticket: String| -> String {
                let Some(address) = ticket.strip_prefix("promise:") else {
                    return "error:invalid native Promise ticket".to_string();
                };
                let Ok(address) = usize::from_str_radix(address, 16) else {
                    return "error:invalid native Promise address".to_string();
                };
                let promise = address as *const c_void;
                let finish_fn: NativeCallbackAdapter = unsafe { std::mem::transmute(finish) };
                let result = unsafe { finish_fn(promise, std::ptr::null()) };
                if result.is_null() {
                    return String::new();
                }
                to_str(result)
            })
            .map_err(|error| error.to_string())?;
            ctx.globals()
                .set(poll_name.as_str(), poll)
                .map_err(|error| error.to_string())?;
        }
        // Exposes `retain_value` to JS via a plain named function (not a
        // closure literal): `ctx`/`value` need the *same* `'js`
        // (`retain_value` requires it), and a closure's own two
        // independently-elided `'_` params don't unify to one on their
        // own here -- the same lifetime wall the module doc comment
        // above hit for a *returned* `Value<'js>`, this time for two
        // *different* params that must agree. A named function's normal
        // `for<'js>` generic already satisfies `Function::new`'s own
        // bound for any 'js, no closure-lifetime inference involved at
        // all. Reinstalled on every call rather than checked for
        // idempotently first: cheap, and simpler than threading a "is it
        // already there" check through this same function.
        let retain = Function::new(ctx.clone(), retain_dynamic_value_for_js)
            .map_err(|error| error.to_string())?;
        ctx.globals()
            .set("__thaw_retain_dynamic_value", retain)
            .map_err(|error| error.to_string())?;
        // Marks exactly the argument positions `compile_register_native_
        // callback` (thaw-llvm) declared `JsValue`-typed -- real example:
        // zod's `.superRefine((val, ctx: JsValue) => { ctx.addIssue(...);
        // })`, whose `ctx` is a live object with methods, not JSON-
        // representable data. Retained as a handle and encoded as the
        // same `{"__thaw_js_handle_id__": N}` marker `compile_dynamic_
        // value_placeholder` builds for the opposite direction, which
        // `compile_json_value_to_native`'s own new `HirType::JsValue`
        // case decodes back out on the native side (this marshaling
        // direction has no JS-side reviver to lean on -- the adapter
        // parses `args_json` natively, never through QuickJS's own
        // `JSON.parse`). `1 << i` is a plain 32-bit JS bitwise op --
        // plenty for any real callback's own arity.
        let wrapper_source = format!(
            "(function() {{ \
             var raw = globalThis['{raw_name}']; \
             delete globalThis['{raw_name}']; \
             var mask = {jsvalue_param_mask}; \
             return function() {{ \
             var args = Array.prototype.slice.call(arguments); \
             for (var i = 0; i < args.length; i++) {{ \
             if ((mask & (1 << i)) !== 0) {{ \
             args[i] = {{ __thaw_js_handle_id__: globalThis.__thaw_retain_dynamic_value(args[i]) }}; \
             }} \
             }} \
             var result = raw(JSON.stringify(args)); \
             if (result.slice(0, 8) !== 'promise:') return JSON.parse(result, globalThis.__thaw_json_date_reviver); \
             return new Promise(function(resolve, reject) {{ \
             function check() {{ \
             var settled = globalThis['{poll_name}'](result); \
             if (!settled) return setTimeout(check, 0); \
             if (settled.slice(0, 6) === 'error:') return reject(new Error(settled.slice(6))); \
             try {{ resolve(JSON.parse(settled, globalThis.__thaw_json_date_reviver)); }} catch (error) {{ reject(error); }} \
             }} \
             check(); \
             }}); \
             }}; \
             }})()"
        );
        let wrapper: Value = ctx
            .eval(wrapper_source.as_str())
            .map_err(|error| error.to_string())?;
        retain_value(&ctx, wrapper)
    });
    match result {
        Ok(value) => ThawHandleResult {
            value,
            error: std::ptr::null(),
        },
        Err(error) => ThawHandleResult {
            value: 0,
            error: CString::new(error).unwrap_or_default().into_raw(),
        },
    }
}

#[no_mangle]
pub extern "C" fn thaw_js_call_handle_handle_result(
    handle: u64,
    args_json: *const c_char,
) -> ThawHandleResult {
    let args_json = to_str(args_json);
    let result: Result<u64, String> = with_active_or_context(|ctx| {
        let target = Function::from_value(value_for_handle(&ctx, handle)?)
            .map_err(|_| format!("JavaScript value handle {handle} is not callable"))?;
        let result = invoke_raw(ctx.clone(), target, &args_json)?;
        let result =
            resolve_promise_value(&ctx, result, &format!("JavaScript value #{handle}"))?;
        retain_value(&ctx, result)
    });
    match result {
        Ok(value) => ThawHandleResult {
            value,
            error: std::ptr::null(),
        },
        Err(error) => ThawHandleResult {
            value: 0,
            error: CString::new(error).unwrap_or_default().into_raw(),
        },
    }
}

#[no_mangle]
pub extern "C" fn thaw_js_call_handle_value_result(handle: u64, argument: u64) -> ThawResult {
    let result = with_active_or_context(|ctx| {
        let target = Function::from_value(value_for_handle(&ctx, handle)?)
            .map_err(|_| format!("JavaScript value handle {handle} is not callable"))?;
        let argument = value_for_handle(&ctx, argument)?;
        let value: Value = target.call((argument,)).map_err(|error| match error {
            rquickjs::Error::Exception => describe_exception(&ctx),
            error => error.to_string(),
        })?;
        resolve_value_impl(ctx, value, &format!("JavaScript value #{handle}"))
    });
    match result {
        Ok(text) => ThawResult {
            value: CString::new(text).unwrap_or_default().into_raw(),
            error: std::ptr::null(),
        },
        Err(error) => ThawResult {
            value: std::ptr::null(),
            error: CString::new(error).unwrap_or_default().into_raw(),
        },
    }
}

#[no_mangle]
pub extern "C" fn thaw_js_release_handle(handle: u64) -> u8 {
    with_active_or_context(|ctx| {
        if handle == 0 {
            return 0;
        }
        let Ok(handles) = handle_array(&ctx) else {
            return 0;
        };
        let index = (handle - 1) as usize;
        let Ok(live) = ctx.globals().get::<_, Array>("__thaw_value_handle_live") else {
            return 0;
        };
        if !live.get::<bool>(index).unwrap_or(false) {
            return 0;
        }
        if live.set(index, false).is_err() {
            return 0;
        }
        u8::from(handles.set(index, Value::new_undefined(ctx)).is_ok())
    })
}

#[no_mangle]
pub extern "C" fn thaw_js_release_all_handles() -> u64 {
    with_context(|ctx| {
        let count = handle_array(&ctx).map(|handles| handles.len()).unwrap_or(0);
        let Ok(handles) = Array::new(ctx.clone()) else {
            return 0;
        };
        let Ok(live) = Array::new(ctx.clone()) else {
            return 0;
        };
        if ctx.globals().set("__thaw_value_handles", handles).is_err()
            || ctx.globals().set("__thaw_value_handle_live", live).is_err()
        {
            return 0;
        }
        count as u64
    })
}

#[no_mangle]
pub extern "C" fn thaw_js_get_property_result(
    handle: u64,
    name: *const c_char,
) -> ThawHandleResult {
    let name = to_str(name);
    let result: Result<u64, String> = with_active_or_context(|ctx| {
        let object = object_for_handle(&ctx, handle)?;
        let value = object.get(name.as_str()).map_err(|error| match error {
            rquickjs::Error::Exception => describe_exception(&ctx),
            error => error.to_string(),
        })?;
        retain_value(&ctx, value)
    });
    match result {
        Ok(value) => ThawHandleResult {
            value,
            error: std::ptr::null(),
        },
        Err(error) => ThawHandleResult {
            value: 0,
            error: CString::new(error).unwrap_or_default().into_raw(),
        },
    }
}

#[no_mangle]
pub extern "C" fn thaw_js_set_property_result(
    handle: u64,
    name: *const c_char,
    value_handle: u64,
) -> ThawHandleResult {
    let name = to_str(name);
    let result: Result<u64, String> = with_active_or_context(|ctx| {
        let object = object_for_handle(&ctx, handle)?;
        let value = value_for_handle(&ctx, value_handle)?;
        object
            .set(name.as_str(), value)
            .map_err(|error| match error {
                rquickjs::Error::Exception => describe_exception(&ctx),
                error => error.to_string(),
            })?;
        Ok(1)
    });
    match result {
        Ok(value) => ThawHandleResult {
            value,
            error: std::ptr::null(),
        },
        Err(error) => ThawHandleResult {
            value: 0,
            error: CString::new(error).unwrap_or_default().into_raw(),
        },
    }
}

fn invoke_method<'js>(
    ctx: &Ctx<'js>,
    handle: u64,
    name: &str,
    args_json: &str,
) -> Result<Value<'js>, String> {
    let object = object_for_handle(ctx, handle)?;
    let method: Function = object.get(name).map_err(|error| match error {
        rquickjs::Error::Exception => describe_exception(ctx),
        error => error.to_string(),
    })?;
    let json: Object = ctx
        .globals()
        .get("JSON")
        .map_err(|error| error.to_string())?;
    let parse: Function = json.get("parse").map_err(|error| error.to_string())?;
    // See the matching comment in `invoke_raw`: revives a `JsValue`
    // wherever `compile_dynamic_value_placeholder` had to leave a
    // `{"__thaw_js_handle_id__": N}` placeholder for a method argument
    // (or a `Date`), not just a plain top-level dynamic call's own
    // arguments.
    let reviver: Function = ctx
        .globals()
        .get("__thaw_json_date_reviver")
        .map_err(|error| error.to_string())?;
    let arguments: Array = parse
        .call((args_json, reviver))
        .map_err(|error| error.to_string())?;
    let mut call_args = Args::new_unsized(ctx.clone());
    call_args.this(object).map_err(|error| error.to_string())?;
    for index in 0..arguments.len() {
        let argument: Value = arguments.get(index).map_err(|error| error.to_string())?;
        call_args
            .push_arg(argument)
            .map_err(|error| error.to_string())?;
    }
    method.call_arg(call_args).map_err(|error| match error {
        rquickjs::Error::Exception => describe_exception(ctx),
        error => error.to_string(),
    })
}

#[no_mangle]
pub extern "C" fn thaw_js_call_method_result(
    handle: u64,
    name: *const c_char,
    args_json: *const c_char,
) -> ThawResult {
    let name = to_str(name);
    let args_json = to_str(args_json);
    let result = with_active_or_context(|ctx| {
        let value = invoke_method(&ctx, handle, &name, &args_json)?;
        resolve_value_impl(ctx, value, &format!("JavaScript method `{name}`"))
    });
    match result {
        Ok(value) => ThawResult {
            value: CString::new(value).unwrap_or_default().into_raw(),
            error: std::ptr::null(),
        },
        Err(error) => ThawResult {
            value: std::ptr::null(),
            error: CString::new(error).unwrap_or_default().into_raw(),
        },
    }
}

/// Like [`thaw_js_call_method_result`], but for a method whose own result
/// is itself a `JsValue` -- a live JS value with no JSON representation --
/// rather than plain data: retains the result as a handle instead of
/// JSON-encoding it. Real example: a schema instance's own chained
/// method returning another schema instance, as opposed to
/// `.safeParse(...)`'s plain data result (which stays on the
/// `thaw_js_call_method_result` path).
/// `chain_intermediate` is true when this call's own result is itself
/// the receiver of another chained `.method()` call (e.g. `.from(...)`
/// in `db.select().from(x).where(y)`) -- in that case a pending
/// thenable (a lazy query-builder object, not a genuine async result)
/// must NOT be resolved yet, since `Promise.resolve()` on any thenable
/// eagerly invokes its `.then`, which would execute the chain
/// prematurely. Only the terminal link in a chain (`chain_intermediate
/// == false`) resolves its result, matching real JS semantics where
/// only an explicit `await`/consumption of the final value would ever
/// settle a pending promise or thenable.
#[no_mangle]
pub extern "C" fn thaw_js_call_method_handle_result(
    handle: u64,
    name: *const c_char,
    args_json: *const c_char,
    chain_intermediate: bool,
) -> ThawHandleResult {
    let name = to_str(name);
    let args_json = to_str(args_json);
    let result: Result<u64, String> = with_active_or_context(|ctx| {
        let value = invoke_method(&ctx, handle, &name, &args_json)?;
        let value = if chain_intermediate {
            value
        } else {
            resolve_promise_value(&ctx, value, &format!("JavaScript method `{name}`"))?
        };
        retain_value(&ctx, value)
    });
    match result {
        Ok(value) => ThawHandleResult {
            value,
            error: std::ptr::null(),
        },
        Err(error) => ThawHandleResult {
            value: 0,
            error: CString::new(error).unwrap_or_default().into_raw(),
        },
    }
}

#[no_mangle]
pub extern "C" fn thaw_js_resolve_handle_result(handle: u64) -> ThawResult {
    let result = with_active_or_context(|ctx| {
        let value = value_for_handle(&ctx, handle)?;
        resolve_value_impl(ctx, value, &format!("JavaScript value #{handle}"))
    });
    match result {
        Ok(value) => ThawResult {
            value: CString::new(value).unwrap_or_default().into_raw(),
            error: std::ptr::null(),
        },
        Err(error) => ThawResult {
            value: std::ptr::null(),
            error: CString::new(error).unwrap_or_default().into_raw(),
        },
    }
}

/// Calls a callable value retained by [`thaw_js_get_global`]. Arguments and
/// results use the existing JSON bridge while the callable itself preserves
/// identity and closures inside QuickJS.
#[no_mangle]
pub extern "C" fn thaw_js_call_handle_result(handle: u64, args_json: *const c_char) -> ThawResult {
    let args_json = to_str(args_json);
    let result = with_active_or_context(|ctx| {
        let target = Function::from_value(value_for_handle(&ctx, handle)?)
            .map_err(|_| format!("JavaScript value handle {handle} is not callable"))?;
        invoke_impl(
            ctx,
            target,
            &format!("JavaScript value #{handle}"),
            &args_json,
        )
    });
    match result {
        Ok(text) => ThawResult {
            value: CString::new(text).unwrap_or_default().into_raw(),
            error: std::ptr::null(),
        },
        Err(reason) => ThawResult {
            value: std::ptr::null(),
            error: CString::new(reason).unwrap_or_default().into_raw(),
        },
    }
}

/// `rquickjs::Error::Exception` doesn't carry the thrown value itself
/// (just a generic placeholder message) -- the real value has to be
/// fetched separately via `Ctx::catch`.
fn describe_exception(ctx: &Ctx<'_>) -> String {
    let exc = ctx.catch();
    if let Some(obj) = exc.as_object() {
        if let Ok(msg) = obj.get::<_, String>("message") {
            return msg;
        }
    }
    if let Some(s) = exc.as_string() {
        if let Ok(s) = s.to_string() {
            return s;
        }
    }
    format!("{exc:?}")
}

fn json_escape_string(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('"');
    for c in s.chars() {
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c if (c as u32) < 0x20 => out.push_str(&format!("\\u{:04x}", c as u32)),
            c => out.push(c),
        }
    }
    out.push('"');
    out
}
