// Real English time zone names for every IANA zone `Intl.
// supportedValuesOf("timeZone")` lists in real Node -- mechanically
// extracted from a real `node -e` run of `Intl.DateTimeFormat(...,
// {timeZoneName: 'long'|'longGeneric'})` (a real, authoritative ICU
// implementation) at two 2026 reference instants (a Jul 1 and a Jan
// 1, comfortably clear of any recent one-off zone-rule change, e.g.
// Kazakhstan's 2024 zone restructuring, which would otherwise corrupt
// a table generated around that date), never typed from memory --
// CLDR's ~150+ metazone names are exactly the kind of data real
// hallucination risk applies to. Regenerate by re-running the same
// `node -e` extraction against a newer Node/ICU/tzdata release if
// this ever drifts.
//
// `(iana_zone, standard_name, daylight_name, generic_name)` --
// `standard_name` == `daylight_name` for a zone with no real DST (290
// of the 418 zones below); `generic_name` (`timeZoneName:
// 'longGeneric'`, DST-independent, e.g. "Eastern Time" rather than
// "Eastern Standard/Daylight Time") often equals `standard_name` too,
// for a zone ICU has no distinct generic form for.
// `intl_time_zone_long_name` picks whichever the caller's own style/
// `dst` selects.
const TIME_ZONE_LONG_NAMES: &[(&str, &str, &str, &str)] = &[
    ("Africa/Abidjan", "Greenwich Mean Time", "Greenwich Mean Time", "Greenwich Mean Time"),
    ("Africa/Accra", "Greenwich Mean Time", "Greenwich Mean Time", "Greenwich Mean Time"),
    ("Africa/Addis_Ababa", "East Africa Time", "East Africa Time", "East Africa Time"),
    ("Africa/Algiers", "Central European Standard Time", "Central European Standard Time", "Central European Standard Time"),
    ("Africa/Asmera", "East Africa Time", "East Africa Time", "East Africa Time"),
    ("Africa/Bamako", "Greenwich Mean Time", "Greenwich Mean Time", "Greenwich Mean Time"),
    ("Africa/Bangui", "West Africa Time", "West Africa Time", "West Africa Time"),
    ("Africa/Banjul", "Greenwich Mean Time", "Greenwich Mean Time", "Greenwich Mean Time"),
    ("Africa/Bissau", "Greenwich Mean Time", "Greenwich Mean Time", "Greenwich Mean Time"),
    ("Africa/Blantyre", "Central Africa Time", "Central Africa Time", "Central Africa Time"),
    ("Africa/Brazzaville", "West Africa Time", "West Africa Time", "West Africa Time"),
    ("Africa/Bujumbura", "Central Africa Time", "Central Africa Time", "Central Africa Time"),
    ("Africa/Cairo", "Eastern European Standard Time", "Eastern European Summer Time", "Eastern European Time"),
    ("Africa/Casablanca", "GMT+01:00", "GMT+01:00", "Morocco Time"),
    ("Africa/Ceuta", "Central European Standard Time", "Central European Summer Time", "Central European Time"),
    ("Africa/Conakry", "Greenwich Mean Time", "Greenwich Mean Time", "Greenwich Mean Time"),
    ("Africa/Dakar", "Greenwich Mean Time", "Greenwich Mean Time", "Greenwich Mean Time"),
    ("Africa/Dar_es_Salaam", "East Africa Time", "East Africa Time", "East Africa Time"),
    ("Africa/Djibouti", "East Africa Time", "East Africa Time", "East Africa Time"),
    ("Africa/Douala", "West Africa Time", "West Africa Time", "West Africa Time"),
    ("Africa/El_Aaiun", "GMT+01:00", "GMT+01:00", "Western Sahara Time"),
    ("Africa/Freetown", "Greenwich Mean Time", "Greenwich Mean Time", "Greenwich Mean Time"),
    ("Africa/Gaborone", "Central Africa Time", "Central Africa Time", "Central Africa Time"),
    ("Africa/Harare", "Central Africa Time", "Central Africa Time", "Central Africa Time"),
    ("Africa/Johannesburg", "South Africa Standard Time", "South Africa Standard Time", "South Africa Standard Time"),
    ("Africa/Juba", "Central Africa Time", "Central Africa Time", "Central Africa Time"),
    ("Africa/Kampala", "East Africa Time", "East Africa Time", "East Africa Time"),
    ("Africa/Khartoum", "Central Africa Time", "Central Africa Time", "Central Africa Time"),
    ("Africa/Kigali", "Central Africa Time", "Central Africa Time", "Central Africa Time"),
    ("Africa/Kinshasa", "West Africa Time", "West Africa Time", "West Africa Time"),
    ("Africa/Lagos", "West Africa Time", "West Africa Time", "West Africa Time"),
    ("Africa/Libreville", "West Africa Time", "West Africa Time", "West Africa Time"),
    ("Africa/Lome", "Greenwich Mean Time", "Greenwich Mean Time", "Greenwich Mean Time"),
    ("Africa/Luanda", "West Africa Time", "West Africa Time", "West Africa Time"),
    ("Africa/Lubumbashi", "Central Africa Time", "Central Africa Time", "Central Africa Time"),
    ("Africa/Lusaka", "Central Africa Time", "Central Africa Time", "Central Africa Time"),
    ("Africa/Malabo", "West Africa Time", "West Africa Time", "West Africa Time"),
    ("Africa/Maputo", "Central Africa Time", "Central Africa Time", "Central Africa Time"),
    ("Africa/Maseru", "South Africa Standard Time", "South Africa Standard Time", "South Africa Standard Time"),
    ("Africa/Mbabane", "South Africa Standard Time", "South Africa Standard Time", "South Africa Standard Time"),
    ("Africa/Mogadishu", "East Africa Time", "East Africa Time", "East Africa Time"),
    ("Africa/Monrovia", "Greenwich Mean Time", "Greenwich Mean Time", "Greenwich Mean Time"),
    ("Africa/Nairobi", "East Africa Time", "East Africa Time", "East Africa Time"),
    ("Africa/Ndjamena", "West Africa Time", "West Africa Time", "West Africa Time"),
    ("Africa/Niamey", "West Africa Time", "West Africa Time", "West Africa Time"),
    ("Africa/Nouakchott", "Greenwich Mean Time", "Greenwich Mean Time", "Greenwich Mean Time"),
    ("Africa/Ouagadougou", "Greenwich Mean Time", "Greenwich Mean Time", "Greenwich Mean Time"),
    ("Africa/Porto-Novo", "West Africa Time", "West Africa Time", "West Africa Time"),
    ("Africa/Sao_Tome", "Greenwich Mean Time", "Greenwich Mean Time", "Greenwich Mean Time"),
    ("Africa/Tripoli", "Eastern European Standard Time", "Eastern European Standard Time", "Eastern European Standard Time"),
    ("Africa/Tunis", "Central European Standard Time", "Central European Standard Time", "Central European Standard Time"),
    ("Africa/Windhoek", "Central Africa Time", "Central Africa Time", "Central Africa Time"),
    ("America/Adak", "Hawaii-Aleutian Standard Time", "Hawaii-Aleutian Daylight Time", "Hawaii-Aleutian Time"),
    ("America/Anchorage", "Alaska Standard Time", "Alaska Daylight Time", "Alaska Time"),
    ("America/Anguilla", "Atlantic Standard Time", "Atlantic Standard Time", "Atlantic Standard Time"),
    ("America/Antigua", "Atlantic Standard Time", "Atlantic Standard Time", "Atlantic Standard Time"),
    ("America/Araguaina", "Brasilia Standard Time", "Brasilia Standard Time", "Brasilia Standard Time"),
    ("America/Argentina/La_Rioja", "Argentina Standard Time", "Argentina Standard Time", "Argentina Standard Time"),
    ("America/Argentina/Rio_Gallegos", "Argentina Standard Time", "Argentina Standard Time", "Argentina Standard Time"),
    ("America/Argentina/Salta", "Argentina Standard Time", "Argentina Standard Time", "Argentina Standard Time"),
    ("America/Argentina/San_Juan", "Argentina Standard Time", "Argentina Standard Time", "Argentina Standard Time"),
    ("America/Argentina/San_Luis", "Argentina Standard Time", "Argentina Standard Time", "Argentina Standard Time"),
    ("America/Argentina/Tucuman", "Argentina Standard Time", "Argentina Standard Time", "Argentina Standard Time"),
    ("America/Argentina/Ushuaia", "Argentina Standard Time", "Argentina Standard Time", "Argentina Standard Time"),
    ("America/Aruba", "Atlantic Standard Time", "Atlantic Standard Time", "Atlantic Standard Time"),
    ("America/Asuncion", "Paraguay Standard Time", "Paraguay Standard Time", "Paraguay Standard Time"),
    ("America/Bahia", "Brasilia Standard Time", "Brasilia Standard Time", "Brasilia Standard Time"),
    ("America/Bahia_Banderas", "Central Standard Time", "Central Standard Time", "Central Standard Time"),
    ("America/Barbados", "Atlantic Standard Time", "Atlantic Standard Time", "Atlantic Standard Time"),
    ("America/Belem", "Brasilia Standard Time", "Brasilia Standard Time", "Brasilia Standard Time"),
    ("America/Belize", "Central Standard Time", "Central Standard Time", "Central Standard Time"),
    ("America/Blanc-Sablon", "Atlantic Standard Time", "Atlantic Standard Time", "Atlantic Standard Time"),
    ("America/Boa_Vista", "Amazon Standard Time", "Amazon Standard Time", "Amazon Standard Time"),
    ("America/Bogota", "Colombia Standard Time", "Colombia Standard Time", "Colombia Standard Time"),
    ("America/Boise", "Mountain Standard Time", "Mountain Daylight Time", "Mountain Time"),
    ("America/Buenos_Aires", "Argentina Standard Time", "Argentina Standard Time", "Argentina Standard Time"),
    ("America/Cambridge_Bay", "Mountain Standard Time", "Mountain Daylight Time", "Mountain Time"),
    ("America/Campo_Grande", "Amazon Standard Time", "Amazon Standard Time", "Amazon Standard Time"),
    ("America/Cancun", "Eastern Standard Time", "Eastern Standard Time", "Eastern Standard Time"),
    ("America/Caracas", "Venezuela Time", "Venezuela Time", "Venezuela Time"),
    ("America/Catamarca", "Argentina Standard Time", "Argentina Standard Time", "Argentina Standard Time"),
    ("America/Cayenne", "French Guiana Time", "French Guiana Time", "French Guiana Time"),
    ("America/Cayman", "Eastern Standard Time", "Eastern Standard Time", "Eastern Standard Time"),
    ("America/Chicago", "Central Standard Time", "Central Daylight Time", "Central Time"),
    ("America/Chihuahua", "Central Standard Time", "Central Standard Time", "Central Standard Time"),
    ("America/Ciudad_Juarez", "Mountain Standard Time", "Mountain Daylight Time", "Mountain Time"),
    ("America/Coral_Harbour", "Eastern Standard Time", "Eastern Standard Time", "Eastern Standard Time"),
    ("America/Cordoba", "Argentina Standard Time", "Argentina Standard Time", "Argentina Standard Time"),
    ("America/Costa_Rica", "Central Standard Time", "Central Standard Time", "Central Standard Time"),
    ("America/Coyhaique", "GMT-03:00", "GMT-03:00", "Coyhaique Time"),
    ("America/Creston", "Mountain Standard Time", "Mountain Standard Time", "Mountain Standard Time"),
    ("America/Cuiaba", "Amazon Standard Time", "Amazon Standard Time", "Amazon Standard Time"),
    ("America/Curacao", "Atlantic Standard Time", "Atlantic Standard Time", "Atlantic Standard Time"),
    ("America/Danmarkshavn", "Greenwich Mean Time", "Greenwich Mean Time", "Greenwich Mean Time"),
    ("America/Dawson", "Yukon Time", "Yukon Time", "Yukon Time"),
    ("America/Dawson_Creek", "Mountain Standard Time", "Mountain Standard Time", "Mountain Standard Time"),
    ("America/Denver", "Mountain Standard Time", "Mountain Daylight Time", "Mountain Time"),
    ("America/Detroit", "Eastern Standard Time", "Eastern Daylight Time", "Eastern Time"),
    ("America/Dominica", "Atlantic Standard Time", "Atlantic Standard Time", "Atlantic Standard Time"),
    ("America/Edmonton", "Mountain Standard Time", "Mountain Daylight Time", "Mountain Time"),
    ("America/Eirunepe", "Acre Standard Time", "Acre Standard Time", "Acre Standard Time"),
    ("America/El_Salvador", "Central Standard Time", "Central Standard Time", "Central Standard Time"),
    ("America/Fort_Nelson", "Mountain Standard Time", "Mountain Standard Time", "Mountain Standard Time"),
    ("America/Fortaleza", "Brasilia Standard Time", "Brasilia Standard Time", "Brasilia Standard Time"),
    ("America/Glace_Bay", "Atlantic Standard Time", "Atlantic Daylight Time", "Atlantic Time"),
    ("America/Godthab", "Greenland Standard Time", "Greenland Summer Time", "Greenland Time"),
    ("America/Goose_Bay", "Atlantic Standard Time", "Atlantic Daylight Time", "Atlantic Time"),
    ("America/Grand_Turk", "Eastern Standard Time", "Eastern Daylight Time", "Eastern Time"),
    ("America/Grenada", "Atlantic Standard Time", "Atlantic Standard Time", "Atlantic Standard Time"),
    ("America/Guadeloupe", "Atlantic Standard Time", "Atlantic Standard Time", "Atlantic Standard Time"),
    ("America/Guatemala", "Central Standard Time", "Central Standard Time", "Central Standard Time"),
    ("America/Guayaquil", "Ecuador Time", "Ecuador Time", "Ecuador Time"),
    ("America/Guyana", "Guyana Time", "Guyana Time", "Guyana Time"),
    ("America/Halifax", "Atlantic Standard Time", "Atlantic Daylight Time", "Atlantic Time"),
    ("America/Havana", "Cuba Standard Time", "Cuba Daylight Time", "Cuba Time"),
    ("America/Hermosillo", "Mexican Pacific Standard Time", "Mexican Pacific Standard Time", "Mexican Pacific Standard Time"),
    ("America/Indiana/Knox", "Central Standard Time", "Central Daylight Time", "Central Time"),
    ("America/Indiana/Marengo", "Eastern Standard Time", "Eastern Daylight Time", "Eastern Time"),
    ("America/Indiana/Petersburg", "Eastern Standard Time", "Eastern Daylight Time", "Eastern Time"),
    ("America/Indiana/Tell_City", "Central Standard Time", "Central Daylight Time", "Central Time"),
    ("America/Indiana/Vevay", "Eastern Standard Time", "Eastern Daylight Time", "Eastern Time"),
    ("America/Indiana/Vincennes", "Eastern Standard Time", "Eastern Daylight Time", "Eastern Time"),
    ("America/Indiana/Winamac", "Eastern Standard Time", "Eastern Daylight Time", "Eastern Time"),
    ("America/Indianapolis", "Eastern Standard Time", "Eastern Daylight Time", "Eastern Time"),
    ("America/Inuvik", "Mountain Standard Time", "Mountain Daylight Time", "Mountain Time"),
    ("America/Iqaluit", "Eastern Standard Time", "Eastern Daylight Time", "Eastern Time"),
    ("America/Jamaica", "Eastern Standard Time", "Eastern Standard Time", "Eastern Standard Time"),
    ("America/Jujuy", "Argentina Standard Time", "Argentina Standard Time", "Argentina Standard Time"),
    ("America/Juneau", "Alaska Standard Time", "Alaska Daylight Time", "Alaska Time"),
    ("America/Kentucky/Monticello", "Eastern Standard Time", "Eastern Daylight Time", "Eastern Time"),
    ("America/Kralendijk", "Atlantic Standard Time", "Atlantic Standard Time", "Atlantic Standard Time"),
    ("America/La_Paz", "Bolivia Time", "Bolivia Time", "Bolivia Time"),
    ("America/Lima", "Peru Standard Time", "Peru Standard Time", "Peru Standard Time"),
    ("America/Los_Angeles", "Pacific Standard Time", "Pacific Daylight Time", "Pacific Time"),
    ("America/Louisville", "Eastern Standard Time", "Eastern Daylight Time", "Eastern Time"),
    ("America/Lower_Princes", "Atlantic Standard Time", "Atlantic Standard Time", "Atlantic Standard Time"),
    ("America/Maceio", "Brasilia Standard Time", "Brasilia Standard Time", "Brasilia Standard Time"),
    ("America/Managua", "Central Standard Time", "Central Standard Time", "Central Standard Time"),
    ("America/Manaus", "Amazon Standard Time", "Amazon Standard Time", "Amazon Standard Time"),
    ("America/Marigot", "Atlantic Standard Time", "Atlantic Standard Time", "Atlantic Standard Time"),
    ("America/Martinique", "Atlantic Standard Time", "Atlantic Standard Time", "Atlantic Standard Time"),
    ("America/Matamoros", "Central Standard Time", "Central Daylight Time", "Central Time"),
    ("America/Mazatlan", "Mexican Pacific Standard Time", "Mexican Pacific Standard Time", "Mexican Pacific Standard Time"),
    ("America/Mendoza", "Argentina Standard Time", "Argentina Standard Time", "Argentina Standard Time"),
    ("America/Menominee", "Central Standard Time", "Central Daylight Time", "Central Time"),
    ("America/Merida", "Central Standard Time", "Central Standard Time", "Central Standard Time"),
    ("America/Metlakatla", "Alaska Standard Time", "Alaska Daylight Time", "Alaska Time"),
    ("America/Mexico_City", "Central Standard Time", "Central Standard Time", "Central Standard Time"),
    ("America/Miquelon", "St. Pierre & Miquelon Standard Time", "St. Pierre & Miquelon Daylight Time", "St. Pierre & Miquelon Time"),
    ("America/Moncton", "Atlantic Standard Time", "Atlantic Daylight Time", "Atlantic Time"),
    ("America/Monterrey", "Central Standard Time", "Central Standard Time", "Central Standard Time"),
    ("America/Montevideo", "Uruguay Standard Time", "Uruguay Standard Time", "Uruguay Standard Time"),
    ("America/Montserrat", "Atlantic Standard Time", "Atlantic Standard Time", "Atlantic Standard Time"),
    ("America/Nassau", "Eastern Standard Time", "Eastern Daylight Time", "Eastern Time"),
    ("America/New_York", "Eastern Standard Time", "Eastern Daylight Time", "Eastern Time"),
    ("America/Nome", "Alaska Standard Time", "Alaska Daylight Time", "Alaska Time"),
    ("America/Noronha", "Fernando de Noronha Standard Time", "Fernando de Noronha Standard Time", "Fernando de Noronha Standard Time"),
    ("America/North_Dakota/Beulah", "Central Standard Time", "Central Daylight Time", "Central Time"),
    ("America/North_Dakota/Center", "Central Standard Time", "Central Daylight Time", "Central Time"),
    ("America/North_Dakota/New_Salem", "Central Standard Time", "Central Daylight Time", "Central Time"),
    ("America/Ojinaga", "Central Standard Time", "Central Daylight Time", "Central Time"),
    ("America/Panama", "Eastern Standard Time", "Eastern Standard Time", "Eastern Standard Time"),
    ("America/Paramaribo", "Suriname Time", "Suriname Time", "Suriname Time"),
    ("America/Phoenix", "Mountain Standard Time", "Mountain Standard Time", "Mountain Standard Time"),
    ("America/Port-au-Prince", "Eastern Standard Time", "Eastern Daylight Time", "Eastern Time"),
    ("America/Port_of_Spain", "Atlantic Standard Time", "Atlantic Standard Time", "Atlantic Standard Time"),
    ("America/Porto_Velho", "Amazon Standard Time", "Amazon Standard Time", "Amazon Standard Time"),
    ("America/Puerto_Rico", "Atlantic Standard Time", "Atlantic Standard Time", "Atlantic Standard Time"),
    ("America/Punta_Arenas", "GMT-03:00", "GMT-03:00", "Punta Arenas Time"),
    ("America/Rankin_Inlet", "Central Standard Time", "Central Daylight Time", "Central Time"),
    ("America/Recife", "Brasilia Standard Time", "Brasilia Standard Time", "Brasilia Standard Time"),
    ("America/Regina", "Central Standard Time", "Central Standard Time", "Central Standard Time"),
    ("America/Resolute", "Central Standard Time", "Central Daylight Time", "Central Time"),
    ("America/Rio_Branco", "Acre Standard Time", "Acre Standard Time", "Acre Standard Time"),
    ("America/Santarem", "Brasilia Standard Time", "Brasilia Standard Time", "Brasilia Standard Time"),
    ("America/Santiago", "Chile Standard Time", "Chile Summer Time", "Chile Time"),
    ("America/Santo_Domingo", "Atlantic Standard Time", "Atlantic Standard Time", "Atlantic Standard Time"),
    ("America/Sao_Paulo", "Brasilia Standard Time", "Brasilia Standard Time", "Brasilia Standard Time"),
    ("America/Scoresbysund", "Greenland Standard Time", "Greenland Summer Time", "Greenland Time"),
    ("America/Sitka", "Alaska Standard Time", "Alaska Daylight Time", "Alaska Time"),
    ("America/St_Barthelemy", "Atlantic Standard Time", "Atlantic Standard Time", "Atlantic Standard Time"),
    ("America/St_Johns", "Newfoundland Standard Time", "Newfoundland Daylight Time", "Newfoundland Time"),
    ("America/St_Kitts", "Atlantic Standard Time", "Atlantic Standard Time", "Atlantic Standard Time"),
    ("America/St_Lucia", "Atlantic Standard Time", "Atlantic Standard Time", "Atlantic Standard Time"),
    ("America/St_Thomas", "Atlantic Standard Time", "Atlantic Standard Time", "Atlantic Standard Time"),
    ("America/St_Vincent", "Atlantic Standard Time", "Atlantic Standard Time", "Atlantic Standard Time"),
    ("America/Swift_Current", "Central Standard Time", "Central Standard Time", "Central Standard Time"),
    ("America/Tegucigalpa", "Central Standard Time", "Central Standard Time", "Central Standard Time"),
    ("America/Thule", "Atlantic Standard Time", "Atlantic Daylight Time", "Atlantic Time"),
    ("America/Tijuana", "Pacific Standard Time", "Pacific Daylight Time", "Pacific Time"),
    ("America/Toronto", "Eastern Standard Time", "Eastern Daylight Time", "Eastern Time"),
    ("America/Tortola", "Atlantic Standard Time", "Atlantic Standard Time", "Atlantic Standard Time"),
    ("America/Vancouver", "Pacific Standard Time", "Pacific Daylight Time", "Pacific Time"),
    ("America/Whitehorse", "Yukon Time", "Yukon Time", "Yukon Time"),
    ("America/Winnipeg", "Central Standard Time", "Central Daylight Time", "Central Time"),
    ("America/Yakutat", "Alaska Standard Time", "Alaska Daylight Time", "Alaska Time"),
    ("Antarctica/Casey", "Australian Western Standard Time", "Australian Western Standard Time", "Australian Western Standard Time"),
    ("Antarctica/Davis", "Davis Time", "Davis Time", "Davis Time"),
    ("Antarctica/DumontDUrville", "Dumont d’Urville Time", "Dumont d’Urville Time", "Dumont d’Urville Time"),
    ("Antarctica/Macquarie", "Australian Eastern Standard Time", "Australian Eastern Daylight Time", "Australian Eastern Time"),
    ("Antarctica/Mawson", "Mawson Time", "Mawson Time", "Mawson Time"),
    ("Antarctica/McMurdo", "New Zealand Standard Time", "New Zealand Daylight Time", "New Zealand Time"),
    ("Antarctica/Palmer", "GMT-03:00", "GMT-03:00", "Palmer Land Time"),
    ("Antarctica/Rothera", "Rothera Time", "Rothera Time", "Rothera Time"),
    ("Antarctica/Syowa", "Syowa Time", "Syowa Time", "Syowa Time"),
    ("Antarctica/Troll", "Greenwich Mean Time", "GMT+02:00", "Troll Station Time"),
    ("Antarctica/Vostok", "Vostok Time", "Vostok Time", "Vostok Time"),
    ("Arctic/Longyearbyen", "Central European Standard Time", "Central European Summer Time", "Central European Time"),
    ("Asia/Aden", "Arabian Standard Time", "Arabian Standard Time", "Arabian Standard Time"),
    ("Asia/Almaty", "Kazakhstan Time", "Kazakhstan Time", "Kazakhstan Time"),
    ("Asia/Amman", "GMT+03:00", "GMT+03:00", "Jordan Time"),
    ("Asia/Anadyr", "Kamchatka Standard Time", "Kamchatka Standard Time", "Kamchatka Standard Time"),
    ("Asia/Aqtau", "Kazakhstan Time", "Kazakhstan Time", "Kazakhstan Time"),
    ("Asia/Aqtobe", "Kazakhstan Time", "Kazakhstan Time", "Kazakhstan Time"),
    ("Asia/Ashgabat", "Turkmenistan Standard Time", "Turkmenistan Standard Time", "Turkmenistan Standard Time"),
    ("Asia/Atyrau", "Kazakhstan Time", "Kazakhstan Time", "Kazakhstan Time"),
    ("Asia/Baghdad", "Arabian Standard Time", "Arabian Standard Time", "Arabian Standard Time"),
    ("Asia/Bahrain", "Arabian Standard Time", "Arabian Standard Time", "Arabian Standard Time"),
    ("Asia/Baku", "Azerbaijan Standard Time", "Azerbaijan Standard Time", "Azerbaijan Standard Time"),
    ("Asia/Bangkok", "Indochina Time", "Indochina Time", "Indochina Time"),
    ("Asia/Barnaul", "Krasnoyarsk Standard Time", "Krasnoyarsk Standard Time", "Krasnoyarsk Standard Time"),
    ("Asia/Beirut", "Eastern European Standard Time", "Eastern European Summer Time", "Eastern European Time"),
    ("Asia/Bishkek", "Kyrgyzstan Time", "Kyrgyzstan Time", "Kyrgyzstan Time"),
    ("Asia/Brunei", "Brunei Time", "Brunei Time", "Brunei Time"),
    ("Asia/Calcutta", "India Standard Time", "India Standard Time", "India Standard Time"),
    ("Asia/Chita", "Yakutsk Standard Time", "Yakutsk Standard Time", "Yakutsk Standard Time"),
    ("Asia/Colombo", "India Standard Time", "India Standard Time", "India Standard Time"),
    ("Asia/Damascus", "GMT+03:00", "GMT+03:00", "Syria Time"),
    ("Asia/Dhaka", "Bangladesh Standard Time", "Bangladesh Standard Time", "Bangladesh Standard Time"),
    ("Asia/Dili", "Timor-Leste Time", "Timor-Leste Time", "Timor-Leste Time"),
    ("Asia/Dubai", "Gulf Standard Time", "Gulf Standard Time", "Gulf Standard Time"),
    ("Asia/Dushanbe", "Tajikistan Time", "Tajikistan Time", "Tajikistan Time"),
    ("Asia/Famagusta", "Eastern European Standard Time", "Eastern European Summer Time", "Eastern European Time"),
    ("Asia/Gaza", "Eastern European Standard Time", "Eastern European Summer Time", "Eastern European Time"),
    ("Asia/Hebron", "Eastern European Standard Time", "Eastern European Summer Time", "Eastern European Time"),
    ("Asia/Hong_Kong", "Hong Kong Standard Time", "Hong Kong Standard Time", "Hong Kong Standard Time"),
    ("Asia/Hovd", "Khovd Standard Time", "Khovd Standard Time", "Khovd Standard Time"),
    ("Asia/Irkutsk", "Irkutsk Standard Time", "Irkutsk Standard Time", "Irkutsk Standard Time"),
    ("Asia/Jakarta", "Western Indonesia Time", "Western Indonesia Time", "Western Indonesia Time"),
    ("Asia/Jayapura", "Eastern Indonesia Time", "Eastern Indonesia Time", "Eastern Indonesia Time"),
    ("Asia/Jerusalem", "Israel Standard Time", "Israel Daylight Time", "Israel Time"),
    ("Asia/Kabul", "Afghanistan Time", "Afghanistan Time", "Afghanistan Time"),
    ("Asia/Kamchatka", "Kamchatka Standard Time", "Kamchatka Standard Time", "Kamchatka Standard Time"),
    ("Asia/Karachi", "Pakistan Standard Time", "Pakistan Standard Time", "Pakistan Standard Time"),
    ("Asia/Katmandu", "Nepal Time", "Nepal Time", "Nepal Time"),
    ("Asia/Khandyga", "Yakutsk Standard Time", "Yakutsk Standard Time", "Yakutsk Standard Time"),
    ("Asia/Krasnoyarsk", "Krasnoyarsk Standard Time", "Krasnoyarsk Standard Time", "Krasnoyarsk Standard Time"),
    ("Asia/Kuala_Lumpur", "Malaysia Time", "Malaysia Time", "Malaysia Time"),
    ("Asia/Kuching", "Malaysia Time", "Malaysia Time", "Malaysia Time"),
    ("Asia/Kuwait", "Arabian Standard Time", "Arabian Standard Time", "Arabian Standard Time"),
    ("Asia/Macau", "China Standard Time", "China Standard Time", "China Standard Time"),
    ("Asia/Magadan", "Magadan Standard Time", "Magadan Standard Time", "Magadan Standard Time"),
    ("Asia/Makassar", "Central Indonesia Time", "Central Indonesia Time", "Central Indonesia Time"),
    ("Asia/Manila", "Philippine Standard Time", "Philippine Standard Time", "Philippine Standard Time"),
    ("Asia/Muscat", "Gulf Standard Time", "Gulf Standard Time", "Gulf Standard Time"),
    ("Asia/Nicosia", "Eastern European Standard Time", "Eastern European Summer Time", "Eastern European Time"),
    ("Asia/Novokuznetsk", "Krasnoyarsk Standard Time", "Krasnoyarsk Standard Time", "Krasnoyarsk Standard Time"),
    ("Asia/Novosibirsk", "Krasnoyarsk Standard Time", "Krasnoyarsk Standard Time", "Krasnoyarsk Standard Time"),
    ("Asia/Omsk", "Omsk Standard Time", "Omsk Standard Time", "Omsk Standard Time"),
    ("Asia/Oral", "Kazakhstan Time", "Kazakhstan Time", "Kazakhstan Time"),
    ("Asia/Phnom_Penh", "Indochina Time", "Indochina Time", "Indochina Time"),
    ("Asia/Pontianak", "Western Indonesia Time", "Western Indonesia Time", "Western Indonesia Time"),
    ("Asia/Pyongyang", "Korean Standard Time", "Korean Standard Time", "Korean Standard Time"),
    ("Asia/Qatar", "Arabian Standard Time", "Arabian Standard Time", "Arabian Standard Time"),
    ("Asia/Qostanay", "Kazakhstan Time", "Kazakhstan Time", "Kazakhstan Time"),
    ("Asia/Qyzylorda", "Kazakhstan Time", "Kazakhstan Time", "Kazakhstan Time"),
    ("Asia/Rangoon", "Myanmar Time", "Myanmar Time", "Myanmar Time"),
    ("Asia/Riyadh", "Arabian Standard Time", "Arabian Standard Time", "Arabian Standard Time"),
    ("Asia/Saigon", "Indochina Time", "Indochina Time", "Indochina Time"),
    ("Asia/Sakhalin", "Magadan Standard Time", "Magadan Standard Time", "Magadan Standard Time"),
    ("Asia/Samarkand", "Uzbekistan Standard Time", "Uzbekistan Standard Time", "Uzbekistan Standard Time"),
    ("Asia/Seoul", "Korean Standard Time", "Korean Standard Time", "Korean Standard Time"),
    ("Asia/Shanghai", "China Standard Time", "China Standard Time", "China Standard Time"),
    ("Asia/Singapore", "Singapore Standard Time", "Singapore Standard Time", "Singapore Standard Time"),
    ("Asia/Srednekolymsk", "Magadan Standard Time", "Magadan Standard Time", "Magadan Standard Time"),
    ("Asia/Taipei", "Taiwan Standard Time", "Taiwan Standard Time", "Taiwan Standard Time"),
    ("Asia/Tashkent", "Uzbekistan Standard Time", "Uzbekistan Standard Time", "Uzbekistan Standard Time"),
    ("Asia/Tbilisi", "Georgia Standard Time", "Georgia Standard Time", "Georgia Standard Time"),
    ("Asia/Tehran", "Iran Standard Time", "Iran Standard Time", "Iran Standard Time"),
    ("Asia/Thimphu", "Bhutan Time", "Bhutan Time", "Bhutan Time"),
    ("Asia/Tokyo", "Japan Standard Time", "Japan Standard Time", "Japan Standard Time"),
    ("Asia/Tomsk", "Krasnoyarsk Standard Time", "Krasnoyarsk Standard Time", "Krasnoyarsk Standard Time"),
    ("Asia/Ulaanbaatar", "Ulaanbaatar Standard Time", "Ulaanbaatar Standard Time", "Ulaanbaatar Standard Time"),
    ("Asia/Urumqi", "GMT+06:00", "GMT+06:00", "Ürümqi Time"),
    ("Asia/Ust-Nera", "Vladivostok Standard Time", "Vladivostok Standard Time", "Vladivostok Standard Time"),
    ("Asia/Vientiane", "Indochina Time", "Indochina Time", "Indochina Time"),
    ("Asia/Vladivostok", "Vladivostok Standard Time", "Vladivostok Standard Time", "Vladivostok Standard Time"),
    ("Asia/Yakutsk", "Yakutsk Standard Time", "Yakutsk Standard Time", "Yakutsk Standard Time"),
    ("Asia/Yekaterinburg", "Yekaterinburg Standard Time", "Yekaterinburg Standard Time", "Yekaterinburg Standard Time"),
    ("Asia/Yerevan", "Armenia Standard Time", "Armenia Standard Time", "Armenia Standard Time"),
    ("Atlantic/Azores", "Azores Standard Time", "Azores Summer Time", "Azores Time"),
    ("Atlantic/Bermuda", "Atlantic Standard Time", "Atlantic Daylight Time", "Atlantic Time"),
    ("Atlantic/Canary", "Western European Standard Time", "Western European Summer Time", "Western European Time"),
    ("Atlantic/Cape_Verde", "Cape Verde Standard Time", "Cape Verde Standard Time", "Cape Verde Standard Time"),
    ("Atlantic/Faeroe", "Western European Standard Time", "Western European Summer Time", "Western European Time"),
    ("Atlantic/Madeira", "Western European Standard Time", "Western European Summer Time", "Western European Time"),
    ("Atlantic/Reykjavik", "Greenwich Mean Time", "Greenwich Mean Time", "Greenwich Mean Time"),
    ("Atlantic/South_Georgia", "South Georgia Time", "South Georgia Time", "South Georgia Time"),
    ("Atlantic/St_Helena", "Greenwich Mean Time", "Greenwich Mean Time", "Greenwich Mean Time"),
    ("Atlantic/Stanley", "Falkland Islands Standard Time", "Falkland Islands Standard Time", "Falkland Islands Standard Time"),
    ("Australia/Adelaide", "Australian Central Standard Time", "Australian Central Daylight Time", "Australian Central Time"),
    ("Australia/Brisbane", "Australian Eastern Standard Time", "Australian Eastern Standard Time", "Australian Eastern Standard Time"),
    ("Australia/Broken_Hill", "Australian Central Standard Time", "Australian Central Daylight Time", "Australian Central Time"),
    ("Australia/Darwin", "Australian Central Standard Time", "Australian Central Standard Time", "Australian Central Standard Time"),
    ("Australia/Eucla", "Australian Central Western Standard Time", "Australian Central Western Standard Time", "Australian Central Western Standard Time"),
    ("Australia/Hobart", "Australian Eastern Standard Time", "Australian Eastern Daylight Time", "Australian Eastern Time"),
    ("Australia/Lindeman", "Australian Eastern Standard Time", "Australian Eastern Standard Time", "Australian Eastern Standard Time"),
    ("Australia/Lord_Howe", "Lord Howe Standard Time", "Lord Howe Daylight Time", "Lord Howe Time"),
    ("Australia/Melbourne", "Australian Eastern Standard Time", "Australian Eastern Daylight Time", "Australian Eastern Time"),
    ("Australia/Perth", "Australian Western Standard Time", "Australian Western Standard Time", "Australian Western Standard Time"),
    ("Australia/Sydney", "Australian Eastern Standard Time", "Australian Eastern Daylight Time", "Australian Eastern Time"),
    ("Europe/Amsterdam", "Central European Standard Time", "Central European Summer Time", "Central European Time"),
    ("Europe/Andorra", "Central European Standard Time", "Central European Summer Time", "Central European Time"),
    ("Europe/Astrakhan", "Samara Standard Time", "Samara Standard Time", "Samara Standard Time"),
    ("Europe/Athens", "Eastern European Standard Time", "Eastern European Summer Time", "Eastern European Time"),
    ("Europe/Belgrade", "Central European Standard Time", "Central European Summer Time", "Central European Time"),
    ("Europe/Berlin", "Central European Standard Time", "Central European Summer Time", "Central European Time"),
    ("Europe/Bratislava", "Central European Standard Time", "Central European Summer Time", "Central European Time"),
    ("Europe/Brussels", "Central European Standard Time", "Central European Summer Time", "Central European Time"),
    ("Europe/Bucharest", "Eastern European Standard Time", "Eastern European Summer Time", "Eastern European Time"),
    ("Europe/Budapest", "Central European Standard Time", "Central European Summer Time", "Central European Time"),
    ("Europe/Busingen", "Central European Standard Time", "Central European Summer Time", "Central European Time"),
    ("Europe/Chisinau", "Eastern European Standard Time", "Eastern European Summer Time", "Eastern European Time"),
    ("Europe/Copenhagen", "Central European Standard Time", "Central European Summer Time", "Central European Time"),
    ("Europe/Dublin", "Greenwich Mean Time", "Irish Standard Time", "Ireland Time"),
    ("Europe/Gibraltar", "Central European Standard Time", "Central European Summer Time", "Central European Time"),
    ("Europe/Guernsey", "Greenwich Mean Time", "GMT+01:00", "Guernsey Time"),
    ("Europe/Helsinki", "Eastern European Standard Time", "Eastern European Summer Time", "Eastern European Time"),
    ("Europe/Isle_of_Man", "Greenwich Mean Time", "GMT+01:00", "Isle of Man Time"),
    ("Europe/Istanbul", "Türkiye Standard Time", "Türkiye Standard Time", "Türkiye Standard Time"),
    ("Europe/Jersey", "Greenwich Mean Time", "GMT+01:00", "Jersey Time"),
    ("Europe/Kaliningrad", "Eastern European Standard Time", "Eastern European Standard Time", "Eastern European Standard Time"),
    ("Europe/Kiev", "Eastern European Standard Time", "Eastern European Summer Time", "Eastern European Time"),
    ("Europe/Kirov", "Moscow Standard Time", "Moscow Standard Time", "Moscow Standard Time"),
    ("Europe/Lisbon", "Western European Standard Time", "Western European Summer Time", "Western European Time"),
    ("Europe/Ljubljana", "Central European Standard Time", "Central European Summer Time", "Central European Time"),
    ("Europe/London", "Greenwich Mean Time", "British Summer Time", "United Kingdom Time"),
    ("Europe/Luxembourg", "Central European Standard Time", "Central European Summer Time", "Central European Time"),
    ("Europe/Madrid", "Central European Standard Time", "Central European Summer Time", "Central European Time"),
    ("Europe/Malta", "Central European Standard Time", "Central European Summer Time", "Central European Time"),
    ("Europe/Mariehamn", "Eastern European Standard Time", "Eastern European Summer Time", "Eastern European Time"),
    ("Europe/Minsk", "Moscow Standard Time", "Moscow Standard Time", "Moscow Standard Time"),
    ("Europe/Monaco", "Central European Standard Time", "Central European Summer Time", "Central European Time"),
    ("Europe/Moscow", "Moscow Standard Time", "Moscow Standard Time", "Moscow Standard Time"),
    ("Europe/Oslo", "Central European Standard Time", "Central European Summer Time", "Central European Time"),
    ("Europe/Paris", "Central European Standard Time", "Central European Summer Time", "Central European Time"),
    ("Europe/Podgorica", "Central European Standard Time", "Central European Summer Time", "Central European Time"),
    ("Europe/Prague", "Central European Standard Time", "Central European Summer Time", "Central European Time"),
    ("Europe/Riga", "Eastern European Standard Time", "Eastern European Summer Time", "Eastern European Time"),
    ("Europe/Rome", "Central European Standard Time", "Central European Summer Time", "Central European Time"),
    ("Europe/Samara", "Samara Standard Time", "Samara Standard Time", "Samara Standard Time"),
    ("Europe/San_Marino", "Central European Standard Time", "Central European Summer Time", "Central European Time"),
    ("Europe/Sarajevo", "Central European Standard Time", "Central European Summer Time", "Central European Time"),
    ("Europe/Saratov", "Samara Standard Time", "Samara Standard Time", "Samara Standard Time"),
    ("Europe/Simferopol", "Moscow Standard Time", "Moscow Standard Time", "Moscow Standard Time"),
    ("Europe/Skopje", "Central European Standard Time", "Central European Summer Time", "Central European Time"),
    ("Europe/Sofia", "Eastern European Standard Time", "Eastern European Summer Time", "Eastern European Time"),
    ("Europe/Stockholm", "Central European Standard Time", "Central European Summer Time", "Central European Time"),
    ("Europe/Tallinn", "Eastern European Standard Time", "Eastern European Summer Time", "Eastern European Time"),
    ("Europe/Tirane", "Central European Standard Time", "Central European Summer Time", "Central European Time"),
    ("Europe/Ulyanovsk", "Samara Standard Time", "Samara Standard Time", "Samara Standard Time"),
    ("Europe/Vaduz", "Central European Standard Time", "Central European Summer Time", "Central European Time"),
    ("Europe/Vatican", "Central European Standard Time", "Central European Summer Time", "Central European Time"),
    ("Europe/Vienna", "Central European Standard Time", "Central European Summer Time", "Central European Time"),
    ("Europe/Vilnius", "Eastern European Standard Time", "Eastern European Summer Time", "Eastern European Time"),
    ("Europe/Volgograd", "Moscow Standard Time", "Moscow Standard Time", "Moscow Standard Time"),
    ("Europe/Warsaw", "Central European Standard Time", "Central European Summer Time", "Central European Time"),
    ("Europe/Zagreb", "Central European Standard Time", "Central European Summer Time", "Central European Time"),
    ("Europe/Zurich", "Central European Standard Time", "Central European Summer Time", "Central European Time"),
    ("Indian/Antananarivo", "East Africa Time", "East Africa Time", "East Africa Time"),
    ("Indian/Chagos", "Indian Ocean Time", "Indian Ocean Time", "Indian Ocean Time"),
    ("Indian/Christmas", "Christmas Island Time", "Christmas Island Time", "Christmas Island Time"),
    ("Indian/Cocos", "Cocos Islands Time", "Cocos Islands Time", "Cocos Islands Time"),
    ("Indian/Comoro", "East Africa Time", "East Africa Time", "East Africa Time"),
    ("Indian/Kerguelen", "French Southern & Antarctic Time", "French Southern & Antarctic Time", "French Southern & Antarctic Time"),
    ("Indian/Mahe", "Seychelles Time", "Seychelles Time", "Seychelles Time"),
    ("Indian/Maldives", "Maldives Time", "Maldives Time", "Maldives Time"),
    ("Indian/Mauritius", "Mauritius Standard Time", "Mauritius Standard Time", "Mauritius Standard Time"),
    ("Indian/Mayotte", "East Africa Time", "East Africa Time", "East Africa Time"),
    ("Indian/Reunion", "Réunion Time", "Réunion Time", "Réunion Time"),
    ("Pacific/Apia", "Samoa Standard Time", "Samoa Standard Time", "Samoa Standard Time"),
    ("Pacific/Auckland", "New Zealand Standard Time", "New Zealand Daylight Time", "New Zealand Time"),
    ("Pacific/Bougainville", "GMT+11:00", "GMT+11:00", "Bougainville Time"),
    ("Pacific/Chatham", "Chatham Standard Time", "Chatham Daylight Time", "Chatham Time"),
    ("Pacific/Easter", "Easter Island Standard Time", "Easter Island Summer Time", "Easter Island Time"),
    ("Pacific/Efate", "Vanuatu Standard Time", "Vanuatu Standard Time", "Vanuatu Standard Time"),
    ("Pacific/Enderbury", "Phoenix Islands Time", "Phoenix Islands Time", "Phoenix Islands Time"),
    ("Pacific/Fakaofo", "Tokelau Time", "Tokelau Time", "Tokelau Time"),
    ("Pacific/Fiji", "Fiji Standard Time", "Fiji Standard Time", "Fiji Standard Time"),
    ("Pacific/Funafuti", "Tuvalu Time", "Tuvalu Time", "Tuvalu Time"),
    ("Pacific/Galapagos", "Galapagos Time", "Galapagos Time", "Galapagos Time"),
    ("Pacific/Gambier", "Gambier Time", "Gambier Time", "Gambier Time"),
    ("Pacific/Guadalcanal", "Solomon Islands Time", "Solomon Islands Time", "Solomon Islands Time"),
    ("Pacific/Guam", "Chamorro Standard Time", "Chamorro Standard Time", "Chamorro Standard Time"),
    ("Pacific/Honolulu", "Hawaii-Aleutian Standard Time", "Hawaii-Aleutian Standard Time", "Hawaii-Aleutian Standard Time"),
    ("Pacific/Kiritimati", "Line Islands Time", "Line Islands Time", "Line Islands Time"),
    ("Pacific/Kosrae", "Kosrae Time", "Kosrae Time", "Kosrae Time"),
    ("Pacific/Kwajalein", "Marshall Islands Time", "Marshall Islands Time", "Marshall Islands Time"),
    ("Pacific/Majuro", "Marshall Islands Time", "Marshall Islands Time", "Marshall Islands Time"),
    ("Pacific/Marquesas", "Marquesas Time", "Marquesas Time", "Marquesas Time"),
    ("Pacific/Midway", "American Samoa Standard Time", "American Samoa Standard Time", "American Samoa Standard Time"),
    ("Pacific/Nauru", "Nauru Time", "Nauru Time", "Nauru Time"),
    ("Pacific/Niue", "Niue Time", "Niue Time", "Niue Time"),
    ("Pacific/Norfolk", "Norfolk Island Standard Time", "Norfolk Island Daylight Time", "Norfolk Island Time"),
    ("Pacific/Noumea", "New Caledonia Standard Time", "New Caledonia Standard Time", "New Caledonia Standard Time"),
    ("Pacific/Pago_Pago", "American Samoa Standard Time", "American Samoa Standard Time", "American Samoa Standard Time"),
    ("Pacific/Palau", "Palau Time", "Palau Time", "Palau Time"),
    ("Pacific/Pitcairn", "Pitcairn Time", "Pitcairn Time", "Pitcairn Time"),
    ("Pacific/Ponape", "Pohnpei Time", "Pohnpei Time", "Pohnpei Time"),
    ("Pacific/Port_Moresby", "Papua New Guinea Time", "Papua New Guinea Time", "Papua New Guinea Time"),
    ("Pacific/Rarotonga", "Cook Islands Standard Time", "Cook Islands Standard Time", "Cook Islands Standard Time"),
    ("Pacific/Saipan", "Chamorro Standard Time", "Chamorro Standard Time", "Chamorro Standard Time"),
    ("Pacific/Tahiti", "Tahiti Time", "Tahiti Time", "Tahiti Time"),
    ("Pacific/Tarawa", "Gilbert Islands Time", "Gilbert Islands Time", "Gilbert Islands Time"),
    ("Pacific/Tongatapu", "Tonga Standard Time", "Tonga Standard Time", "Tonga Standard Time"),
    ("Pacific/Truk", "Chuuk Time", "Chuuk Time", "Chuuk Time"),
    ("Pacific/Wake", "Wake Island Time", "Wake Island Time", "Wake Island Time"),
    ("Pacific/Wallis", "Wallis & Futuna Time", "Wallis & Futuna Time", "Wallis & Futuna Time"),
];

/// Looks up a real English time zone name for `tz_name`: `generic`
/// selects `generic_name` (DST-independent, `timeZoneName:
/// 'longGeneric'`); otherwise `dst` (already determined by `jiff`)
/// picks `standard_name`/`daylight_name` (`timeZoneName: 'long'`).
/// `None` for a zone this table has no entry for (shouldn't happen for
/// any of the 418 real IANA names above, but `intl_zoned_parts_json`'s
/// caller falls back to the synthesized `"GMT+H:MM"` form gracefully
/// either way).
fn intl_time_zone_long_name(tz_name: &str, dst: bool, generic: bool) -> Option<&'static str> {
    TIME_ZONE_LONG_NAMES
        .iter()
        .find(|(zone, ..)| *zone == tz_name)
        .map(|(_, standard, daylight, generic_name)| {
            if generic {
                *generic_name
            } else if dst {
                *daylight
            } else {
                *standard
            }
        })
}
