pub(super) fn source(name: &str) -> Option<&'static str> {
    match name {
        "diagnostics_channel" => Some(
            "var registry = globalThis.__thawDiagnosticChannels || (globalThis.__thawDiagnosticChannels = new Map());\n\
             function Channel(name) { this.name = String(name); this._subscribers = []; this._stores = []; }\n\
             Object.defineProperty(Channel.prototype, 'hasSubscribers', { get: function() { return this._subscribers.length !== 0; } });\n\
             Channel.prototype.subscribe = function(callback) { if (typeof callback !== 'function') throw new TypeError('callback must be a function'); if (this._subscribers.indexOf(callback) < 0) this._subscribers.push(callback); };\n\
             Channel.prototype.unsubscribe = function(callback) { var index = this._subscribers.indexOf(callback); if (index < 0) return false; this._subscribers.splice(index, 1); return true; };\n\
             Channel.prototype.bindStore = function(store, transform) { if (!store || typeof store.run !== 'function') throw new TypeError('store must provide run'); this._stores.push({ store: store, transform: typeof transform === 'function' ? transform : function(value) { return value; } }); };\n\
             Channel.prototype.unbindStore = function(store) { var before = this._stores.length; this._stores = this._stores.filter(function(binding) { return binding.store !== store; }); return before !== this._stores.length; };\n\
             Channel.prototype.runStores = function(data, callback, thisArg) { var args = Array.prototype.slice.call(arguments, 3); var bindings = this._stores.slice(); function invoke(index) { if (index === bindings.length) return callback.apply(thisArg, args); var binding = bindings[index]; return binding.store.run(binding.transform(data), function() { return invoke(index + 1); }); } return invoke(0); };\n\
             Channel.prototype.publish = function(data) { var self = this; return this.runStores(data, function() { self._subscribers.slice().forEach(function(callback) { callback(data, self.name); }); }); };\n\
             function channel(name) { var key = String(name); if (!registry.has(key)) registry.set(key, new Channel(key)); return registry.get(key); }\n\
             function hasSubscribers(name) { return channel(name).hasSubscribers; }\n\
             function subscribe(name, callback) { channel(name).subscribe(callback); }\n\
             function unsubscribe(name, callback) { return channel(name).unsubscribe(callback); }\n\
             function tracingChannel(nameOrChannels) {\n\
             \x20\x20var channels = typeof nameOrChannels === 'string' ? { start: channel('tracing:' + nameOrChannels + ':start'), end: channel('tracing:' + nameOrChannels + ':end'), asyncStart: channel('tracing:' + nameOrChannels + ':asyncStart'), asyncEnd: channel('tracing:' + nameOrChannels + ':asyncEnd'), error: channel('tracing:' + nameOrChannels + ':error') } : nameOrChannels;\n\
             \x20\x20return { start: channels.start, end: channels.end, asyncStart: channels.asyncStart, asyncEnd: channels.asyncEnd, error: channels.error, traceSync: function(callback, context, thisArg) { var args = Array.prototype.slice.call(arguments, 3); context = context || {}; channels.start.publish(context); try { var result = channels.start.runStores(context, callback, thisArg, ...args); context.result = result; channels.end.publish(context); return result; } catch (error) { context.error = error; channels.error.publish(context); channels.end.publish(context); throw error; } }, tracePromise: function(callback, context, thisArg) { var args = Array.prototype.slice.call(arguments, 3); context = context || {}; channels.start.publish(context); return Promise.resolve().then(function() { return channels.start.runStores(context, callback, thisArg, ...args); }).then(function(result) { context.result = result; channels.asyncStart.publish(context); channels.asyncEnd.publish(context); channels.end.publish(context); return result; }, function(error) { context.error = error; channels.error.publish(context); channels.asyncStart.publish(context); channels.asyncEnd.publish(context); channels.end.publish(context); throw error; }); }, traceCallback: function(callback, position, context, thisArg) { var args = Array.prototype.slice.call(arguments, 4); context = context || {}; channels.start.publish(context); var original = args[position]; args[position] = function(error, result) { if (error) { context.error = error; channels.error.publish(context); } else context.result = result; channels.asyncStart.publish(context); try { return original.apply(this, arguments); } finally { channels.asyncEnd.publish(context); channels.end.publish(context); } }; return channels.start.runStores(context, callback, thisArg, ...args); } };\n\
             }\n\
             module.exports = { channel: channel, hasSubscribers: hasSubscribers, subscribe: subscribe, unsubscribe: unsubscribe, tracingChannel: tracingChannel, Channel: Channel }; module.exports.default = module.exports; module.exports.__esModule = true;\n",
        ),
        "trace_events" => Some(
            r#"var categoryCounts = new Map();
             function normalizeCategories(categories) { if (!Array.isArray(categories) || !categories.length) throw new TypeError('options.categories must be a non-empty array'); return Array.from(new Set(categories.map(String))); }
             function Tracing(options) { if (!(this instanceof Tracing)) return new Tracing(options); if (!options || typeof options !== 'object') throw new TypeError('options must be an object'); this.categories = normalizeCategories(options.categories); this.enabled = false; }
             Tracing.prototype.enable = function() { if (this.enabled) return; this.enabled = true; this.categories.forEach(function(category) { categoryCounts.set(category, (categoryCounts.get(category) || 0) + 1); }); };
             Tracing.prototype.disable = function() { if (!this.enabled) return; this.enabled = false; this.categories.forEach(function(category) { var count = (categoryCounts.get(category) || 0) - 1; if (count > 0) categoryCounts.set(category, count); else categoryCounts.delete(category); }); };
             function createTracing(options) { return new Tracing(options); }
             function getEnabledCategories() { return Array.from(categoryCounts.keys()).sort().join(','); }
             module.exports = { Tracing: Tracing, createTracing: createTracing, getEnabledCategories: getEnabledCategories }; module.exports.default = module.exports; module.exports.__esModule = true;
"#,
        ),
        "inspector" => Some(concat!(
            r#"var EventEmitter = require('node:events'), opened = false, inspectorUrl, isolateId = 'thaw-quickjs-main';
             function remoteObject(value, returnByValue) { var type = value === null ? 'object' : typeof value, result = { type: type }; if (value === null) result.subtype = 'null'; else if (type === 'undefined') result.description = 'undefined'; else if (type === 'number' && !Number.isFinite(value)) { result.unserializableValue = String(value); result.description = String(value); } else if (type === 'bigint') { result.unserializableValue = String(value) + 'n'; result.description = String(value) + 'n'; } else if (type === 'symbol' || type === 'function') result.description = String(value); else if (type === 'object' && !returnByValue) { result.className = value.constructor && value.constructor.name || 'Object'; result.description = result.className; } else result.value = value; return result; }
             function Session() { if (!(this instanceof Session)) return new Session(); EventEmitter.call(this); this._connected = false; }
             Session.prototype = Object.create(EventEmitter.prototype); Session.prototype.constructor = Session;
             Session.prototype.connect = function() { if (this._connected) { var error = new Error('The inspector session is already connected'); error.code = 'ERR_INSPECTOR_ALREADY_CONNECTED'; throw error; } this._connected = true; };
             Session.prototype.connectToMainThread = Session.prototype.connect;
             Session.prototype.disconnect = function() { this._connected = false; this.removeAllListeners(); };
             Session.prototype.post = function(method, params, callback) { if (typeof params === 'function') { callback = params; params = {}; } params = params || {}; if (typeof callback !== 'function') callback = function(error) { if (error) throw error; }; var session = this; queueMicrotask(function() { if (!session._connected) { var disconnected = new Error('Session is not connected'); disconnected.code = 'ERR_INSPECTOR_NOT_CONNECTED'; callback(disconnected); return; } var result = {}; try { if (method === 'Runtime.evaluate') { try { var value = (0, eval)(String(params.expression || '')); result.result = remoteObject(value, Boolean(params.returnByValue)); } catch (error) { result.result = remoteObject(error, false); result.exceptionDetails = { text: error.message, exception: remoteObject(error, false), lineNumber: 0, columnNumber: 0 }; } } else if (method === 'Runtime.getIsolateId') result = { id: isolateId }; else if (method === 'Schema.getDomains') result = { domains: ['Runtime','Debugger','Profiler','HeapProfiler','Schema'].map(function(name) { return { name: name, version: '1.3' }; }) }; else if (/^(Runtime|Debugger|Profiler|HeapProfiler)\.(enable|disable)$/.test(String(method))) result = {}; else { var unsupported = new Error('Inspector protocol method is not supported: ' + method); unsupported.code = 'ERR_INSPECTOR_COMMAND'; throw unsupported; } callback(null, result); } catch (error) { callback(error); } }); };
             function open(port, host, wait) { port = port === undefined ? 9229 : Number(port); host = host === undefined ? '127.0.0.1' : String(host); opened = true; inspectorUrl = 'ws://' + host + ':' + port + '/thaw'; return { dispose: close }; }
             function close() { opened = false; inspectorUrl = undefined; }
             function url() { return opened ? inspectorUrl : undefined; }
             function waitForDebugger() { if (!opened) { var error = new Error('Inspector is not active'); error.code = 'ERR_INSPECTOR_NOT_ACTIVE'; throw error; } }
             module.exports = { Session: Session, open: open, close: close, url: url, waitForDebugger: waitForDebugger, console: globalThis.console }; module.exports.default = module.exports; module.exports.__esModule = true;
"#,
            r#"var thawInspectorPost = Session.prototype.post;
             Session.prototype.post = function(method, params, callback) { if (typeof params === 'function') { callback = params; params = {}; } if (method !== 'Network.enable' && method !== 'Network.disable' && method !== 'Schema.getDomains') return thawInspectorPost.call(this, method, params, callback); var session = this; if (typeof callback !== 'function') callback = function(error) { if (error) throw error; }; queueMicrotask(function() { if (!session._connected) { var error = new Error('Session is not connected'); error.code = 'ERR_INSPECTOR_NOT_CONNECTED'; callback(error); } else if (method === 'Schema.getDomains') callback(null, { domains: ['Runtime','Debugger','Profiler','HeapProfiler','Network','Schema'].map(function(name) { return { name: name, version: '1.3' }; }) }); else callback(null, {}); }); };
"#,
        )),
        "inspector/promises" => Some(
            r#"var inspector = require('node:inspector');
             function Session() { inspector.Session.call(this); }
             Session.prototype = Object.create(inspector.Session.prototype); Session.prototype.constructor = Session;
             Session.prototype.post = function(method, params) { var session = this; return new Promise(function(resolve, reject) { inspector.Session.prototype.post.call(session, method, params || {}, function(error, result) { if (error) reject(error); else resolve(result); }); }); };
             module.exports = { Session: Session, open: inspector.open, close: inspector.close, url: inspector.url, waitForDebugger: inspector.waitForDebugger, console: inspector.console }; module.exports.default = module.exports; module.exports.__esModule = true;
"#,
        ),
        "repl" => Some(
            r#"var EventEmitter = require('node:events'), inspect = require('node:util').inspect;
             var REPL_MODE_SLOPPY = Symbol('repl-sloppy'), REPL_MODE_STRICT = Symbol('repl-strict');
             function Recoverable(error) { if (!(this instanceof Recoverable)) return new Recoverable(error); SyntaxError.call(this, error && error.message || String(error)); this.name = 'Recoverable'; this.err = error; this.message = error && error.message || String(error); }
             Recoverable.prototype = Object.create(SyntaxError.prototype); Recoverable.prototype.constructor = Recoverable;
             function writer(value) { return inspect(value); }
             function defaultEval(code, context, filename, callback) { try { var source = String(code), strict = context && context.__thawReplMode === REPL_MODE_STRICT; var result = (0, eval)(strict ? '\"use strict\";\n' + source : source); callback(null, result); } catch (error) { if (error instanceof SyntaxError && /unexpected end|unterminated|expecting/i.test(String(error.message))) callback(new Recoverable(error)); else callback(error); } }
             function writeOutput(output, value) { if (output && typeof output.write === 'function') output.write(String(value)); }
             function REPLServer(options) { if (!(this instanceof REPLServer)) return new REPLServer(options); EventEmitter.call(this); if (typeof options === 'string') options = { prompt: options }; options = options || {}; this.input = options.input || options.stdin; this.output = options.output || options.stdout; this.prompt = options.prompt === undefined ? '> ' : String(options.prompt); this.eval = typeof options.eval === 'function' ? options.eval : defaultEval; this.writer = typeof options.writer === 'function' ? options.writer : writer; this.context = options.useGlobal ? globalThis : Object.create(globalThis); this.context.global = this.context; this.context.globalThis = this.context; this.context.console = globalThis.console; this.context.__thawReplMode = options.replMode || REPL_MODE_SLOPPY; this.commands = Object.create(null); this.lines = []; this.history = []; this.historySize = options.historySize === undefined ? 30 : Math.max(0, Number(options.historySize)); this._bufferedCommand = ''; this.closed = false; this.paused = false; this.last = undefined; this.defineCommand('break', { help: 'Sometimes you get stuck, this gets you out', action: function() { this.clearBufferedCommand(); this.displayPrompt(); } }); this.defineCommand('clear', { help: 'Alias for .break', action: function() { this.clearBufferedCommand(); this.displayPrompt(); } }); this.defineCommand('exit', { help: 'Exit the REPL', action: function() { this.close(); } }); this.defineCommand('help', { help: 'Print this help message', action: function() { var self = this; Object.keys(this.commands).sort().forEach(function(name) { writeOutput(self.output, '.' + name + '\t' + self.commands[name].help + '\n'); }); this.displayPrompt(); } }); }
             REPLServer.prototype = Object.create(EventEmitter.prototype); REPLServer.prototype.constructor = REPLServer;
             REPLServer.prototype.setPrompt = function(prompt) { this.prompt = String(prompt); };
             REPLServer.prototype.displayPrompt = function(preserveCursor) { if (!this.closed) writeOutput(this.output, this.prompt); return this; };
             REPLServer.prototype.clearBufferedCommand = function() { this._bufferedCommand = ''; };
             REPLServer.prototype.defineCommand = function(keyword, command) { keyword = String(keyword).replace(/^\./, ''); if (!keyword) throw new TypeError('keyword must not be empty'); if (typeof command === 'function') command = { action: command }; if (!command || typeof command.action !== 'function') throw new TypeError('command action must be a function'); this.commands[keyword] = { help: String(command.help || ''), action: command.action }; };
             REPLServer.prototype.setupHistory = function(path, callback) { this.historyPath = String(path); if (typeof callback === 'function') queueMicrotask(function() { callback(null); }); };
             REPLServer.prototype.pause = function() { this.paused = true; if (this.input && this.input.pause) this.input.pause(); return this; };
             REPLServer.prototype.resume = function() { this.paused = false; if (this.input && this.input.resume) this.input.resume(); return this; };
             REPLServer.prototype.close = function() { if (this.closed) return; this.closed = true; this.emit('exit'); this.emit('close'); };
             REPLServer.prototype.write = function(command) { if (this.closed) return false; var line = String(command), trimmed = line.trim(), self = this; this.lines.push(line); if (trimmed.charAt(0) === '.') { var space = trimmed.indexOf(' '), name = trimmed.slice(1, space < 0 ? undefined : space), value = space < 0 ? '' : trimmed.slice(space + 1), entry = this.commands[name]; if (!entry) { writeOutput(this.output, 'Invalid REPL keyword\n'); this.displayPrompt(); return true; } entry.action.call(this, value); return true; } if (trimmed) { this.history.unshift(line); if (this.history.length > this.historySize) this.history.length = this.historySize; } var source = this._bufferedCommand + line; this.eval(source, this.context, 'repl', function(error, result) { if (error instanceof Recoverable) { self._bufferedCommand = source + '\n'; self.displayPrompt(); return; } self._bufferedCommand = ''; if (error) { self.emit('error', error); writeOutput(self.output, String(error) + '\n'); } else { self.last = result; self.context._ = result; writeOutput(self.output, self.writer(result) + '\n'); self.emit('result', result); } self.displayPrompt(); }); return true; };
             function start(options) { var server = new REPLServer(options); server.displayPrompt(); return server; }
             module.exports = { start: start, REPLServer: REPLServer, Recoverable: Recoverable, REPL_MODE_SLOPPY: REPL_MODE_SLOPPY, REPL_MODE_STRICT: REPL_MODE_STRICT, writer: writer, _builtinLibs: [] }; module.exports.default = module.exports; module.exports.__esModule = true;
"#,
        ),
        "cluster" => Some(concat!(
            r#"var EventEmitter = require('node:events'), processObject = require('node:process'), cluster = new EventEmitter();
             var nextWorkerId = 1, SCHED_NONE = 1, SCHED_RR = 2, schedulingPolicy = SCHED_RR, workers = Object.create(null), settings = {}, isPrimary = processObject.env.NODE_UNIQUE_ID === undefined;
             function Worker(options) { if (!(this instanceof Worker)) return new Worker(options); EventEmitter.call(this); options = options || {}; this.id = options.id === undefined ? nextWorkerId++ : Number(options.id); this.process = options.process || { pid: Number(processObject.pid || 0) + this.id, connected: true, killed: false, kill: function() { this.killed = true; this.connected = false; return true; } }; this.exitedAfterDisconnect = undefined; this.state = 'none'; }
             Worker.prototype = Object.create(EventEmitter.prototype); Worker.prototype.constructor = Worker;
             Worker.prototype.isConnected = function() { return Boolean(this.process && this.process.connected) && this.state !== 'disconnected' && this.state !== 'dead'; };
             Worker.prototype.isDead = function() { return this.state === 'dead' || Boolean(this.process && this.process.killed); };
             Worker.prototype.send = function(message, sendHandle, options, callback) { if (typeof sendHandle === 'function') callback = sendHandle; else if (typeof options === 'function') callback = options; if (!this.isConnected()) { var error = new Error('Channel closed'); error.code = 'ERR_IPC_CHANNEL_CLOSED'; if (typeof callback === 'function') queueMicrotask(function() { callback(error); }); return false; } var worker = this; queueMicrotask(function() { worker.emit('message', message, sendHandle); cluster.emit('message', worker, message, sendHandle); if (typeof callback === 'function') callback(null); }); return true; };
             Worker.prototype.disconnect = function() { if (!this.isConnected()) return this; this.exitedAfterDisconnect = true; this.state = 'disconnected'; if (this.process) this.process.connected = false; var worker = this; queueMicrotask(function() { worker.emit('disconnect'); cluster.emit('disconnect', worker); }); return this; };
             Worker.prototype.kill = Worker.prototype.destroy = function(signal) { if (this.isDead()) return this; var worker = this; this.exitedAfterDisconnect = this.exitedAfterDisconnect === true; this.state = 'dead'; if (this.process) { this.process.connected = false; this.process.killed = true; } delete workers[this.id]; queueMicrotask(function() { worker.emit('exit', 0, signal || 'SIGTERM'); cluster.emit('exit', worker, 0, signal || 'SIGTERM'); }); return this; };
             function setupPrimary(options) { if (!isPrimary) return settings; options = options || {}; settings = Object.assign({}, settings, options); cluster.settings = settings; queueMicrotask(function() { cluster.emit('setup', settings); }); return settings; }
             function fork(environment) { if (!isPrimary) { var error = new Error('cluster.fork() may only be called from a primary process'); error.code = 'ERR_CLUSTER_ONLY_PRIMARY'; throw error; } var worker = new Worker(); worker.state = 'online'; worker.environment = Object.assign({}, processObject.env, environment || {}, { NODE_UNIQUE_ID: String(worker.id) }); workers[worker.id] = worker; queueMicrotask(function() { cluster.emit('fork', worker); worker.emit('online'); cluster.emit('online', worker); }); return worker; }
             function disconnect(callback) { var active = Object.keys(workers).map(function(id) { return workers[id]; }); if (!active.length) { if (typeof callback === 'function') queueMicrotask(callback); return; } var remaining = active.length; active.forEach(function(worker) { worker.once('disconnect', function() { if (--remaining === 0 && typeof callback === 'function') queueMicrotask(callback); }); worker.disconnect(); }); }
             Object.assign(cluster, { Worker: Worker, workers: workers, settings: settings, isPrimary: isPrimary, isMaster: isPrimary, isWorker: !isPrimary, worker: isPrimary ? undefined : new Worker({ id: Number(processObject.env.NODE_UNIQUE_ID) }), SCHED_NONE: SCHED_NONE, SCHED_RR: SCHED_RR, setupPrimary: setupPrimary, setupMaster: setupPrimary, fork: fork, disconnect: disconnect });
             if (!isPrimary) { processObject.connected = true; processObject.disconnect = function() { if (!processObject.connected) return; processObject.connected = false; cluster.worker.disconnect(); processObject.emit('disconnect'); }; }
             Object.defineProperty(cluster, 'schedulingPolicy', { enumerable: true, get: function() { return schedulingPolicy; }, set: function(value) { value = Number(value); if (value !== SCHED_NONE && value !== SCHED_RR) throw new RangeError('invalid scheduling policy'); schedulingPolicy = value; } });
             module.exports = cluster; module.exports.default = cluster; module.exports.__esModule = true;
"#,
            r#"var thawSimulatedClusterFork = fork, thawClusterChildProcess = require('node:child_process');
             fork = function(environment) { if (settings.exec !== undefined || !processObject.execPath) return thawSimulatedClusterFork(environment); if (!isPrimary) { var primaryError = new Error('cluster.fork() may only be called from a primary process'); primaryError.code = 'ERR_CLUSTER_ONLY_PRIMARY'; throw primaryError; } var worker = new Worker(), childEnvironment = Object.assign({}, processObject.env, environment || {}, { NODE_UNIQUE_ID: String(worker.id) }), child = thawClusterChildProcess.spawn(processObject.execPath, processObject.argv.slice(2), { env: childEnvironment, stdio: 'inherit' }); worker.process = child; worker.environment = childEnvironment; worker.state = 'online'; child.connected = true; workers[worker.id] = worker; queueMicrotask(function() { cluster.emit('fork', worker); }); child.on('spawn', function() { worker.emit('online'); cluster.emit('online', worker); }); child.on('exit', function(code, signal) { worker.state = 'dead'; child.connected = false; delete workers[worker.id]; worker.emit('exit', code, signal); cluster.emit('exit', worker, code, signal); }); return worker; }; cluster.fork = fork;
"#,
        )),
        _ => None,
    }
}
