pub(super) fn source(name: &str) -> Option<&'static str> {
    match name {
        "test" => Some(
            r#"var EventEmitter = require('node:events'), assertion = require('node:assert'), root = { name: '', parent: null, tests: [], before: [], after: [], beforeEach: [], afterEach: [] }, declaring = root, chain = Promise.resolve(), history = [], resultBus = new EventEmitter(), sequence = 1;
             function MockTracker() { this._restores = []; this.timers = { enabled: false, enable: function() { this.enabled = true; }, reset: function() { this.enabled = false; }, tick: function(milliseconds) { return new Promise(function(resolve) { setTimeout(resolve, Number(milliseconds) || 0); }); }, runAll: function() { return Promise.resolve(); } }; }
             MockTracker.prototype.fn = function(implementation, options) { implementation = typeof implementation === 'function' ? implementation : function() {}; options = options || {}; var calls = [], once = [], limit = options.times === undefined ? Infinity : Number(options.times), wrapper = function() { var record = { arguments: Array.prototype.slice.call(arguments), this: this, target: new.target }, selected = once.length ? once.shift() : implementation; calls.push(record); try { record.result = selected.apply(this, arguments); return record.result; } catch (error) { record.error = error; throw error; } }; Object.defineProperty(wrapper, 'mock', { value: { calls: calls, callCount: function() { return calls.length; }, resetCalls: function() { calls.length = 0; }, mockImplementation: function(value) { implementation = value; return wrapper; }, mockImplementationOnce: function(value) { once.push(value); return wrapper; }, restore: function() {} } }); if (Number.isFinite(limit)) { var original = wrapper; wrapper = function() { if (calls.length >= limit) throw new Error('mock function call limit exceeded'); return original.apply(this, arguments); }; Object.defineProperty(wrapper, 'mock', { value: original.mock }); } return wrapper; };
             MockTracker.prototype.method = function(object, name, implementation) { if (!object) throw new TypeError('object is required'); var descriptor = Object.getOwnPropertyDescriptor(object, name), original = object[name], replacement = this.fn(implementation || original); object[name] = replacement; var restore = function() { if (descriptor) Object.defineProperty(object, name, descriptor); else delete object[name]; }; replacement.mock.restore = restore; this._restores.push(restore); return replacement; }; MockTracker.prototype.getter = function(object, name, implementation) { var descriptor = Object.getOwnPropertyDescriptor(object, name); Object.defineProperty(object, name, { configurable: true, enumerable: descriptor ? descriptor.enumerable : true, get: this.fn(implementation) }); var restore = function() { if (descriptor) Object.defineProperty(object, name, descriptor); else delete object[name]; }; this._restores.push(restore); }; MockTracker.prototype.setter = function(object, name, implementation) { var descriptor = Object.getOwnPropertyDescriptor(object, name); Object.defineProperty(object, name, { configurable: true, enumerable: descriptor ? descriptor.enumerable : true, set: this.fn(implementation) }); var restore = function() { if (descriptor) Object.defineProperty(object, name, descriptor); else delete object[name]; }; this._restores.push(restore); }; MockTracker.prototype.reset = function() { this.restoreAll(); }; MockTracker.prototype.restoreAll = function() { this._restores.splice(0).reverse().forEach(function(restore) { restore(); }); };
             var mock = new MockTracker();
             function TestContext(record) { this.name = record.name; this.fullName = record.fullName; this.signal = new AbortController().signal; this.mock = new MockTracker(); this.assert = assertion; this._diagnostics = []; this._plan = null; this._assertions = 0; this._record = record; }
             TestContext.prototype.diagnostic = function(message) { this._diagnostics.push(String(message)); }; TestContext.prototype.plan = function(count) { this._plan = Number(count); }; TestContext.prototype.skip = function(message) { var error = new Error(message || 'test skipped'); error.__testSkip = true; throw error; }; TestContext.prototype.todo = function(message) { var error = new Error(message || 'test todo'); error.__testTodo = true; throw error; }; TestContext.prototype.test = function(name, options, fn) { return runCase(normalizeTest(name, options, fn, this._record.suite), this._record.suite); }; TestContext.prototype.before = function(fn) { this._record.localBefore.push(fn); }; TestContext.prototype.after = function(fn) { this._record.localAfter.push(fn); }; TestContext.prototype.beforeEach = function(fn) { this._record.localBeforeEach.push(fn); }; TestContext.prototype.afterEach = function(fn) { this._record.localAfterEach.push(fn); };
             function normalizeTest(name, options, fn, suite) { if (typeof name === 'function') { fn = name; name = fn.name || '<anonymous>'; options = {}; } else if (typeof options === 'function') { fn = options; options = {}; } options = options || {}; return { id: sequence++, name: String(name), fullName: (suite && suite.name ? suite.name + ' > ' : '') + String(name), options: options, fn: fn || function() {}, suite: suite || root, localBefore: [], localAfter: [], localBeforeEach: [], localAfterEach: [] }; }
             function ancestors(suite) { var values = []; while (suite) { values.unshift(suite); suite = suite.parent; } return values; }
             async function invokeAll(functions, context) { for (var fn of functions) await fn(context); }
             function publish(result) { history.push(result); resultBus.emit('result', result); resultBus.emit('test:' + result.status, result); }
             async function runCase(record) { var start = Date.now(), context = new TestContext(record), suites = ancestors(record.suite), result = { type: 'test', name: record.name, fullName: record.fullName, nesting: Math.max(0, suites.length - 1), status: 'passed', duration_ms: 0, diagnostics: context._diagnostics }; if (record.options.skip) { result.status = 'skipped'; result.message = typeof record.options.skip === 'string' ? record.options.skip : undefined; publish(result); return result; } if (record.options.todo) { result.status = 'todo'; result.message = typeof record.options.todo === 'string' ? record.options.todo : undefined; publish(result); return result; } try { await invokeAll(suites.flatMap(function(suite) { return suite.beforeEach; }).concat(record.localBefore, record.localBeforeEach), context); await record.fn(context); if (context._plan !== null && context._plan !== context._assertions) throw new Error('plan expected ' + context._plan + ' assertions but saw ' + context._assertions); } catch (error) { if (error && error.__testSkip) { result.status = 'skipped'; result.message = error.message; } else if (error && error.__testTodo) { result.status = 'todo'; result.message = error.message; } else { result.status = 'failed'; result.error = error; result.message = error && error.message || String(error); } } finally { try { await invokeAll(record.localAfterEach.concat(record.localAfter).concat(suites.slice().reverse().flatMap(function(suite) { return suite.afterEach; })), context); } catch (error) { result.status = 'failed'; result.error = error; result.message = error.message; } context.mock.restoreAll(); result.duration_ms = Date.now() - start; publish(result); } return result; }
             function enqueue(operation) { var promise = chain.then(operation); chain = promise.catch(function() {}); return promise; }
             function test(name, options, fn) { var record = normalizeTest(name, options, fn, declaring); if (declaring !== root) { declaring.tests.push({ test: record }); return Promise.resolve(record); } return enqueue(function() { return runCase(record); }); }
             function describe(name, options, fn) { if (typeof options === 'function') { fn = options; options = {}; } options = options || {}; var suite = { name: String(name), parent: declaring, tests: [], before: [], after: [], beforeEach: [], afterEach: [], options: options }, previous = declaring; declaring = suite; try { fn(); } finally { declaring = previous; } if (previous !== root) { previous.tests.push({ suite: suite }); return Promise.resolve(suite); } return enqueue(function() { return runSuite(suite); }); }
             async function runSuite(suite) { var context = { name: suite.name, signal: new AbortController().signal }; if (suite.options.skip) { var skipped = { type: 'suite', name: suite.name, status: 'skipped', duration_ms: 0 }; publish(skipped); return skipped; } var start = Date.now(), status = 'passed', error; try { await invokeAll(suite.before, context); for (var item of suite.tests) { var result = item.test ? await runCase(item.test) : await runSuite(item.suite); if (result.status === 'failed') status = 'failed'; } } catch (failure) { status = 'failed'; error = failure; } finally { try { await invokeAll(suite.after, context); } catch (failure) { status = 'failed'; error = failure; } } var result = { type: 'suite', name: suite.name, status: status, duration_ms: Date.now() - start, error: error }; publish(result); return result; }
             function hook(kind, fn) { declaring[kind].push(fn); } function before(fn) { hook('before', fn); } function after(fn) { hook('after', fn); } function beforeEach(fn) { hook('beforeEach', fn); } function afterEach(fn) { hook('afterEach', fn); }
             function TestsStream() { EventEmitter.call(this); this._queue = history.slice(); this._waiters = []; this._closed = false; var self = this; this._listener = function(result) { if (self._waiters.length) self._waiters.shift()({ value: result, done: false }); else self._queue.push(result); self.emit('data', result); }; resultBus.on('result', this._listener); } TestsStream.prototype = Object.create(EventEmitter.prototype); TestsStream.prototype.constructor = TestsStream; TestsStream.prototype[Symbol.asyncIterator] = function() { return this; }; TestsStream.prototype.next = function() { if (this._queue.length) return Promise.resolve({ value: this._queue.shift(), done: false }); if (this._closed) return Promise.resolve({ done: true }); var self = this; return new Promise(function(resolve) { self._waiters.push(resolve); }); }; TestsStream.prototype.close = function() { if (this._closed) return; this._closed = true; resultBus.off('result', this._listener); while (this._waiters.length) this._waiters.shift()({ done: true }); this.emit('end'); };
             function run(options) { var stream = new TestsStream(); chain.finally(function() { queueMicrotask(function() { stream.close(); }); }); return stream; }
             test.skip = function(name, options, fn) { if (typeof options === 'function') { fn = options; options = {}; } return test(name, Object.assign({}, options || {}, { skip: true }), fn); }; test.todo = function(name, options, fn) { if (typeof options === 'function') { fn = options; options = {}; } return test(name, Object.assign({}, options || {}, { todo: true }), fn); }; test.only = test; describe.skip = function(name, options, fn) { if (typeof options === 'function') { fn = options; options = {}; } return describe(name, Object.assign({}, options || {}, { skip: true }), fn); }; describe.only = describe;
             Object.assign(test, { test: test, it: test, describe: describe, suite: describe, before: before, after: after, beforeEach: beforeEach, afterEach: afterEach, run: run, mock: mock, assert: assertion, skip: test.skip, todo: test.todo, only: test.only, snapshot: { setDefaultSnapshotSerializers: function() {} } }); module.exports = test; module.exports.default = test; module.exports.__esModule = true;
"#,
        ),
        "test/reporters" => Some(
            r#"async function* records(source) { for await (var event of source) yield event; }
             async function* dot(source) { for await (var event of records(source)) if (event.type === 'test') yield event.status === 'passed' ? '.' : event.status === 'failed' ? 'X' : '-'; }
             async function* spec(source) { for await (var event of records(source)) yield (event.status === 'passed' ? '✔ ' : event.status === 'failed' ? '✖ ' : '- ') + event.fullName + '\n'; }
             async function* tap(source) { var index = 0; yield 'TAP version 13\n'; for await (var event of records(source)) if (event.type === 'test') yield (++index) + (event.status === 'passed' ? ' ok ' : ' not ok ') + '- ' + event.fullName + '\n'; yield '1..' + index + '\n'; }
             async function* junit(source) { yield '<testsuite>'; for await (var event of records(source)) if (event.type === 'test') yield '<testcase name="' + String(event.fullName).replace(/&/g, '&amp;').replace(/"/g, '&quot;') + '">' + (event.status === 'failed' ? '<failure>' + String(event.message || '') + '</failure>' : '') + '</testcase>'; yield '</testsuite>'; }
             async function* lcov(source) { for await (var event of records(source)) if (event.coverage) yield String(event.coverage); }
             module.exports = { dot: dot, spec: spec, tap: tap, junit: junit, lcov: lcov }; module.exports.default = module.exports; module.exports.__esModule = true;
"#,
        ),
        "wasi" => Some(
            r#"function validateOptions(options) {
               options = options || {};
               if (options.version !== undefined && options.version !== 'preview1') { var error = new TypeError('The "version" option must be "preview1"'); error.code = 'ERR_INVALID_ARG_VALUE'; throw error; }
               var args = options.args === undefined ? [] : options.args;
               if (!Array.isArray(args) || args.some(function(value) { return typeof value !== 'string'; })) { var argsError = new TypeError('The "args" option must be an array of strings'); argsError.code = 'ERR_INVALID_ARG_TYPE'; throw argsError; }
               var env = options.env === undefined ? {} : options.env, preopens = options.preopens === undefined ? {} : options.preopens;
               if (!env || typeof env !== 'object' || Array.isArray(env) || Object.keys(env).some(function(key) { return typeof env[key] !== 'string'; })) { var envError = new TypeError('The "env" option must be an object of strings'); envError.code = 'ERR_INVALID_ARG_TYPE'; throw envError; }
               if (!preopens || typeof preopens !== 'object' || Array.isArray(preopens) || Object.keys(preopens).some(function(key) { return typeof preopens[key] !== 'string'; })) { var preopenError = new TypeError('The "preopens" option must be an object of strings'); preopenError.code = 'ERR_INVALID_ARG_TYPE'; throw preopenError; }
               return { args: args.slice(), env: Object.assign({}, env), preopens: Object.assign({}, preopens), returnOnExit: Boolean(options.returnOnExit), version: 'preview1' };
             }
             function WASI(options) { if (!(this instanceof WASI)) throw new TypeError("Class constructor WASI cannot be invoked without 'new'"); this._options = validateOptions(options); this._started = false; this._import = Object.freeze({ __thawWasiOptions: JSON.stringify(this._options) }); }
             WASI.prototype.getImportObject = function() { return { wasi_snapshot_preview1: this._import }; };
             Object.defineProperty(WASI.prototype, 'wasiImport', { enumerable: true, get: function() { return this._import; } });
             WASI.prototype._invoke = function(instance, name) { if (!(instance instanceof WebAssembly.Instance)) { var typeError = new TypeError('instance must be a WebAssembly.Instance'); typeError.code = 'ERR_INVALID_ARG_TYPE'; throw typeError; } if (this._started) { var stateError = new Error('WASI instance has already started'); stateError.code = 'ERR_WASI_ALREADY_STARTED'; throw stateError; } if (!(instance.exports.memory instanceof WebAssembly.Memory)) { var memoryError = new Error('WASI instance must export a memory'); memoryError.code = 'ERR_WASI_NOT_STARTED'; throw memoryError; } if (typeof instance.exports[name] !== 'function') { var exportError = new Error('WASI instance does not export ' + name); exportError.code = 'ERR_WASI_NOT_STARTED'; throw exportError; } this._started = true; try { instance.exports[name](); return 0; } catch (error) { if (error && error.__thawWasiExit !== undefined) { var code = Number(error.__thawWasiExit); if (!this._options.returnOnExit) process.exitCode = code; return code; } throw error; } };
             WASI.prototype.start = function(instance) { var code = this._invoke(instance, '_start'); return this._options.returnOnExit ? code : undefined; };
             WASI.prototype.initialize = function(instance) { if (instance && instance.exports && typeof instance.exports._start === 'function') { var error = new Error('WASI reactor must not export _start'); error.code = 'ERR_INVALID_ARG_VALUE'; throw error; } this._invoke(instance, '_initialize'); };
             module.exports = { WASI: WASI }; module.exports.default = module.exports; module.exports.__esModule = true;
"#,
        ),
        _ => None,
    }
}
