#[repr(C)]
pub struct ThawJitResult {
    pub value: f64,
    pub error: *const c_char,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
enum NumericOp {
    Add,
    Subtract,
    Multiply,
    Divide,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
#[repr(u8)]
enum CompareOp {
    Less,
    LessEqual,
    Greater,
    GreaterEqual,
    Equal,
    NotEqual,
}

impl CompareOp {
    fn parse(operation: &str) -> Option<Self> {
        match operation {
            "lt" => Some(Self::Less),
            "lte" => Some(Self::LessEqual),
            "gt" => Some(Self::Greater),
            "gte" => Some(Self::GreaterEqual),
            "eq" => Some(Self::Equal),
            "ne" => Some(Self::NotEqual),
            _ => None,
        }
    }
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
#[repr(u8)]
enum UnaryMath {
    Acos,
    Acosh,
    Asin,
    Asinh,
    Atan,
    Atanh,
    Cbrt,
    Ceil,
    Clz32,
    Cos,
    Cosh,
    Exp,
    Expm1,
    Floor,
    Fround,
    Log,
    Log1p,
    Log2,
    Log10,
    Round,
    Sign,
    Sin,
    Sinh,
    SquareRoot,
    Tan,
    Tanh,
    Truncate,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
enum BitwiseOp {
    And,
    Or,
    ShiftLeft,
    ShiftRight,
    ShiftRightUnsigned,
    Xor,
}

impl BitwiseOp {
    #[cfg(all(target_arch = "x86_64", target_family = "unix"))]
    fn function(self) -> extern "C" fn(f64, f64) -> f64 {
        match self {
            Self::And => bit_and,
            Self::Or => bit_or,
            Self::ShiftLeft => shift_left,
            Self::ShiftRight => shift_right,
            Self::ShiftRightUnsigned => shift_right_unsigned,
            Self::Xor => bit_xor,
        }
    }
}

impl UnaryMath {
    fn parse(operation: &str) -> Option<Self> {
        match operation {
            "acos" => Some(Self::Acos),
            "acosh" => Some(Self::Acosh),
            "asin" => Some(Self::Asin),
            "asinh" => Some(Self::Asinh),
            "atan" => Some(Self::Atan),
            "atanh" => Some(Self::Atanh),
            "cbrt" => Some(Self::Cbrt),
            "ceil" => Some(Self::Ceil),
            "clz32" => Some(Self::Clz32),
            "cos" => Some(Self::Cos),
            "cosh" => Some(Self::Cosh),
            "exp" => Some(Self::Exp),
            "expm1" => Some(Self::Expm1),
            "floor" => Some(Self::Floor),
            "fround" => Some(Self::Fround),
            "log" => Some(Self::Log),
            "log1p" => Some(Self::Log1p),
            "log2" => Some(Self::Log2),
            "log10" => Some(Self::Log10),
            "round" => Some(Self::Round),
            "sign" => Some(Self::Sign),
            "sin" => Some(Self::Sin),
            "sinh" => Some(Self::Sinh),
            "sqrt" => Some(Self::SquareRoot),
            "tan" => Some(Self::Tan),
            "tanh" => Some(Self::Tanh),
            "trunc" => Some(Self::Truncate),
            _ => None,
        }
    }

    #[cfg(all(target_arch = "x86_64", target_family = "unix"))]
    fn function(self) -> extern "C" fn(f64) -> f64 {
        match self {
            Self::Acos => acos_number,
            Self::Acosh => acosh_number,
            Self::Asin => asin_number,
            Self::Asinh => asinh_number,
            Self::Atan => atan_number,
            Self::Atanh => atanh_number,
            Self::Cbrt => cbrt_number,
            Self::Ceil => ceil_number,
            Self::Clz32 => clz32_number,
            Self::Cos => cos_number,
            Self::Cosh => cosh_number,
            Self::Exp => exp_number,
            Self::Expm1 => expm1_number,
            Self::Floor => floor_number,
            Self::Fround => fround_number,
            Self::Log => log_number,
            Self::Log1p => log1p_number,
            Self::Log2 => log2_number,
            Self::Log10 => log10_number,
            Self::Round => round_number,
            Self::Sign => sign_number,
            Self::Sin => sin_number,
            Self::Sinh => sinh_number,
            Self::SquareRoot => unreachable!("square root emits SSE2 directly"),
            Self::Tan => tan_number,
            Self::Tanh => tanh_number,
            Self::Truncate => truncate_number,
        }
    }
}

impl NumericOp {
    fn parse(operation: &str) -> Option<Self> {
        match operation {
            "add" => Some(Self::Add),
            "sub" => Some(Self::Subtract),
            "mul" => Some(Self::Multiply),
            "div" => Some(Self::Divide),
            _ => None,
        }
    }

    #[cfg(all(target_arch = "x86_64", target_family = "unix"))]
    fn opcode(self) -> u8 {
        match self {
            Self::Add => 0x58,
            Self::Subtract => 0x5c,
            Self::Multiply => 0x59,
            Self::Divide => 0x5e,
        }
    }
}

#[derive(Clone, Copy, Debug, PartialEq)]
enum NumericReduceOp {
    Add,
    Subtract,
    Multiply,
    Divide,
    Remainder,
    Power,
    Minimum,
    Maximum,
}

impl NumericReduceOp {
    fn parse(operation: &str) -> Option<Self> {
        match operation {
            "add" => Some(Self::Add),
            "sub" => Some(Self::Subtract),
            "mul" => Some(Self::Multiply),
            "div" => Some(Self::Divide),
            "rem" => Some(Self::Remainder),
            "pow" => Some(Self::Power),
            "min" => Some(Self::Minimum),
            "max" => Some(Self::Maximum),
            _ => None,
        }
    }
}

#[derive(Clone, Copy, Debug, PartialEq)]
enum NumericValue {
    Argument(u8),
    DynamicArgument(u8),
    Constant(f64),
    Operation(NumericOp),
    Compare(CompareOp),
    Bitwise(BitwiseOp),
    BitNot,
    Absolute,
    Negate,
    Maximum,
    Minimum,
    Atan2,
    Hypot,
    Imul,
    IsFinite,
    IsInteger,
    IsNaN,
    IsSafeInteger,
    NumberSameValue,
    StringSameValue,
    ReferenceSameValue,
    TypeOfNumber,
    TypeOfBoolean,
    TypeOfString,
    TypeOfObject,
    TypeOfDynamic,
    DynamicToBoolean,
    StringCompare,
    StringCharAt,
    StringCharCodeAt,
    StringAt,
    StringCodePointAt,
    StringConcat,
    NumberToString,
    BooleanToString,
    StringToNumber,
    DynamicToString,
    DynamicToNumber,
    DynamicAdd,
    DynamicCompare(u8),
    TagNumber,
    TagString,
    TagBoolean,
    TagAggregate(u8),
    DynamicTag,
    UntagNumber,
    UntagString,
    UntagBoolean,
    UntagNumberArray,
    UntagBooleanArray,
    UntagStringArray,
    UntagArray,
    UntagNumberDictionary,
    UntagBooleanDictionary,
    UntagStringDictionary,
    UntagDictionary,
    UntagObject,
    UntagTuple,
    ObjectField(u8, u16),
    OptionalObjectField(u8, u16),
    OptionalTupleField(u8, u16),
    NullishObjectField(u8, u16),
    NullishTupleField(u8, u16),
    FixedObjectNew(u16),
    FixedObjectSet(u8, u16),
    TaggedObjectNumberUpdate(u8, u16),
    TaggedObjectNumberAssign(u8, u16),
    FixedTupleNew(u16),
    FixedTupleSet(u8, u16),
    FixedWideTupleNew(u16),
    FixedWideTupleSet(u8, u16, u8),
    ExcludeNumber,
    ExcludeString,
    ExcludeBoolean,
    ExcludeArray,
    ExcludeObject,
    GlobalGet,
    GlobalInit,
    GlobalSet,
    CallableEntryGet,
    CallableEntrySet,
    ParseFloat,
    ParseInt,
    NumberToFixed,
    NumberToPrecision,
    NumberToRadixString,
    NumberToExponential,
    NumberToExponentialShortest,
    StringConstant(*const c_char),
    StringEndsWith,
    StringEndsWithAt,
    StringIncludes,
    StringIncludesAt,
    StringIsWellFormed,
    StringIndexOf,
    StringIndexOfAt,
    StringLastIndexOf,
    StringLastIndexOfAt,
    StringLength,
    ArrayLength,
    DynamicArrayLength,
    IsArray,
    IsNotArray,
    DynamicIsArray,
    NumberArrayAt,
    BoolArrayAt,
    StringArrayAt,
    DynamicArrayAt,
    NumberArrayGet,
    BoolArrayGet,
    StringArrayGet,
    NumberDictionaryGet,
    BoolDictionaryGet,
    StringDictionaryGet,
    NumberDictionarySet,
    NumberDictionaryPostSet,
    StringDictionarySet,
    BoolDictionarySet,
    DictionaryDelete,
    DictionaryHasOwn,
    DictionaryIn,
    DictionaryKeys,
    NumberDictionaryValues,
    BoolDictionaryValues,
    StringDictionaryValues,
    NumberDictionaryEntries,
    BoolDictionaryEntries,
    StringDictionaryEntries,
    DictionaryFromNumberEntries,
    DictionaryFromBoolEntries,
    DictionaryFromStringEntries,
    DictionaryAssign,
    DictionaryLength,
    DictionaryKeyAt,
    EmptyDictionary,
    DictionaryAppend(u8),
    DictionaryStaticAppend(u8, *const c_char),
    NumberArrayIncludes,
    BoolArrayIncludes,
    StringArrayIncludes,
    DynamicArrayIncludes,
    NumberArrayIndexOf,
    BoolArrayIndexOf,
    StringArrayIndexOf,
    DynamicArrayIndexOf,
    NumberArrayLastIndexOf,
    BoolArrayLastIndexOf,
    StringArrayLastIndexOf,
    DynamicArrayLastIndexOf,
    NumberArrayJoin,
    BoolArrayJoin,
    StringArrayJoin,
    DynamicArrayJoin,
    DynamicArraySlice,
    ArraySlice,
    DynamicArrayConcat,
    ArrayConcat,
    NumberArrayAppend,
    StringArrayAppend,
    BoolArrayAppend,
    DynamicArrayAppend,
    ArrayToReversed,
    ArrayReverse,
    DynamicArrayToReversed,
    DynamicArrayReverse,
    NumberArrayToSorted,
    StringArrayToSorted,
    BoolArrayToSorted,
    DynamicArrayToSorted,
    NumberArraySort,
    NumberArrayToSortedBy(bool),
    NumberArraySortBy(bool),
    StringArrayToSortedDescending,
    StringArraySortDescending,
    StringArraySort,
    BoolArraySort,
    DynamicArraySort,
    NumberArrayFill,
    StringArrayFill,
    BoolArrayFill,
    DynamicArrayFill,
    ArrayCopyWithin,
    DynamicArrayCopyWithin,
    DynamicArrayWith,
    NumberArrayPush,
    StringArrayPush,
    BoolArrayPush,
    DynamicArrayPush,
    NumberArrayUnshift,
    StringArrayUnshift,
    BoolArrayUnshift,
    DynamicArrayUnshift,
    NumberArraySet,
    NumberArrayPostSet,
    StringArraySet,
    BoolArraySet,
    DynamicArraySet,
    AggregateLocalSet(u8, u8),
    AggregateLocalArrayInsert(u8, u8, bool),
    ArrayValue,
    MutableArrayHandle,
    EmptyArray,
    NumberArrayMin,
    NumberArrayMax,
    NumberArrayHypot,
    NumberArrayReduce(NumericReduceOp, bool, bool),
    NumberArrayJitReduce(bool, bool, bool),
    NumberArrayQuantifier(CompareOp, bool),
    NumberArrayFind(CompareOp, u8),
    NumberArrayFilter(CompareOp),
    PrimitiveArrayTruthy(u8, u8),
    DynamicArrayTruthy(u8),
    PrimitiveArrayCompare(u8, CompareOp, u8),
    DynamicArrayCompare(u8, u8),
    PrimitiveArrayMap(u8, u8),
    PrimitiveArrayConvert(u8, u8),
    DynamicArrayConvert(u8),
    DynamicArrayMapIdentity,
    DynamicArrayJitMap(u8, bool),
    DynamicArrayJitScan(u8, bool),
    DynamicArrayJitReduce(bool, bool, bool),
    NumberArrayMap(NumericReduceOp, bool),
    PrimitiveArrayJitMap(u8, u8, bool),
    PrimitiveArrayJitScan(u8, u8, bool),
    NumberArrayIndexMap(NumericReduceOp, bool),
    NumberArraySelectMap(CompareOp, u8),
    NumberArrayBranchMap(u16),
    NumberArrayUnaryMap(bool),
    NumberArrayMathMap(UnaryMath),
    NumberArrayPop,
    StringArrayPop,
    BoolArrayPop,
    DynamicArrayPop,
    NumberArrayShift,
    StringArrayShift,
    BoolArrayShift,
    DynamicArrayShift,
    ArraySplice,
    ArrayToSpliced,
    DynamicArraySplice,
    DynamicArrayToSpliced,
    NumberArrayWith,
    StringArrayWith,
    BoolArrayWith,
    StringTruthy,
    StringPadEnd,
    StringPadStart,
    StringStartsWith,
    StringStartsWithAt,
    StringRepeat,
    StringNormalize,
    StringSplit,
    StringToArray,
    StringFromCharCode,
    StringFromCodePoint,
    StringReplace,
    StringReplaceAll,
    StringSlice,
    StringSliceRange,
    StringSubstring,
    StringSubstringRange,
    StringToLowerCase,
    StringToWellFormed,
    StringToUpperCase,
    StringTrim,
    StringTrimEnd,
    StringTrimStart,
    Power,
    UnaryMath(UnaryMath),
    Remainder,
    Select,
    ShortCircuit(bool),
    ConditionalStart,
    PresentConditionalStart,
    ConditionalAlternate,
    ShortCircuitEnd,
    Absent,
    Null,
    PreserveAbsent,
    AsBoolean,
    BooleanNot,
    StrictMismatch(bool),
    Drop,
    DropUnder,
    Duplicate,
    DuplicatePair,
    LocalGet(u8),
    LocalSet(u8),
    LoopStart,
    LoopWhile,
    LoopContinuePoint,
    LoopBreak(u8),
    LoopContinue(u8),
    LoopEnd,
    GuardStart,
    GuardAlternate,
    GuardEnd,
    SwitchStart,
    SwitchCaseStart,
    SwitchCaseBody,
    SwitchDefault,
    SwitchBreak,
    SwitchEnd,
    TryStart,
    TaggedTryStart,
    CatchStart,
    TryEnd,
    ResultStart,
    ResultReturn(u8),
    ResultEnd,
    Throw,
    TaggedThrow(u8),
    CheckError,
    UncaughtNumberThrow,
    UncaughtBooleanThrow,
    UncaughtStringThrow,
    UncaughtNumberArrayThrow,
    UncaughtBooleanArrayThrow,
    UncaughtStringArrayThrow,
    UncaughtDictionaryThrow,
    EarlyReturn,
    MathRandom,
    DateNow,
    PerformanceNow,
    ProcessPid,
    ProcessPpid,
    MissingCallable,
    Recur(u8),
}

struct NumericProgram(Vec<NumericValue>);

