//! QuickJS-NG integration for the Fallback path (docs/design/bridge.md
//! section 7): runs arbitrary JS (e.g. an npm package's actual source, once
//! thaw-registry can fetch one) in an embedded engine, exchanging values
//! with compiled Thaw code as JSON text.
//!
//! `rquickjs` (which bundles QuickJS-NG -- the bnoordhuis/saghul fork the
//! design doc names, not Bellard's original) does the real work; this
//! crate is a thin C ABI shim around it, in the same spirit as
//! thaw-std/thaw-runtime.
//!
//! Argument/result marshaling goes through JSON both at the Rust/QuickJS
//! boundary (`thaw_js_call`'s `args_json`/return) and, one level up, at the
//! HIR/codegen boundary (`callDynamic`, see hir_codegen.rs), which
//! composes this crate's `thaw_js_call` with thaw-std's
//! `thaw_json_stringify`/`thaw_json_parse` so a `Json` value flows in and
//! out without this crate needing to know thaw-std's internal
//! representation. A Promise-returning call is driven to completion by
//! polling QuickJS's job queue (`Promise::finish`) rather than true
//! non-blocking integration -- the same "poll until resolved" shortcut V1
//! async/await already takes (docs/design/async-await.md), consistent
//! rather than a special case.
//!
//! Generated code uses `thaw_js_call_result` to route unknown functions,
//! thrown JS exceptions, malformed arguments, and Promise rejections through
//! Thaw's `try`/`catch`. The original `thaw_js_call` JSON-error-object API is
//! retained for C ABI compatibility with older callers.

use std::cell::RefCell;
use std::ffi::{CStr, CString};
use std::os::raw::c_char;

use rquickjs::function::Args;
use rquickjs::{Array, Context, Ctx, Function, Object, Runtime, Value};

thread_local! {
    static JS: RefCell<Option<(Runtime, Context)>> = const { RefCell::new(None) };
}

fn to_str(ptr: *const c_char) -> String {
    unsafe { CStr::from_ptr(ptr) }
        .to_string_lossy()
        .into_owned()
}

fn with_context<R>(f: impl FnOnce(Ctx<'_>) -> R) -> R {
    JS.with(|cell| {
        let mut slot = cell.borrow_mut();
        let (_, context) = slot.get_or_insert_with(|| {
            let runtime = Runtime::new().expect("failed to create a QuickJS runtime");
            let context = Context::full(&runtime).expect("failed to create a QuickJS context");
            (runtime, context)
        });
        context.with(f)
    })
}

/// Evaluates `source` in the (per-thread) global QuickJS context. Top-level
/// function declarations become callable afterwards via `thaw_js_call`.
/// Returns `1` on success, `0` on failure (syntax error, thrown exception).
#[no_mangle]
pub extern "C" fn thaw_js_load(source: *const c_char) -> u8 {
    let source = to_str(source);
    with_context(|ctx| match load_impl(ctx, &source) {
        Ok(()) => 1,
        Err(reason) => {
            eprintln!("thaw-quickjs: failed to load script: {reason}");
            0
        }
    })
}

/// Real error message for a failed `eval`, extracted the same way
/// `call_impl` already does for a thrown exception -- without this,
/// `rquickjs::Error::Exception`'s own `Display` is just a generic
/// placeholder ("Exception generated by QuickJS"), which made a real
/// npm package's load-time failure (e.g. a top-level `require(...)` call
/// this crate's stub rejects, see thaw-bridge's `wrap_as_commonjs_module`)
/// undiagnosable.
fn load_impl(ctx: Ctx<'_>, source: &str) -> Result<(), String> {
    ctx.eval::<(), _>(source).map_err(|e| match e {
        rquickjs::Error::Exception => describe_exception(&ctx),
        e => e.to_string(),
    })
}

/// Calls a top-level function (previously loaded via `thaw_js_load`) named
/// `func_name`, with `args_json` a JSON-encoded array of arguments.
/// Returns the JSON-encoded result (or an error object -- see the module
/// doc comment).
#[no_mangle]
pub extern "C" fn thaw_js_call(
    func_name: *const c_char,
    args_json: *const c_char,
) -> *const c_char {
    let func_name = to_str(func_name);
    let args_json = to_str(args_json);

    let text = with_context(|ctx| match call_impl(ctx, &func_name, &args_json) {
        Ok(text) => text,
        Err(reason) => format!("{{\"__thaw_error__\":{}}}", json_escape_string(&reason)),
    });

    CString::new(text).unwrap_or_default().into_raw() as *const c_char
}

/// Result-ABI companion to [`thaw_js_call`]. Unlike the legacy JSON error
/// object API, failures occupy the error channel so generated Thaw code can
/// route JavaScript throws and Promise rejections through `try`/`catch`.
#[no_mangle]
pub extern "C" fn thaw_js_call_result(
    func_name: *const c_char,
    args_json: *const c_char,
) -> ThawResult {
    let func_name = to_str(func_name);
    let args_json = to_str(args_json);
    match with_context(|ctx| call_impl(ctx, &func_name, &args_json)) {
        Ok(text) => ThawResult {
            value: CString::new(text).unwrap_or_default().into_raw(),
            error: std::ptr::null(),
        },
        Err(reason) => ThawResult {
            value: std::ptr::null(),
            error: CString::new(reason).unwrap_or_default().into_raw(),
        },
    }
}

fn call_impl(ctx: Ctx<'_>, func_name: &str, args_json: &str) -> Result<String, String> {
    let target: Function = ctx
        .globals()
        .get(func_name)
        .map_err(|_| format!("no such function `{func_name}` (was it loaded via loadScript?)"))?;
    invoke_impl(ctx, target, func_name, args_json)
}

fn invoke_impl<'js>(
    ctx: Ctx<'js>,
    target: Function<'js>,
    label: &str,
    args_json: &str,
) -> Result<String, String> {
    let to_string_err = |e: rquickjs::Error| e.to_string();

    let json: Object = ctx.globals().get("JSON").map_err(to_string_err)?;
    let parse: Function = json.get("parse").map_err(to_string_err)?;
    let stringify: Function = json.get("stringify").map_err(to_string_err)?;

    let args_array: Array = parse
        .call((args_json,))
        .map_err(|e| format!("args_json is not a valid JSON array: {e}"))?;

    let mut call_args = Args::new_unsized(ctx.clone());
    for i in 0..args_array.len() {
        let arg: Value = args_array.get(i).map_err(to_string_err)?;
        call_args.push_arg(arg).map_err(to_string_err)?;
    }

    let result: Value = target.call_arg(call_args).map_err(|e| match e {
        rquickjs::Error::Exception => format!("`{label}` threw: {}", describe_exception(&ctx)),
        e => format!("`{label}` threw: {e}"),
    })?;

    // Always pass the result through the realm's Promise resolution
    // procedure. `Value::as_promise` only recognizes native Promise objects;
    // `Promise.resolve` also assimilates arbitrary foreign thenables, handles
    // throwing `then` accessors/calls, and obeys the first-settlement-wins
    // rule required by JavaScript.
    let assimilate: Function = ctx
        .eval("(value) => Promise.resolve(value)")
        .map_err(to_string_err)?;
    let promise: rquickjs::Promise = assimilate.call((result,)).map_err(|e| match e {
        rquickjs::Error::Exception => {
            format!(
                "`{label}` could not resolve its result: {}",
                describe_exception(&ctx)
            )
        }
        e => format!("`{label}` could not resolve its result: {e}"),
    })?;
    let result = promise.finish::<Value>().map_err(|e| match e {
        rquickjs::Error::Exception => {
            format!("`{label}`'s promise rejected: {}", describe_exception(&ctx))
        }
        e => format!("`{label}`'s promise rejected or stalled: {e}"),
    })?;

    stringify
        .call((result,))
        .map_err(|e| format!("failed to JSON-encode the result: {e}"))
}

/// Retains a global JavaScript value in the realm and returns a stable opaque
/// handle. Zero denotes failure or a missing value.
#[no_mangle]
pub extern "C" fn thaw_js_get_global(name: *const c_char) -> u64 {
    let name = to_str(name);
    with_context(|ctx| {
        let Ok(value) = ctx.globals().get::<_, Value>(name.as_str()) else {
            return 0;
        };
        let globals = ctx.globals();
        let handles: Array = match globals.get("__thaw_value_handles") {
            Ok(handles) => handles,
            Err(_) => {
                let Ok(handles) = Array::new(ctx.clone()) else {
                    return 0;
                };
                if globals
                    .set("__thaw_value_handles", handles.clone())
                    .is_err()
                {
                    return 0;
                }
                handles
            }
        };
        let index = handles.len();
        if handles.set(index, value).is_err() {
            return 0;
        }
        index as u64 + 1
    })
}

/// Calls a callable value retained by [`thaw_js_get_global`]. Arguments and
/// results use the existing JSON bridge while the callable itself preserves
/// identity and closures inside QuickJS.
#[no_mangle]
pub extern "C" fn thaw_js_call_handle_result(handle: u64, args_json: *const c_char) -> ThawResult {
    let args_json = to_str(args_json);
    let result = with_context(|ctx| {
        if handle == 0 {
            return Err("invalid JavaScript value handle".to_string());
        }
        let handles: Array = ctx
            .globals()
            .get("__thaw_value_handles")
            .map_err(|_| "JavaScript value handle registry is empty".to_string())?;
        let target: Function = handles
            .get((handle - 1) as usize)
            .map_err(|_| format!("JavaScript value handle {handle} is not callable"))?;
        invoke_impl(
            ctx,
            target,
            &format!("JavaScript value #{handle}"),
            &args_json,
        )
    });
    match result {
        Ok(text) => ThawResult {
            value: CString::new(text).unwrap_or_default().into_raw(),
            error: std::ptr::null(),
        },
        Err(reason) => ThawResult {
            value: std::ptr::null(),
            error: CString::new(reason).unwrap_or_default().into_raw(),
        },
    }
}

/// `rquickjs::Error::Exception` doesn't carry the thrown value itself
/// (just a generic placeholder message) -- the real value has to be
/// fetched separately via `Ctx::catch`.
fn describe_exception(ctx: &Ctx<'_>) -> String {
    let exc = ctx.catch();
    if let Some(obj) = exc.as_object() {
        if let Ok(msg) = obj.get::<_, String>("message") {
            return msg;
        }
    }
    if let Some(s) = exc.as_string() {
        if let Ok(s) = s.to_string() {
            return s;
        }
    }
    format!("{exc:?}")
}

fn json_escape_string(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('"');
    for c in s.chars() {
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c if (c as u32) < 0x20 => out.push_str(&format!("\\u{:04x}", c as u32)),
            c => out.push(c),
        }
    }
    out.push('"');
    out
}

#[cfg(test)]
#[allow(clippy::items_after_test_module)]
mod tests {
    use super::*;

    fn call(func_name: &str, args_json: &str) -> String {
        let func_name = CString::new(func_name).unwrap();
        let args_json = CString::new(args_json).unwrap();
        let result_ptr = thaw_js_call(func_name.as_ptr(), args_json.as_ptr());
        unsafe { CStr::from_ptr(result_ptr) }
            .to_string_lossy()
            .into_owned()
    }

    fn load(source: &str) -> u8 {
        let source = CString::new(source).unwrap();
        thaw_js_load(source.as_ptr())
    }

    #[test]
    fn loads_and_calls_a_simple_function() {
        assert_eq!(load("function add(a, b) { return a + b; }"), 1);
        assert_eq!(call("add", "[2, 3]"), "5");
    }

    #[test]
    fn round_trips_objects_and_arrays() {
        assert_eq!(load("function identity(x) { return x; }"), 1);
        assert_eq!(
            call("identity", r#"[{"a": 1, "b": [true, "x"]}]"#),
            r#"{"a":1,"b":[true,"x"]}"#
        );
    }

    #[test]
    fn resolves_a_returned_promise() {
        assert_eq!(
            load("function later(x) { return Promise.resolve(x * 2); }"),
            1
        );
        assert_eq!(call("later", "[21]"), "42");
    }

    #[test]
    fn retains_and_calls_a_callable_javascript_value() {
        assert_eq!(
            load("globalThis.times = factor => value => Promise.resolve(value * factor); globalThis.twice = times(2);"),
            1
        );
        let name = CString::new("twice").unwrap();
        let handle = thaw_js_get_global(name.as_ptr());
        assert_ne!(handle, 0);
        let args = CString::new("[21]").unwrap();
        let result = thaw_js_call_handle_result(handle, args.as_ptr());
        assert!(result.error.is_null());
        assert_eq!(
            unsafe { CStr::from_ptr(result.value) }.to_str().unwrap(),
            "42"
        );
    }

    #[test]
    fn assimilates_foreign_thenables_once_and_reports_then_errors() {
        assert_eq!(
            load(
                "function thenable() {\n\
                   return { then(resolve, reject) { resolve(42); reject('late'); resolve(99); } };\n\
                 }\n\
                 function throwingThen() {\n\
                   return Object.create(null, { then: { get() { throw new Error('bad then'); } } });\n\
                 }"
            ),
            1
        );
        assert_eq!(call("thenable", "[]"), "42");
        let failed = call("throwingThen", "[]");
        assert!(failed.contains("__thaw_error__"), "{failed}");
        assert!(failed.contains("bad then"), "{failed}");
    }

    #[test]
    fn unknown_function_reports_an_error_object_instead_of_crashing() {
        let result = call("doesNotExist", "[]");
        assert!(
            result.contains("__thaw_error__"),
            "unexpected result: {result}"
        );
    }

    #[test]
    fn thrown_exception_reports_an_error_object_instead_of_crashing() {
        assert_eq!(load("function boom() { throw new Error('kaboom'); }"), 1);
        let result = call("boom", "[]");
        assert!(
            result.contains("__thaw_error__"),
            "unexpected result: {result}"
        );
        assert!(result.contains("kaboom"), "unexpected result: {result}");
    }

    #[test]
    fn result_abi_separates_success_from_javascript_exceptions() {
        assert_eq!(
            load("function ok() { return 42; } function boom() { throw new Error('kaboom'); }"),
            1
        );
        let ok_name = CString::new("ok").unwrap();
        let boom_name = CString::new("boom").unwrap();
        let args = CString::new("[]").unwrap();
        let ok = thaw_js_call_result(ok_name.as_ptr(), args.as_ptr());
        assert!(ok.error.is_null());
        assert_eq!(unsafe { CStr::from_ptr(ok.value) }.to_str().unwrap(), "42");

        let failed = thaw_js_call_result(boom_name.as_ptr(), args.as_ptr());
        assert!(failed.value.is_null());
        let error = unsafe { CStr::from_ptr(failed.error) }.to_string_lossy();
        assert!(error.contains("kaboom"), "{error}");
    }

    #[test]
    fn syntax_error_fails_to_load_instead_of_crashing() {
        assert_eq!(load("function( this is not valid js"), 0);
    }

    /// Regression test for the pre-fix behavior: a thrown exception during
    /// `loadScript` used to report only `rquickjs::Error::Exception`'s
    /// generic placeholder message on stderr, not the real thrown message
    /// -- undiagnosable for e.g. a real npm package's top-level
    /// `require(...)` call. `load_impl` is the testable inner function
    /// (`thaw_js_load` itself only returns 0/1, with the message going to
    /// stderr).
    #[test]
    fn load_failure_reports_the_real_thrown_message() {
        with_context(|ctx| {
            let err = load_impl(ctx, "throw new Error('boom');").unwrap_err();
            assert_eq!(err, "boom");
        });
    }
}
/// Common C ABI result for external operations that can either return a
/// pointer-shaped value or throw. Both pointers are owned by the callee for
/// the current request; exactly one is non-null.
#[repr(C)]
pub struct ThawResult {
    pub value: *const c_char,
    pub error: *const c_char,
}
