[package]
name = "thaw-registry"
version = "0.1.0"
edition.workspace = true

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1.0.151"
sha2 = "0.10"
thaw-parser = { path = "../thaw-parser" }
swc_ecma_visit = "29.0.0"

[dev-dependencies]
thaw-quickjs = { path = "../thaw-quickjs" }
