[package]
name = "thaw-cli"
version = "0.1.0"
edition.workspace = true
build = "build.rs"

[[bin]]
name = "thaw"
path = "src/main.rs"

[dependencies]
flate2 = "1"
inkwell = { version = "0.10.0", features = ["llvm22-1"] }
thaw-bridge = { version = "0.1.0", path = "../thaw-bridge" }
thaw-hir = { version = "0.1.0", path = "../thaw-hir" }
thaw-llvm = { version = "0.1.0", path = "../thaw-llvm" }
thaw-parser = { version = "0.1.0", path = "../thaw-parser" }
thaw-registry = { version = "0.1.0", path = "../thaw-registry" }
swc_ecma_visit = "29.0.0"
serde_json = "1"
