pub(super) fn source(name: &str) -> Option<&'static str> {
    match name {
        // Found necessary by a real ESM package (`has-flag`): `import
        // process from 'process'` -- Node exposes `process` as both a
        // global and a core module; this is the module half. `.default`
        // is set too so the ESM-interop convention `rewrite_esm_to_commonjs`
        // generates for a default import (`.__esModule ? .default : ...`)
        // finds the same object either way. Only the couple of fields a
        // real package has actually been found to read.
        "process" => Some(
            "var __thaw_process = globalThis.process || { argv: [], env: {}, platform: 'linux', version: '', versions: {}, cwd: function() { return '/'; }, nextTick: function(fn) { var args = Array.prototype.slice.call(arguments, 1); Promise.resolve().then(function() { fn.apply(undefined, args); }); } };\n\
             if (!__thaw_process.cwd) __thaw_process.cwd = function() { return '/'; };\n\
             module.exports = __thaw_process;\n\
             module.exports.default = __thaw_process;\n\
             module.exports.__esModule = true;\n",
        ),
        "child_process" => Some(
            r#"var EventEmitter = require('node:events'), streams = require('node:stream');
             function normalize(command, args, options) { if (!Array.isArray(args)) { options = args || {}; args = []; } else options = options || {}; command = String(command); args = args.map(String); if (options.shell) { var shell = typeof options.shell === 'string' ? options.shell : '/bin/sh', joined = [command].concat(args).map(function(value) { return "'" + value.replace(/'/g, "'\\''") + "'"; }).join(' '); command = shell; args = ['-c', joined]; } var environment; if (options.env) { environment = {}; Object.keys(options.env).forEach(function(name) { if (options.env[name] !== undefined) environment[name] = String(options.env[name]); }); } var input = options.input === undefined ? undefined : Buffer.from(options.input, options.encoding).toString('hex'); return { command: command, args: args, options: { cwd: options.cwd === undefined ? undefined : String(options.cwd), env: environment, input: input, detached: Boolean(options.detached) }, original: options }; }
             function processError(record, normalized) { var error = new Error(record.error || ('Command failed: ' + normalized.command)); error.code = record.code || null; error.errno = record.errno === undefined ? null : record.errno; error.path = record.path || normalized.command; error.spawnargs = normalized.args.slice(); error.status = record.status === undefined ? null : record.status; error.signal = record.signal === undefined ? null : record.signal; return error; }
             function decode(record, options) { var encoding = options.encoding === undefined ? null : options.encoding, stdout = Buffer.from(record.stdout || '', 'hex'), stderr = Buffer.from(record.stderr || '', 'hex'); if (encoding && encoding !== 'buffer') { stdout = stdout.toString(encoding); stderr = stderr.toString(encoding); } return { pid: record.pid || 0, output: [null, stdout, stderr], stdout: stdout, stderr: stderr, status: record.status === undefined ? null : record.status, signal: record.signal === undefined ? null : record.signal, error: record.error ? processError(record, { command: record.path || '', args: [] }) : undefined }; }
             function spawnSync(command, args, options) { var normalized = normalize(command, args, options), record = JSON.parse(__thaw_child_process_sync(normalized.command, JSON.stringify(normalized.args), JSON.stringify(normalized.options))), result = decode(record, normalized.original), maxBuffer = normalized.original.maxBuffer === undefined ? 1048576 : Number(normalized.original.maxBuffer); if (!result.error && result.stdout.length + result.stderr.length > maxBuffer) { var error = new Error('spawnSync ' + normalized.command + ' ENOBUFS'); error.code = 'ENOBUFS'; result.error = error; result.status = null; } return result; }
             function execFileSync(file, args, options) { var normalized = normalize(file, args, options), result = spawnSync(file, args, options); if (result.error || result.status !== 0) { var error = result.error || processError({ status: result.status, signal: result.signal }, normalized); error.stdout = result.stdout; error.stderr = result.stderr; error.output = result.output; error.pid = result.pid; throw error; } return result.stdout; }
             function execSync(command, options) { options = options || {}; return execFileSync(options.shell || '/bin/sh', ['-c', String(command)], Object.assign({}, options, { shell: false })); }
             var children = new Map(), signals = { SIGHUP: 1, SIGINT: 2, SIGQUIT: 3, SIGKILL: 9, SIGUSR1: 10, SIGUSR2: 12, SIGPIPE: 13, SIGALRM: 14, SIGTERM: 15 }; function signalName(signal) { if (signal === null || signal === undefined) return null; var names = Object.keys(signals); for (var index = 0; index < names.length; index++) if (signals[names[index]] === signal) return names[index]; return 'SIG' + signal; } function signalNumber(signal) { if (signal === undefined || signal === null) return signals.SIGTERM; if (typeof signal === 'string') { signal = signal.toUpperCase(); if (signals[signal] !== undefined) return signals[signal]; } else if (Number.isInteger(signal) && signal > 0) return signal; var error = new TypeError('Unknown signal: ' + signal); error.code = 'ERR_UNKNOWN_SIGNAL'; throw error; }
             function ChildProcess(normalized) { EventEmitter.call(this); this.pid = 0; this.spawnfile = normalized.command; this.spawnargs = [normalized.command].concat(normalized.args); this.killed = false; this.connected = false; this.exitCode = null; this.signalCode = null; this.detached = Boolean(normalized.original.detached); this._closed = false; this._spawnError = false; this._timedOut = false; var child = this; this._stdin = new streams.Writable({ write: function(chunk, encoding, callback) { if (!child._closed) __thaw_child_process_stdin(child._handle, Buffer.from(chunk).toString('hex'), false); callback(); }, final: function(callback) { if (!child._closed) __thaw_child_process_stdin(child._handle, '', true); callback(); } }); this._stdout = new streams.PassThrough(); this._stderr = new streams.PassThrough(); var stdio = normalized.original.stdio === undefined ? 'pipe' : normalized.original.stdio, modes = Array.isArray(stdio) ? stdio.slice(0, 3) : [stdio, stdio, stdio]; while (modes.length < 3) modes.push('pipe'); modes = modes.map(function(mode) { mode = mode === null || mode === undefined ? 'pipe' : mode; if (mode !== 'pipe' && mode !== 'ignore' && mode !== 'inherit') { var error = new TypeError('The argument stdio is invalid. Received ' + mode); error.code = 'ERR_INVALID_ARG_VALUE'; throw error; } return mode; }); this._stdioModes = modes; this.stdin = modes[0] === 'pipe' ? this._stdin : null; this.stdout = modes[1] === 'pipe' ? this._stdout : null; this.stderr = modes[2] === 'pipe' ? this._stderr : null; this.stdio = [this.stdin, this.stdout, this.stderr]; this.channel = null; this._handle = __thaw_child_process_spawn(normalized.command, JSON.stringify(normalized.args), JSON.stringify(normalized.options)); children.set(this._handle, this); if (modes[0] !== 'pipe') this._stdin.end(); var timeout = Number(normalized.original.timeout || 0); if (timeout > 0 && Number.isFinite(timeout)) this._timeout = setTimeout(function() { if (!child._closed) { child._timedOut = true; child.kill(normalized.original.killSignal); } }, timeout); var signal = normalized.original.signal; if (signal && typeof signal.addEventListener === 'function') { this._abortSignal = signal; this._abortListener = function() { if (child._closed || child._aborted) return; child._aborted = true; var error = new Error('The operation was aborted'); error.name = 'AbortError'; error.code = 'ABORT_ERR'; error.cause = signal.reason; child.emit('error', error); child.kill(normalized.original.killSignal); }; signal.addEventListener('abort', this._abortListener, { once: true }); if (signal.aborted) queueMicrotask(this._abortListener); } }
             ChildProcess.prototype = Object.create(EventEmitter.prototype); ChildProcess.prototype.constructor = ChildProcess; ChildProcess.prototype.kill = function(signal) { if (this._closed) return false; this.killed = __thaw_child_process_kill(this._handle, signalNumber(signal)); return this.killed; }; ChildProcess.prototype.ref = function() { return this; }; ChildProcess.prototype.unref = function() { return this; }; ChildProcess.prototype.disconnect = function() { if (!this.connected) { var error = new Error('IPC channel is already disconnected'); error.code = 'ERR_IPC_DISCONNECTED'; throw error; } this.connected = false; this.channel = null; if (this.stdin && !this.stdin.writableEnded) this.stdin.end(); this.emit('disconnect'); return this; }; ChildProcess.prototype.send = function(message, sendHandle, options, callback) { if (typeof sendHandle === 'function') callback = sendHandle; else if (typeof options === 'function') callback = options; if (!this.connected || !this._ipc) { var error = new Error('Channel closed'); error.code = 'ERR_IPC_CHANNEL_CLOSED'; if (callback) { queueMicrotask(function() { callback(error); }); return false; } throw error; } var serialized; try { serialized = JSON.stringify(message); } catch (error) { if (callback) queueMicrotask(function() { callback(error); }); else throw error; return false; } this.stdin.write('__THAW_IPC__' + serialized + '\n', function(error) { if (callback) callback(error || null); }); return true; };
             function spawn(command, args, options) { return new ChildProcess(normalize(command, args, options)); }
             function fork(modulePath, args, options) { if (!Array.isArray(args)) { options = args || {}; args = []; } else options = options || {}; if (typeof modulePath !== 'string' && !(modulePath instanceof String)) { var pathError = new TypeError('The modulePath argument must be of type string'); pathError.code = 'ERR_INVALID_ARG_TYPE'; throw pathError; } var wrapper = "var prefix='__THAW_IPC__',buffer='';process.send=function(value,handle,options,callback){if(typeof handle==='function')callback=handle;else if(typeof options==='function')callback=options;try{process.stdout.write(prefix+JSON.stringify(value)+'\\n',function(){if(typeof callback==='function')callback(null);});return true;}catch(error){if(typeof callback==='function')callback(error);else throw error;return false;}};process.connected=true;process.disconnect=function(){if(!process.connected)return;process.connected=false;process.emit('disconnect');process.stdin.destroy();setTimeout(function(){process.exit(0);},0);};process.stdin.setEncoding('utf8');process.stdin.on('data',function(chunk){buffer+=chunk;for(;;){var end=buffer.indexOf('\\n');if(end<0)break;var line=buffer.slice(0,end);buffer=buffer.slice(end+1);if(line.indexOf(prefix)===0)process.emit('message',JSON.parse(line.slice(prefix.length)));}});process.stdin.on('end',process.disconnect);require(require('path').resolve(process.argv[1]));"; var childOptions = Object.assign({}, options, { stdio: 'pipe' }), execArgv = options.execArgv === undefined ? [] : Array.from(options.execArgv, String), child = spawn(options.execPath || process.execPath || 'node', execArgv.concat(['-e', wrapper, String(modulePath)]).concat(args.map(String)), childOptions); child.connected = true; child.channel = {}; child._ipc = true; child._ipcBuffer = ''; child._ipcOutputMode = options.silent ? 'pipe' : 'inherit'; if (!options.silent) { child.stdout = null; child.stderr = null; child.stdio = [child.stdin, null, null, child.channel]; } else child.stdio.push(child.channel); return child; }
             function execFile(file, args, options, callback) { if (typeof args === 'function') { callback = args; args = []; options = {}; } else if (!Array.isArray(args)) { callback = options; options = args || {}; args = []; } else if (typeof options === 'function') { callback = options; options = {}; } options = options || {}; var child = spawn(file, args, options), stdout = [], stderr = [], encoding = options.encoding || 'utf8', maxBuffer = options.maxBuffer === undefined ? 1048576 : Number(options.maxBuffer); child.stdout.on('data', function(value) { stdout.push(Buffer.from(value)); }); child.stderr.on('data', function(value) { stderr.push(Buffer.from(value)); }); child.once('close', function(code, signal) { var out = Buffer.concat(stdout), err = Buffer.concat(stderr), decodedOut = encoding === 'buffer' ? out : out.toString(encoding), decodedErr = encoding === 'buffer' ? err : err.toString(encoding), error = null; if (out.length + err.length > maxBuffer) { error = new Error('stdout maxBuffer length exceeded'); error.code = 'ERR_CHILD_PROCESS_STDIO_MAXBUFFER'; } else if (code !== 0) { error = new Error('Command failed: ' + file + '\n' + decodedErr); error.code = code; error.killed = child.killed; error.signal = signal; error.cmd = file; } if (error) { error.stdout = decodedOut; error.stderr = decodedErr; } if (typeof callback === 'function') callback(error, decodedOut, decodedErr); }); child.stdin.end(); return child; }
             function exec(command, options, callback) { if (typeof options === 'function') { callback = options; options = {}; } options = options || {}; return execFile(options.shell || '/bin/sh', ['-c', String(command)], Object.assign({}, options, { shell: false }), callback); }
             if (!globalThis.__thaw_child_process_poll_installed) { globalThis.__thaw_child_process_poll_installed = true; var previousPlatformPoll = globalThis.__thaw_poll_platform_events; globalThis.__thaw_poll_platform_events = function() { if (previousPlatformPoll) previousPlatformPoll(); JSON.parse(__thaw_child_process_poll()).forEach(function(event) { var child = children.get(event.handle); if (!child) return; if (event.type === 'spawn') { child.pid = Number(event.pid); child.emit('spawn'); } else if (event.type === 'stdout') { var stdout = Buffer.from(event.value, 'hex'); if (child._ipc) { child._ipcBuffer += stdout.toString(); for (;;) { var end = child._ipcBuffer.indexOf('\n'); if (end < 0) break; var line = child._ipcBuffer.slice(0, end); child._ipcBuffer = child._ipcBuffer.slice(end + 1); if (line.indexOf('__THAW_IPC__') === 0) { try { child.emit('message', JSON.parse(line.slice(12))); } catch (error) { child.emit('error', error); } } else if (child._ipcOutputMode === 'inherit' && process.stdout && process.stdout.write) process.stdout.write(Buffer.from(line + '\n')); else child._stdout.write(Buffer.from(line + '\n')); } } else if (child._stdioModes[1] === 'pipe') child._stdout.write(stdout); else if (child._stdioModes[1] === 'inherit' && process.stdout && process.stdout.write) process.stdout.write(stdout); } else if (event.type === 'stderr') { var stderr = Buffer.from(event.value, 'hex'); if (child._ipc && child._ipcOutputMode === 'inherit' && process.stderr && process.stderr.write) process.stderr.write(stderr); else if (child._stdioModes[2] === 'pipe') child._stderr.write(stderr); else if (child._stdioModes[2] === 'inherit' && process.stderr && process.stderr.write) process.stderr.write(stderr); } else if (event.type === 'error') { child._spawnError = true; var error = new Error(event.message); error.code = event.code; error.path = child.spawnfile; error.spawnargs = child.spawnargs.slice(1); child.emit('error', error); } else if (event.type === 'exit') { child._closed = true; child.exitCode = event.code === null ? null : Number(event.code); child.signalCode = signalName(event.signal); if (child._ipcBuffer) { if (child._ipcOutputMode === 'inherit' && process.stdout && process.stdout.write) process.stdout.write(Buffer.from(child._ipcBuffer)); else child._stdout.write(Buffer.from(child._ipcBuffer)); } child._stdout.end(); child._stderr.end(); if (!child._stdin.writableEnded) child._stdin.end(); if (child.connected) { child.connected = false; child.channel = null; child.emit('disconnect'); } if (child._timeout) clearTimeout(child._timeout); if (child._abortSignal && child._abortListener) child._abortSignal.removeEventListener('abort', child._abortListener); if (!child._spawnError) child.emit('exit', child.exitCode, child.signalCode); child.emit('close', child.exitCode, child.signalCode); children.delete(event.handle); } }); }; }
             module.exports = { ChildProcess: ChildProcess, spawn: spawn, fork: fork, exec: exec, execFile: execFile, spawnSync: spawnSync, execFileSync: execFileSync, execSync: execSync }; module.exports.default = module.exports; module.exports.__esModule = true;
"#,
        ),
        "punycode" => Some(
            "var base = 36, tMin = 1, tMax = 26, skew = 38, damp = 700, initialBias = 72, initialN = 128, delimiter = '-'; function adapt(delta, points, first) { delta = first ? Math.floor(delta / damp) : delta >> 1; delta += Math.floor(delta / points); var k = 0; while (delta > Math.floor(((base - tMin) * tMax) / 2)) { delta = Math.floor(delta / (base - tMin)); k += base; } return k + Math.floor(((base - tMin + 1) * delta) / (delta + skew)); } function encodeDigit(value) { return String.fromCharCode(value + 22 + 75 * (value < 26)); } function decodeDigit(code) { if (code >= 48 && code <= 57) return code - 22; if (code >= 65 && code <= 90) return code - 65; if (code >= 97 && code <= 122) return code - 97; return base; } function codePoints(value) { return Array.from(String(value)).map(function(character) { return character.codePointAt(0); }); }\n\
             function encode(value) { var input = codePoints(value), output = [], n = initialN, delta = 0, bias = initialBias; input.forEach(function(point) { if (point < 128) output.push(String.fromCharCode(point)); }); var basic = output.length, handled = basic; if (basic) output.push(delimiter); while (handled < input.length) { var next = Infinity; input.forEach(function(point) { if (point >= n && point < next) next = point; }); delta += (next - n) * (handled + 1); n = next; input.forEach(function(point) { if (point < n) delta++; if (point === n) { var q = delta; for (var k = base;; k += base) { var threshold = k <= bias ? tMin : k >= bias + tMax ? tMax : k - bias; if (q < threshold) break; output.push(encodeDigit(threshold + ((q - threshold) % (base - threshold)))); q = Math.floor((q - threshold) / (base - threshold)); } output.push(encodeDigit(q)); bias = adapt(delta, handled + 1, handled === basic); delta = 0; handled++; } }); delta++; n++; } return output.join(''); }\n\
             function decode(value) { var input = String(value), output = [], n = initialN, index = 0, bias = initialBias, i = 0, delimiterIndex = input.lastIndexOf(delimiter); if (delimiterIndex >= 0) { for (var basicIndex = 0; basicIndex < delimiterIndex; basicIndex++) { var basicCode = input.charCodeAt(basicIndex); if (basicCode >= 128) throw new RangeError('Illegal input'); output.push(basicCode); } index = delimiterIndex + 1; } while (index < input.length) { var oldI = i, weight = 1; for (var k = base;; k += base) { if (index >= input.length) throw new RangeError('Invalid input'); var digit = decodeDigit(input.charCodeAt(index++)); if (digit >= base) throw new RangeError('Invalid input'); i += digit * weight; var threshold = k <= bias ? tMin : k >= bias + tMax ? tMax : k - bias; if (digit < threshold) break; weight *= base - threshold; } var length = output.length + 1; bias = adapt(i - oldI, length, oldI === 0); n += Math.floor(i / length); i %= length; output.splice(i, 0, n); i++; } return String.fromCodePoint.apply(String, output); }\n\
             function mapDomain(value, callback) { var input = String(value), parts = input.split('@'), local = ''; if (parts.length > 1) local = parts.shift() + '@'; return local + parts.join('@').replace(/[\\u3002\\uFF0E\\uFF61]/g, '.').split('.').map(callback).join('.'); } function toASCII(value) { return mapDomain(value, function(label) { return /[^\\x00-\\x7F]/.test(label) ? 'xn--' + encode(label) : label; }); } function toUnicode(value) { return mapDomain(value, function(label) { return /^xn--/i.test(label) ? decode(label.slice(4).toLowerCase()) : label; }); } var ucs2 = { decode: codePoints, encode: function(points) { return String.fromCodePoint.apply(String, points); } }; module.exports = { version: '2.1.0', ucs2: ucs2, decode: decode, encode: encode, toASCII: toASCII, toUnicode: toUnicode }; module.exports.default = module.exports; module.exports.__esModule = true;\n",
        ),
        // Found necessary chasing a real native addon's load path
        // (`bcrypt`, `utf-8-validate`): both depend on `node-gyp-build`,
        // which unconditionally does `require('path')`/`require('os')`/
        // `require('fs')` at the top of its own real, unmodified source
        // (`node-gyp-build.js`) before it ever gets to the actual
        // native-addon lookup. Pure string manipulation, no dependency on
        // any crate -- `path` never touches a real filesystem in Node
        // either (that's what `fs` is for).
        _ => None,
    }
}
