/// `native_lib_available` is false: a real npm package fetched via
/// `thaw registry add` is pure JS with no native counterpart at all, so a
/// type shape that happens to be fully representable in a native ABI
/// (e.g. date-fns's `daysToWeeks(days: number): number`) still has
/// nothing to link against. Treating it as FastPath anyway produces a
/// confusing `undefined reference` linker error for a function that has
/// a perfectly good JS implementation sitting right next to it in
/// `bundle.js`.
///
/// This is the single source of truth for "is this name actually
/// callable via FFI" -- `generate_shim` and any caller that separately
/// needs to know which names require Fallback binding (e.g. thaw-cli's
/// `ModuleBundle::fallback_names`) both call this rather than
/// `classify_all` directly, so they can't disagree.
/// Whether `name` is one of the handful of identifiers thaw-hir gives a
/// special, *global* meaning to when it's read bare as a value
/// (`undefined`, `NaN`, `Infinity`) -- see `lower_expr`'s own
/// `Expr::Ident` arm, which treats a bare reference to one of these
/// names as the corresponding literal *unless* the compiled program
/// happens to declare a real top-level signature under that exact name
/// (a defensive check meant for a user shadowing one of these on
/// purpose). A Fallback package that genuinely exports something under
/// one of these names (real example: zod's own `z.undefined()`) is
/// still always reachable through its properly-typed, mangled symbol --
/// a plain import, or a namespace/package-qualified alias -- but a
/// *bare*, unqualified top-level declaration literally named
/// `undefined` would shadow thaw-hir's own special-casing globally, for
/// every `!= undefined`/`=== undefined` comparison anywhere in the
/// *entire* compiled program, not just calls to this one function --
/// including inside thaw's own generated arity-dispatch wrapper's own
/// `param != undefined` optional-parameter guard, which has nothing to
/// do with this function at all. So the bare (non-qualified) form is
/// skipped for exactly these names; the package-qualified alias
/// (`pkg_undefined`) is unaffected, since it can never collide with a
/// bare literal reference.
pub fn shadows_a_thaw_literal_identifier(name: &str) -> bool {
    matches!(name, "undefined" | "NaN" | "Infinity")
}

pub fn effective_classifications(
    functions: &[DtsFunction],
    native_lib_available: bool,
) -> Vec<(String, Classification)> {
    classify_all(functions)
        .into_iter()
        .map(|(name, classification)| match classification {
            Classification::FastPath(_) if !native_lib_available => (
                name.clone(),
                Classification::Fallback {
                    function: name,
                    reason: "no linked native library backs this Fast path signature".to_string(),
                },
            ),
            other => (name, other),
        })
        .collect()
}

/// `native_lib_available` says whether there's actually a linkable
/// native library backing this `.d.ts`'s FastPath signatures -- see
/// `effective_classifications`. thaw-cli passes `true` only for the
/// manual `--bridge` path, where the user is already responsible for
/// supplying a matching `--link`ed library themselves (that contract
/// predates this flag and is unchanged); for a registry (`--use`)
/// package it passes whether `native.a` actually exists.
/// A Fallback name thaw-cli also wants reachable through a package-
/// qualified Thaw-callable identifier, so a user can write `qs.parse(x)`
/// (rewritten by thaw-cli to call `alias`, since Thaw has no real
/// object/member-call support backing this -- it's pure source-level
/// syntax sugar) regardless of whether `parse` happens to collide with
/// another `--use`d package's own name. `qualified_key` is the JS-global
/// lookup key `callDynamic` uses at runtime, which must match the same
/// key `ModuleBundle::qualified_aliases` captured right after this
/// package's `loadScript` (`generate_module_init`) -- these always
/// travel together as a pair, generated by the same thaw-cli pass.
///
/// `suppress_bare` is set when `name` collides with another `--use`d
/// package's own declared name (thaw-cli detects this -- no single
/// `.d.ts`/package knows about any other package on its own): the bare
/// name is then *not* emitted at all, forcing qualified syntax, since
/// leaving it in would silently resolve to whichever colliding package
/// loaded last. When `false` (the common, non-colliding case), both the
/// bare name and the qualified alias are emitted, so a name stays
/// callable either way.
pub struct QualifiedFallback {
    pub name: String,
    pub alias: String,
    pub qualified_key: String,
    pub suppress_bare: bool,
}

/// `qualified` names (see `QualifiedFallback`) additionally get a
/// package-qualified alias function (and, when `suppress_bare` is set,
/// have their bare name dropped entirely -- see that field's doc
/// comment). A name not in `qualified` is emitted exactly as before.
/// Generates a Thaw-compilable TypeScript "shim" for a `.d.ts`'s functions,
/// per their classification (docs/design/bridge.md section 6/7): a
/// `FastPath` function becomes a plain ambient `declare function` (so
/// calling it compiles to a direct FFI call, resolved at link time --
/// still requires `thaw build --link <path>` today, until thaw-registry
/// can fetch/build that library automatically); a `Fallback` function
/// becomes a thin wrapper wired to the QuickJS-NG path (`callDynamic`).
///
/// This only generates the *callable surface* -- for `Fallback` functions,
/// something still has to `loadScript(...)` the package's actual JS source
/// before the wrapper is called (not generated here: there's no
/// module-level initialization mechanism in Thaw yet to hook that up
/// automatically, so it stays the caller's explicit responsibility, e.g.
/// as the first statement in `main`/`handler`).
/// `classify_all`, then downgrades every FastPath entry to Fallback when
pub fn generate_shim(
    functions: &[DtsFunction],
    native_lib_available: bool,
    qualified: &[QualifiedFallback],
    typed_bare_aliases: &std::collections::HashSet<String>,
) -> String {
    let mut out = String::new();
    for (name, classification) in effective_classifications(functions, native_lib_available) {
        match classification {
            Classification::FastPath(sig) => {
                // `classify_all` only returns `FastPath` for a name with
                // exactly one signature, so this lookup is unambiguous.
                let func = functions
                    .iter()
                    .find(|f| f.name == name)
                    .expect("FastPath classification implies a matching DtsFunction exists");
                let mut params = func
                    .params
                    .iter()
                    .zip(&sig.params)
                    .map(|((name, _), ty)| format!("{name}: {}", render_ts_type(ty)))
                    .collect::<Vec<_>>();
                if let (Some((name, _)), Some(variadic)) = (&func.rest_param, &sig.variadic) {
                    params.push(format!("...{name}: {}[]", render_ts_type(variadic)));
                }
                let params = params.join(", ");
                out.push_str(&format!(
                    "declare function {}({params}): {};\n",
                    sig.symbol,
                    render_ts_type(&sig.ret)
                ));
            }
            Classification::Fallback { function, reason } => {
                // thaw-cli's own `typed_dynamic_bare_alias` already
                // generated a properly-typed forwarding wrapper under
                // both this name's package-qualified alias and its bare
                // name (whichever of those isn't itself suppressed by a
                // cross-package collision) -- generating the untyped
                // `(argsArray: Json): Json` shape here too would just be
                // a second, unreachable-in-practice-but-still-a-
                // duplicate-declaration-error declaration under the same
                // name(s).
                if typed_bare_aliases.contains(&function) {
                    continue;
                }
                let returns_callable = functions
                    .iter()
                    .filter(|candidate| candidate.name == function)
                    .all(|candidate| {
                        matches!(
                            candidate.ret,
                            DtsType::Native(HirType::Function(_, _) | HirType::JsValue)
                        )
                    });
                let qualified_entry = qualified.iter().find(|q| q.name == function);
                if let Some(q) = qualified_entry {
                    out.push_str(&format!(
                        "// Fallback (QuickJS-NG), package-qualified alias: {reason}\n"
                    ));
                    if returns_callable {
                        out.push_str(&format!(
                            "function {}(argsArray: Json): JsValue {{\n",
                            q.alias
                        ));
                        out.push_str(&format!(
                            "    const callable: JsValue = getDynamicValue(\"{}\");\n    return callDynamicValueHandle(callable, argsArray);\n",
                            q.qualified_key
                        ));
                    } else {
                        out.push_str(&format!("function {}(argsArray: Json): Json {{\n", q.alias));
                        out.push_str(&format!(
                            "    return callDynamic(\"{}\", argsArray);\n",
                            q.qualified_key
                        ));
                    }
                    out.push_str("}\n");
                }
                if qualified_entry.is_some_and(|q| q.suppress_bare) {
                    continue;
                }
                if shadows_a_thaw_literal_identifier(&function) {
                    continue;
                }
                out.push_str(&format!("// Fallback (QuickJS-NG): {reason}\n"));
                // `argsArray` (not `args`): `callDynamic` expects a JSON
                // *array* of positional arguments, e.g.
                // `identity(JSON.parse("[42]"))`, not `identity(JSON.parse("42"))` --
                // named to make that convention hard to miss at the call site.
                if returns_callable {
                    out.push_str(&format!(
                        "function {function}(argsArray: Json): JsValue {{\n"
                    ));
                    out.push_str(&format!(
                        "    const callable: JsValue = getDynamicValue(\"{function}\");\n    return callDynamicValueHandle(callable, argsArray);\n"
                    ));
                } else {
                    out.push_str(&format!("function {function}(argsArray: Json): Json {{\n"));
                    out.push_str(&format!(
                        "    return callDynamic(\"{function}\", argsArray);\n"
                    ));
                }
                out.push_str("}\n");
            }
        }
    }
    out
}

/// Generates the same JSON-shaped fallback wrappers as `generate_shim`, but
/// targets the synchronous N-API host instead of QuickJS.
pub fn generate_native_addon_shim(
    functions: &[DtsFunction],
    qualified: &[QualifiedFallback],
    typed_bare_aliases: &std::collections::HashSet<String>,
) -> String {
    let mut out = String::new();
    for (function, _) in effective_classifications(functions, false) {
        // See the matching check (and its own doc comment) in
        // `generate_shim` -- thaw-cli's own `typed_dynamic_bare_alias`
        // already generated a properly-typed wrapper under both this
        // name's forms for a native-addon Fallback function too (they
        // share the same declaration/symbol machinery, `napi: bool`
        // just picks the encoded symbol's prefix), so emitting the
        // untyped shape here as well would be a duplicate declaration
        // under the same name(s), not just a harmless dead one.
        if typed_bare_aliases.contains(&function) {
            continue;
        }
        if let Some(qualified) = qualified.iter().find(|entry| entry.name == function) {
            out.push_str("// Fallback (N-API), package-qualified alias\n");
            out.push_str(&format!(
                "function {}(argsArray: Json): Json {{\n",
                qualified.alias
            ));
            out.push_str(&format!(
                "    return callNativeAddon(\"{function}\", argsArray);\n"
            ));
            out.push_str("}\n");
            if qualified.suppress_bare {
                continue;
            }
        }
        if shadows_a_thaw_literal_identifier(&function) {
            continue;
        }
        out.push_str("// Fallback (N-API)\n");
        out.push_str(&format!("function {function}(argsArray: Json): Json {{\n"));
        out.push_str(&format!(
            "    return callNativeAddon(\"{function}\", argsArray);\n"
        ));
        out.push_str("}\n");
    }
    out
}

pub struct NativeAddon<'a> {
    pub package_name: &'a str,
    pub bytes: &'a [u8],
    pub root_export: Option<&'a str>,
}

pub fn generate_native_addon_init(addons: &[NativeAddon<'_>]) -> String {
    if addons.is_empty() {
        return String::new();
    }
    let mut out = String::from("function __thaw_native_module_init(): void {\n");
    for addon in addons {
        out.push_str(&format!("    // {}\n", addon.package_name));
        let hex: String = addon
            .bytes
            .iter()
            .map(|byte| format!("{byte:02x}"))
            .collect();
        let root_export = escape_ts_string_literal(addon.root_export.unwrap_or(""));
        out.push_str(&format!(
            "    loadNativeAddonEmbedded(\"{hex}\", \"{root_export}\");\n"
        ));
    }
    out.push_str("}\n");
    out
}

/// Escapes JS source for embedding as a double-quoted TS string literal
/// (backslash, `"`, and newlines/carriage-returns -- the characters that
/// would otherwise terminate or corrupt the literal). `generate_module_init`
/// is the only caller; a package's real `bundle.js` can contain any of
/// these.
fn escape_ts_string_literal(source: &str) -> String {
    let mut out = String::with_capacity(source.len());
    for ch in source.chars() {
        match ch {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            _ => out.push(ch),
        }
    }
    out
}

/// One registry package's bundled JS to auto-load, for
/// `generate_module_init`.
pub struct ModuleBundle<'a> {
    pub package_name: &'a str,
    pub js_source: &'a str,
    /// This package's Fallback function names (from its `.d.ts`,
    /// `Classification::Fallback { function, .. }`) -- used by
    /// `wrap_as_commonjs_module` to bind a bare `module.exports = fn`
    /// default export (very common for small single-function utility
    /// packages, e.g. `left-pad`) to the name `callDynamic` will look it
    /// up by.
    pub fallback_names: &'a [String],
    /// `(bare_name, qualified_key)` pairs for names that collide with
    /// another `--use`d package (thaw-cli detects this across packages,
    /// which no single `.d.ts`/package knows about on its own). Right
    /// after this bundle's `loadScript`, `generate_module_init` also
    /// captures `globalThis[bare_name]` under `globalThis[qualified_key]`
    /// (e.g. `"qs::stringify"`) -- *before* a later colliding package's
    /// own `loadScript` overwrites the bare name -- so a package-
    /// qualified call (`qs.stringify(...)`, rewritten by thaw-cli to the
    /// matching `generate_shim` alias) reaches the right one regardless
    /// of `--use` order. See `generate_shim`'s `qualified_names` doc
    /// comment for the other half of this.
    pub qualified_aliases: &'a [(String, String)],
}

/// Wraps a real npm package's CommonJS source so it can run inside
/// QuickJS-NG's bare global scope: defines `module`/`exports`/`require`
/// as *globals* before the source runs (real CommonJS/UMD source
/// references them unconditionally, and QuickJS-NG's global scope has
/// none of them), runs the source completely unwrapped/at top level
/// (deliberately -- nesting it inside a function scope would break the
/// existing simple case of a hand-authored bundle using bare top-level
/// `function` declarations, which rely on top-level scope becoming
/// global properties directly, the same way `loadScript` already worked
/// before this), then copies whatever the source assigned to
/// `module.exports` onto the global scope too, so `callDynamic`'s
/// by-name lookup (`thaw_js_call`, which only ever looks up *global*
/// functions) can find it either way.
///
/// Validated by running real, unmodified npm packages through the
/// Fallback path: `left-pad` (`module.exports = leftPad`) and `slugify`
/// (a UMD wrapper that takes the CommonJS branch once `module`/`exports`
/// exist) both load and run correctly, and a plain hand-authored bundle
/// with no `module.exports` at all keeps working exactly as before.
/// `is-odd` -- which calls `require('is-number')` at load time -- fails
/// with a clear error instead of the pre-existing opaque
/// `ReferenceError: module is not defined`, correctly surfacing a real,
/// documented limitation (see below) rather than silently misbehaving.
///
/// `require` is a stub that throws immediately: resolving a real
/// inter-package dependency graph inside QuickJS-NG remains out of scope
/// (docs/design/bridge.md section 7's "未解決の論点"/"unresolved
/// questions"). This only unblocks packages with no runtime dependencies
/// of their own, which covers plenty of real small utility packages.
///
/// A `fallback_names` binding also checks `module.exports.default`, not
/// just `module.exports` itself, being a function: thaw-registry's ESM
/// rewrite (a real ESM package's `export default function foo(){}`)
/// always sets `module.exports.default`, matching real `import x from
/// 'y'` interop semantics, rather than replacing `module.exports`
/// outright the way a plain CommonJS `module.exports = foo` does.
///
/// The `module.exports` -> `globalThis` copy loop skips (rather than
/// aborts on) a key it can't assign: `for...in` enumerates own AND
/// inherited enumerable keys in insertion order, so one key throwing
/// (in strict mode -- this bundle runs with `"use strict"`) used to
/// silently drop *every* key enumerated after it too, not just that one
/// -- real example: zod, which exports a schema-builder function
/// literally named `undefined` (`z.undefined()`), and `globalThis`'s own
/// `undefined` property is non-writable, so assigning it throws
/// `TypeError: 'undefined' is read-only`; every other export enumerated
/// after `undefined` in zod's own property order (`optional`, `object`,
/// ...) silently never reached `globalThis` at all before this fix,
/// even though none of them have anything to do with `undefined`
/// itself.
fn wrap_as_commonjs_module(js_source: &str, fallback_names: &[String]) -> String {
    // `name` is always a valid JS identifier here: it's a function name
    // SWC already parsed out of a `.d.ts` `declare function` statement,
    // not arbitrary text, so splicing it directly as a property-access
    // identifier (not a bracketed string) is safe.
    let bind_default_exports: String = fallback_names
        .iter()
        .map(|name| {
            format!(
                "if (typeof module.exports === 'function' && typeof globalThis.{name} !== 'function') {{ globalThis.{name} = module.exports; }}\n\
                 else if (typeof module.exports === 'object' && module.exports !== null && typeof module.exports.default === 'function') {{ globalThis.{name} = module.exports.default; }}\n"
            )
        })
        .collect();
    format!(
        "globalThis.module = {{ exports: {{}} }};\n\
         globalThis.exports = globalThis.module.exports;\n\
         globalThis.require = function(name) {{ throw new Error(\"require('\" + name + \"') is not supported in the Fallback path yet\"); }};\n\
         // Real packages commonly *guard* Node-only globals before using\n\
         // them (`Buffer && Buffer.isBuffer(x)`, `Buffer?.from(x)`) for\n\
         // exactly this situation -- a non-Node environment. But an\n\
         // undeclared bare identifier throws `ReferenceError` just from\n\
         // being *referenced*, guard or not (found via `@hapi/hoek`,\n\
         // which does this unconditionally at load time); explicitly\n\
         // assigning it `undefined` makes the identifier exist without\n\
         // pretending Buffer support exists, so those guards correctly\n\
         // take their \"not available\" branch instead of throwing.\n\
         if (typeof globalThis.Buffer === 'undefined') {{ globalThis.Buffer = undefined; }}\n\
         // Unlike `Buffer` above, real code sometimes reaches for `URL`\n\
         // *unconditionally* (e.g. `URL.prototype` as a lookup-table key,\n\
         // found via `@hapi/hoek`) rather than guarding it first --\n\
         // `undefined` doesn't survive a `.prototype` access, so this\n\
         // needs an actual (empty) constructor stand-in instead, which\n\
         // gets a `.prototype` object for free like any JS function.\n\
         if (typeof globalThis.URL === 'undefined') {{ globalThis.URL = function URL() {{}}; }}\n\
         // Node exposes `process` as an *ambient global*, not only as a\n\
         // requirable core module (thaw-registry's `builtin_module_source`\n\
         // covers the `require('process')` half) -- real packages\n\
         // (`node-gyp-build.js`, chasing a native addon's load path) read\n\
         // `process.config`/`process.env`/`process.versions`/\n\
         // `process.execPath` as a bare global with no guard at all, which\n\
         // would otherwise throw `ReferenceError: process is not defined`\n\
         // the same way an unguarded `Buffer`/`URL` reference would.\n\
         if (typeof globalThis.process === 'undefined') {{\n\
         \x20\x20globalThis.process = {{ argv: [], env: {{}}, platform: 'linux', version: '', execPath: '/usr/bin/node', config: {{ variables: {{}} }}, versions: {{ node: '', modules: '', uv: '' }}, nextTick: function(fn) {{ var args = Array.prototype.slice.call(arguments, 1); var run = function() {{ fn.apply(undefined, args); }}; if (typeof queueMicrotask === 'function') queueMicrotask(run); else Promise.resolve().then(run); }} }};\n\
         }}\n\
         // Likewise `__dirname`/`__filename`: real per-module Node\n\
         // locals, but every package here already runs unwrapped at\n\
         // global scope (see this function's doc comment), so a shared\n\
         // global stand-in is consistent with the rest of this wrapper.\n\
         // The exact path is inert -- `fs` above always reports \"nothing\n\
         // here\", so no real lookup ever depends on this value being\n\
         // accurate, only present as a string.\n\
         if (typeof globalThis.__dirname === 'undefined') {{ globalThis.__dirname = '/thaw_modules/package'; }}\n\
         if (typeof globalThis.__filename === 'undefined') {{ globalThis.__filename = '/thaw_modules/package/index.js'; }}\n\
         if (typeof globalThis.__thaw_napi_bridge_exports === 'function') {{\n\
         \x20\x20var __thaw_addon = {{}};\n\
         \x20\x20var __thaw_napi_reference_id = 0;\n\
         \x20\x20var __thaw_napi_reference_ids = new WeakMap();\n\
         \x20\x20var __thaw_napi_reference_values = new Map();\n\
         \x20\x20var __thaw_napi_handles = new WeakMap();\n\
         \x20\x20var __thaw_napi_proxies = new Map();\n\
         \x20\x20var __thaw_napi_finalizers = typeof FinalizationRegistry === 'function' ? new FinalizationRegistry(function(id) {{ __thaw_napi_reference_values.delete(id); __thaw_napi_handle('release', id, '', []); }}) : null;\n\
         \x20\x20var __thaw_napi_proxy_finalizers = typeof FinalizationRegistry === 'function' ? new FinalizationRegistry(function(handle) {{ __thaw_napi_proxies.delete(String(handle)); __thaw_napi_handle('release_handle', handle, '', []); }}) : null;\n\
         \x20\x20var __thaw_napi_argument = function(value) {{\n\
         \x20\x20\x20\x20if (value === null || (typeof value !== 'function' && typeof value !== 'object')) return value;\n\
         \x20\x20\x20\x20var handle = __thaw_napi_handles.get(value); if (handle) return {{ __thaw_napi_handle__: handle }};\n\
         \x20\x20\x20\x20if (Array.isArray(value)) return value.map(__thaw_napi_argument);\n\
         \x20\x20\x20\x20var id = __thaw_napi_reference_ids.get(value);\n\
         \x20\x20\x20\x20if (id) return typeof value === 'function' ? {{ __thaw_napi_function__: id }} : {{ __thaw_napi_object__: id, value: __thaw_napi_reference_values.get(id) }};\n\
         \x20\x20\x20\x20id = ++__thaw_napi_reference_id; __thaw_napi_reference_ids.set(value, id);\n\
         \x20\x20\x20\x20if (typeof value === 'function') {{ globalThis['__thaw_napi_reference_' + id] = function() {{ var args = Array.prototype.slice.call(arguments), meta = args.shift(), receiver; if (meta && meta.__thaw_napi_this_handle__) {{ var stored = __thaw_napi_proxies.get(meta.__thaw_napi_this_handle__); receiver = stored && typeof stored.deref === 'function' ? stored.deref() : stored; if (!receiver) receiver = __thaw_napi_proxy(meta.__thaw_napi_this_handle__); }} return value.apply(receiver, args); }}; return {{ __thaw_napi_function__: id }}; }}\n\
         \x20\x20\x20\x20var properties = {{}}; Object.keys(value).forEach(function(key) {{ properties[key] = __thaw_napi_argument(value[key]); }});\n\
         \x20\x20\x20\x20__thaw_napi_reference_values.set(id, properties);\n\
         \x20\x20\x20\x20if (__thaw_napi_finalizers) __thaw_napi_finalizers.register(value, id);\n\
         \x20\x20\x20\x20return {{ __thaw_napi_object__: id, value: properties }};\n\
         \x20\x20}};\n\
         \x20\x20var __thaw_napi_arguments = function(args) {{ return Array.prototype.map.call(args, __thaw_napi_argument); }};\n\
         \x20\x20var __thaw_napi_handle = function(operation, target, name, args) {{\n\
         \x20\x20\x20\x20var result = JSON.parse(globalThis.__thaw_napi_bridge_handle(operation, String(target), name || '', JSON.stringify(__thaw_napi_arguments(args || []))));\n\
         \x20\x20\x20\x20if (result && result.__thaw_error__) throw new Error(result.__thaw_error__);\n\
         \x20\x20\x20\x20if (result && result.value && result.value['$__thaw_napi_undefined$'] === true) result.value = undefined;\n\
         \x20\x20\x20\x20return result;\n\
         \x20\x20}};\n\
         \x20\x20var __thaw_napi_proxy = function(handle, prototype) {{ var target = Object.create(prototype || Object.prototype), proxy = new Proxy(target, {{\n\
         \x20\x20\x20\x20get: function(_, name, receiver) {{\n\
         \x20\x20\x20\x20\x20\x20if (name in _) return Reflect.get(_, name, receiver);\n\
         \x20\x20\x20\x20\x20\x20var result = __thaw_napi_handle('get', handle, String(name), []);\n\
         \x20\x20\x20\x20\x20\x20return result.kind === 'method' ? function() {{ return __thaw_napi_handle('call', handle, String(name), Array.prototype.slice.call(arguments)).value; }} : result.value;\n\
         \x20\x20\x20\x20}},\n\
         \x20\x20\x20\x20set: function(_, name, value, receiver) {{ __thaw_napi_handle('set', handle, String(name), [value]); return Reflect.set(_, name, value, receiver); }}\n\
         \x20\x20}}); __thaw_napi_handles.set(proxy, handle); __thaw_napi_proxies.set(String(handle), typeof WeakRef === 'function' ? new WeakRef(proxy) : proxy); if (__thaw_napi_proxy_finalizers) __thaw_napi_proxy_finalizers.register(proxy, String(handle)); return proxy; }};\n\
         \x20\x20JSON.parse(globalThis.__thaw_napi_bridge_exports()).forEach(function(name) {{\n\
         \x20\x20\x20\x20__thaw_addon[name] = function() {{\n\
         \x20\x20\x20\x20\x20\x20if (new.target) {{ var created = __thaw_napi_handle('construct', name, '', Array.prototype.slice.call(arguments)); return __thaw_napi_proxy(created.value, new.target.prototype); }}\n\
         \x20\x20\x20\x20\x20\x20var result = JSON.parse(globalThis.__thaw_napi_bridge_call(name, JSON.stringify(__thaw_napi_arguments(arguments))));\n\
         \x20\x20\x20\x20\x20\x20if (result && result.__thaw_error__) throw new Error(result.__thaw_error__);\n\
         \x20\x20\x20\x20\x20\x20return result;\n\
         \x20\x20\x20\x20}};\n\
         \x20\x20}});\n\
         \x20\x20globalThis.require.addon = function() {{ return __thaw_addon; }};\n\
         }}\n\
         {js_source}\n\
         var __thaw_bind_module_exports = function() {{\n\
         \x20\x20if (module.exports !== null && (typeof module.exports === 'object' || typeof module.exports === 'function')) {{ for (var k in module.exports) {{ try {{ globalThis[k] = module.exports[k]; }} catch (e) {{}} }} }}\n\
         {bind_default_exports}\
         }};\n\
         if (globalThis.__thaw_module_ready && typeof globalThis.__thaw_module_ready.then === 'function') {{ globalThis.__thaw_module_ready.then(__thaw_bind_module_exports); }}\n\
         else {{ __thaw_bind_module_exports(); }}"
    )
}

/// Generates the `__thaw_module_init` function that loads each registry
/// package's bundled JS source via `loadScript`, once, before user code
/// runs (thaw-llvm's `MODULE_INIT_SYMBOL`/`call_module_init_if_present`
/// call this automatically from both entry points). This is what makes a
/// registry package's Fallback functions (see `generate_shim`) callable
/// without the *user* having to call `loadScript` themselves -- they still
/// need to `--use` the package (thaw-cli), but not hand-write the load.
/// Each bundle's JS is passed through `wrap_as_commonjs_module` first, so
/// a real npm package's actual CommonJS/UMD source works unmodified.
///
/// `bundles` is in the order packages should load (later packages can
/// rely on earlier ones already being loaded into the shared QuickJS-NG
/// global scope). Returns an empty string -- no function emitted at all
/// -- when `bundles` is empty, since there would be nothing for it to do.
pub fn generate_module_init(bundles: &[ModuleBundle]) -> String {
    if bundles.is_empty() {
        return String::new();
    }
    let mut out = String::from("function __thaw_module_init(): void {\n");
    for bundle in bundles {
        out.push_str(&format!("    // {}\n", bundle.package_name));
        let wrapped = wrap_as_commonjs_module(bundle.js_source, bundle.fallback_names);
        out.push_str(&format!(
            "    loadScript(\"{}\");\n",
            escape_ts_string_literal(&wrapped)
        ));
        // Captured immediately, before any later package's own
        // `loadScript` can overwrite the bare name -- see
        // `ModuleBundle::qualified_aliases`'s doc comment.
        for (bare_name, qualified_key) in bundle.qualified_aliases {
            // This alias-capture logic must run as *JS* (QuickJS-NG),
            // inside its own `loadScript`, not as bare Thaw source --
            // `__thaw_module_init` is a real, compiled Thaw function, and
            // Thaw's compiler has no `typeof`/bracket-indexing/etc. at
            // all. Double-escaped: `qualified_key` for the inner JS
            // string literal, then the whole JS snippet again for the
            // outer TS string literal `loadScript` takes, same as
            // `wrap_as_commonjs_module`'s own output already is.
            //
            // Reads `globalThis.module.exports.{bare_name}` first, not
            // `globalThis.{bare_name}` directly -- `globalThis.module`
            // still holds *this* package's own fresh `{ exports: {} }`
            // at this exact point (nothing else has run in between; see
            // this loop's own comment above), so `module.exports` is a
            // perfectly ordinary object property lookup regardless of
            // what `bare_name` is. `globalThis.{bare_name}` itself can't
            // work at all for a real ECMAScript reserved word used as an
            // export name (`undefined` -- zod has one, `z.undefined()`
            // -- `null`, `NaN`; `globalThis.undefined` can never be
            // reassigned in any JS engine, so it would always read back
            // the literal, never the real function). Falls back to the
            // old `globalThis.{bare_name}` read only when the property
            // lookup finds nothing, for the one shape it doesn't cover:
            // a CommonJS package whose *whole* `module.exports` (not a
            // property of it) is the single exported function --
            // `wrap_as_commonjs_module`'s own `bind_default_exports`
            // already binds `globalThis.{bare_name} = module.exports`
            // directly for exactly that case, with no corresponding
            // property to read here instead.
            let capture_js = format!(
                "if (typeof globalThis.module !== 'undefined' && globalThis.module && typeof globalThis.module.exports !== 'undefined' && globalThis.module.exports !== null && typeof globalThis.module.exports.{bare_name} !== 'undefined') {{ globalThis[\"{}\"] = globalThis.module.exports.{bare_name}; }} else if (typeof globalThis.{bare_name} !== 'undefined') {{ globalThis[\"{}\"] = globalThis.{bare_name}; }}",
                escape_ts_string_literal(qualified_key),
                escape_ts_string_literal(qualified_key)
            );
            out.push_str(&format!(
                "    loadScript(\"{}\");\n",
                escape_ts_string_literal(&capture_js)
            ));
        }
    }
    out.push_str("}\n");
    out
}
