pub(super) fn source(name: &str) -> Option<&'static str> {
    match name {
        "console" => Some(
            "module.exports = globalThis.console; module.exports.Console = globalThis.Console; module.exports.console = globalThis.console; module.exports.default = globalThis.console; module.exports.__esModule = true;\n",
        ),
        "constants" => Some(
            "var constants = globalThis.__thaw_fs_constants || (globalThis.__thaw_fs_constants = { F_OK: 0, X_OK: 1, W_OK: 2, R_OK: 4, O_RDONLY: 0, O_WRONLY: 1, O_RDWR: 2, O_CREAT: 64, O_EXCL: 128, O_NOCTTY: 256, O_TRUNC: 512, O_APPEND: 1024, O_DIRECTORY: 65536, O_NOFOLLOW: 131072, O_SYNC: 1052672, S_IFMT: 61440, S_IFREG: 32768, S_IFDIR: 16384, S_IFCHR: 8192, S_IFBLK: 24576, S_IFIFO: 4096, S_IFLNK: 40960, S_IFSOCK: 49152, COPYFILE_EXCL: 1, COPYFILE_FICLONE: 2, COPYFILE_FICLONE_FORCE: 4 }); module.exports = constants; module.exports.default = constants; module.exports.__esModule = true;\n",
        ),
        "crypto" => Some(
            "module.exports = globalThis.__thaw_crypto_module; module.exports.default = module.exports; module.exports.__esModule = true;\n",
        ),
        "perf_hooks" => Some(
            "function Histogram(resolution) { this.enabled = false; this.resolution = Math.max(1, Number(resolution || 10)); this.exceeds = 0; this.reset(); }\n\
             Histogram.prototype._record = function(value) { this._values.push(value); this.count = this._values.length; this.min = Math.min(this.min, value); this.max = Math.max(this.max, value); var delta = value - this.mean; this.mean += delta / this.count; this._m2 += delta * (value - this.mean); this.stddev = Math.sqrt(this._m2 / this.count); var values = this._values.slice().sort(function(left, right) { return left - right; }); this.percentiles = new Map([0, 50, 75, 90, 99, 100].map(function(percentile) { var index = Math.min(values.length - 1, Math.ceil(percentile / 100 * values.length) - 1); return [percentile, values[Math.max(0, index)]]; })); }; Histogram.prototype.enable = function() { if (this.enabled) return false; this.enabled = true; var histogram = this, previous = performance.now(); function sample() { if (!histogram.enabled) return; var now = performance.now(); histogram._record((now - previous) * 1000000); previous = now; histogram._timer = setTimeout(sample, histogram.resolution); } this._timer = setTimeout(sample, this.resolution); return true; }; Histogram.prototype.disable = function() { if (!this.enabled) return false; this.enabled = false; clearTimeout(this._timer); return true; }; Histogram.prototype.reset = function() { this.min = Infinity; this.max = 0; this.mean = 0; this.stddev = 0; this.count = 0; this._m2 = 0; this._values = []; this.percentiles = new Map(); }; Histogram.prototype.percentile = function(value) { if (!this.count) return 0; var values = this._values.slice().sort(function(left, right) { return left - right; }), index = Math.min(values.length - 1, Math.ceil(Number(value) / 100 * values.length) - 1); return values[Math.max(0, index)]; }; Histogram.prototype.percentileBigInt = function(value) { return BigInt(Math.round(this.percentile(value))); };\n\
             function monitorEventLoopDelay(options) { return new Histogram(options && options.resolution); } function createHistogram() { return new Histogram(); }\n\
             var started = globalThis.performance.timeOrigin; globalThis.performance.nodeTiming = globalThis.performance.nodeTiming || { name: 'node', entryType: 'node', startTime: 0, duration: globalThis.performance.now(), nodeStart: 0, v8Start: 0, bootstrapComplete: 0, environment: 0, loopStart: 0, loopExit: -1, idleTime: 0 };\n\
             globalThis.performance.eventLoopUtilization = globalThis.performance.eventLoopUtilization || function(previous) { var active = globalThis.performance.now(); if (previous) active = Math.max(0, active - Number(previous.active || 0)); return { idle: 0, active: active, utilization: active === 0 ? 0 : 1 }; };\n\
             module.exports = { performance: globalThis.performance, PerformanceEntry: globalThis.PerformanceEntry, PerformanceMark: globalThis.PerformanceMark, PerformanceMeasure: globalThis.PerformanceMeasure, PerformanceObserver: globalThis.PerformanceObserver, PerformanceObserverEntryList: globalThis.PerformanceObserverEntryList, monitorEventLoopDelay: monitorEventLoopDelay, createHistogram: createHistogram, constants: { NODE_PERFORMANCE_GC_MAJOR: 4, NODE_PERFORMANCE_GC_MINOR: 1, NODE_PERFORMANCE_GC_INCREMENTAL: 8, NODE_PERFORMANCE_GC_WEAKCB: 16 }, timerify: globalThis.performance.timerify };\n\
             module.exports.default = module.exports; module.exports.__esModule = true;\n",
        ),
        "v8" => Some(
            "function encode(root) { var seen = new Map(); var nodes = []; function visit(value) { if (value === undefined) return { t: 'u' }; if (typeof value === 'bigint') return { t: 'i', v: String(value) }; if (typeof value === 'number' && !Number.isFinite(value)) return { t: 'n', v: String(value) }; if (value === null || typeof value !== 'object') return { t: 'p', v: value }; if (seen.has(value)) return { t: 'r', v: seen.get(value) }; var id = nodes.length; seen.set(value, id); nodes.push(null); var node; if (Buffer.isBuffer(value)) node = { k: 'b', v: value.toString('base64') }; else if (value instanceof Date) node = { k: 'd', v: value.toISOString() }; else if (value instanceof RegExp) node = { k: 'x', v: value.source, f: value.flags, l: value.lastIndex }; else if (value instanceof Map) node = { k: 'm', v: Array.from(value, function(entry) { return [visit(entry[0]), visit(entry[1])]; }) }; else if (value instanceof Set) node = { k: 's', v: Array.from(value, visit) }; else if (Array.isArray(value)) node = { k: 'a', v: value.map(visit) }; else node = { k: 'o', v: Object.keys(value).map(function(key) { return [key, visit(value[key])]; }) }; nodes[id] = node; return { t: 'r', v: id }; } return JSON.stringify({ root: visit(root), nodes: nodes }); }\n\
             function decode(text) { var graph = JSON.parse(text); var values = new Array(graph.nodes.length); graph.nodes.forEach(function(node, index) { if (node.k === 'b') values[index] = Buffer.from(node.v, 'base64'); else if (node.k === 'd') values[index] = new Date(node.v); else if (node.k === 'x') values[index] = new RegExp(node.v, node.f); else if (node.k === 'm') values[index] = new Map(); else if (node.k === 's') values[index] = new Set(); else if (node.k === 'a') values[index] = []; else values[index] = {}; }); function read(value) { if (value.t === 'u') return undefined; if (value.t === 'i') return BigInt(value.v); if (value.t === 'n') return Number(value.v); if (value.t === 'p') return value.v; return values[value.v]; } graph.nodes.forEach(function(node, index) { var target = values[index]; if (node.k === 'm') node.v.forEach(function(entry) { target.set(read(entry[0]), read(entry[1])); }); else if (node.k === 's') node.v.forEach(function(entry) { target.add(read(entry)); }); else if (node.k === 'a') node.v.forEach(function(entry) { target.push(read(entry)); }); else if (node.k === 'o') node.v.forEach(function(entry) { target[entry[0]] = read(entry[1]); }); else if (node.k === 'x') target.lastIndex = node.l; }); return read(graph.root); }\n\
             function serialize(value) { return Buffer.from(encode(value), 'utf8'); } function deserialize(value) { return decode(Buffer.from(value).toString('utf8')); }\n\
             function getHeapStatistics() { return { total_heap_size: 0, total_heap_size_executable: 0, total_physical_size: 0, total_available_size: 0, used_heap_size: 0, heap_size_limit: Number.MAX_SAFE_INTEGER, malloced_memory: 0, peak_malloced_memory: 0, does_zap_garbage: 0, number_of_native_contexts: 1, number_of_detached_contexts: 0, total_global_handles_size: 0, used_global_handles_size: 0, external_memory: 0 }; }\n\
             function getHeapSpaceStatistics() { return []; } function getHeapCodeStatistics() { return { code_and_metadata_size: 0, bytecode_and_metadata_size: 0, external_script_source_size: 0, cpu_profiler_metadata_size: 0 }; } function cachedDataVersionTag() { return 0; } function setFlagsFromString() {}\n\
             module.exports = { serialize: serialize, deserialize: deserialize, getHeapStatistics: getHeapStatistics, getHeapSpaceStatistics: getHeapSpaceStatistics, getHeapCodeStatistics: getHeapCodeStatistics, cachedDataVersionTag: cachedDataVersionTag, setFlagsFromString: setFlagsFromString }; module.exports.default = module.exports; module.exports.__esModule = true;\n",
        ),
        "vm" => Some(concat!(
            "var contexts = globalThis.__thaw_vm_contexts || (globalThis.__thaw_vm_contexts = new WeakSet()); function createContext(object, options) { var context = object === undefined ? {} : object; if ((typeof context !== 'object' && typeof context !== 'function') || context === null) throw new TypeError('contextObject must be an object'); contexts.add(context); if (!Object.prototype.hasOwnProperty.call(context, 'globalThis')) Object.defineProperty(context, 'globalThis', { value: context, configurable: true }); if (!Object.prototype.hasOwnProperty.call(context, 'global')) Object.defineProperty(context, 'global', { value: context, configurable: true }); return context; } function isContext(value) { return (typeof value === 'object' || typeof value === 'function') && value !== null && contexts.has(value); } function scopeFor(context) { return new Proxy(context, { has: function(target, key) { return key !== 'scope' && key !== 'source'; }, get: function(target, key) { if (key === Symbol.unscopables) return undefined; return key in target ? target[key] : globalThis[key]; }, set: function(target, key, value) { target[key] = value; return true; } }); } function runInContext(code, context, options) { if (!isContext(context)) throw new TypeError('contextifiedObject must be a vm.Context'); return Function('scope', 'source', 'with (scope) { return eval(source); }')(scopeFor(context), String(code)); } function runInNewContext(code, context, options) { return runInContext(code, createContext(context === undefined ? {} : context), options); } function runInThisContext(code, options) { return (0, eval)(String(code)); }\n\
             function Script(code, options) { if (!(this instanceof Script)) return new Script(code, options); this.code = String(code); this.filename = options && options.filename ? String(options.filename) : 'evalmachine.<anonymous>'; this.cachedDataRejected = false; this.sourceMapURL = undefined; Function(this.code); } Script.prototype.runInContext = function(context, options) { return runInContext(this.code, context, options); }; Script.prototype.runInNewContext = function(context, options) { return runInNewContext(this.code, context, options); }; Script.prototype.runInThisContext = function(options) { return runInThisContext(this.code, options); }; Script.prototype.createCachedData = function() { return Buffer.from(this.code, 'utf8'); }; function compileFunction(code, params, options) { params = params || []; var fn = Function.apply(null, params.concat(String(code))); if (options && options.filename) Object.defineProperty(fn, 'filename', { value: String(options.filename) }); return fn; } function measureMemory(options) { return Promise.resolve({ total: { jsMemoryEstimate: 0, jsMemoryRange: [0, 0] }, current: { jsMemoryEstimate: 0, jsMemoryRange: [0, 0] }, other: [] }); } function getDefaultContext() { return globalThis; }\n\
             module.exports = { Script: Script, createScript: function(code, options) { return new Script(code, options); }, createContext: createContext, isContext: isContext, runInContext: runInContext, runInNewContext: runInNewContext, runInThisContext: runInThisContext, compileFunction: compileFunction, measureMemory: measureMemory, constants: { USE_MAIN_CONTEXT_DEFAULT_LOADER: Symbol.for('vm_dynamic_import_main_context_default'), DONT_CONTEXTIFY: Symbol.for('vm_context_no_contextify') }, getDefaultContext: getDefaultContext }; module.exports.default = module.exports; module.exports.__esModule = true;\n",
            "var vmIntrinsicNames = new Set(['console','Error','TypeError','RangeError','ReferenceError','SyntaxError','URIError','EvalError','AggregateError','Object','Function','Array','Number','String','Boolean','BigInt','Symbol','Date','RegExp','Map','Set','WeakMap','WeakSet','WeakRef','FinalizationRegistry','Promise','Proxy','Reflect','JSON','Math','Intl','ArrayBuffer','SharedArrayBuffer','DataView','Uint8Array','Uint8ClampedArray','Uint16Array','Uint32Array','Int8Array','Int16Array','Int32Array','Float32Array','Float64Array','BigInt64Array','BigUint64Array','Atomics','WebAssembly','Infinity','NaN','undefined','eval','isFinite','isNaN','parseFloat','parseInt','decodeURI','decodeURIComponent','encodeURI','encodeURIComponent']); scopeFor = function(context) { return new Proxy(context, { has: function(target, key) { return key !== 'scope' && key !== 'source'; }, get: function(target, key) { if (key === Symbol.unscopables) return undefined; return key in target ? target[key] : vmIntrinsicNames.has(key) ? globalThis[key] : undefined; }, set: function(target, key, value) { target[key] = value; return true; } }); };\n",
        )),
        "zlib" => Some(
            "var stream = require('node:stream'); function input(value) { return Buffer.isBuffer(value) ? value : Buffer.from(value); } function run(operation, format, value) { return Buffer.from(__thaw_zlib_hex(operation, format, input(value).toString('hex')), 'hex'); } function sync(operation, format) { return function(value) { return run(operation, format, value); }; } function async(syncFunction) { return function(value, options, callback) { if (typeof options === 'function') callback = options; try { var result = syncFunction(value, options); queueMicrotask(function() { callback(null, result); }); } catch (error) { queueMicrotask(function() { callback(error); }); } }; }\n\
             var gzipSync = sync('compress', 'gzip'), gunzipSync = sync('decompress', 'gzip'), deflateSync = sync('compress', 'deflate'), inflateSync = sync('decompress', 'deflate'), deflateRawSync = sync('compress', 'deflateRaw'), inflateRawSync = sync('decompress', 'deflateRaw'), brotliCompressSync = sync('compress', 'brotli'), brotliDecompressSync = sync('decompress', 'brotli');\n\
             function ZlibTransform(operation, format, options) { if (!(this instanceof ZlibTransform)) return new ZlibTransform(operation, format, options); var chunks = [], self = this; stream.Transform.call(this, { transform: function(chunk, encoding, callback) { self.bytesWritten += chunk.length; chunks.push(Buffer.from(chunk)); callback(); }, flush: function(callback) { try { callback(null, run(operation, format, Buffer.concat(chunks))); } catch (error) { callback(error); } } }); this.bytesWritten = 0; this._operation = operation; this._format = format; } ZlibTransform.prototype = Object.create(stream.Transform.prototype); ZlibTransform.prototype.constructor = ZlibTransform; ZlibTransform.prototype.flush = function(kind, callback) { if (typeof kind === 'function') callback = kind; if (callback) queueMicrotask(callback); }; ZlibTransform.prototype.close = function(callback) { this.destroy(); if (callback) queueMicrotask(callback); }; ZlibTransform.prototype.reset = function() { if (this.writableEnded) throw new Error('Cannot reset a finished zlib stream'); return this; };\n\
             function type(name, operation, format) { var Constructor = function(options) { if (!(this instanceof Constructor)) return new Constructor(options); ZlibTransform.call(this, operation, format, options); }; Constructor.prototype = Object.create(ZlibTransform.prototype); Constructor.prototype.constructor = Constructor; Object.defineProperty(Constructor, 'name', { value: name }); return Constructor; } var Gzip = type('Gzip', 'compress', 'gzip'), Gunzip = type('Gunzip', 'decompress', 'gzip'), Deflate = type('Deflate', 'compress', 'deflate'), Inflate = type('Inflate', 'decompress', 'deflate'), DeflateRaw = type('DeflateRaw', 'compress', 'deflateRaw'), InflateRaw = type('InflateRaw', 'decompress', 'deflateRaw'), BrotliCompress = type('BrotliCompress', 'compress', 'brotli'), BrotliDecompress = type('BrotliDecompress', 'decompress', 'brotli'); function factory(Constructor) { return function(options) { return new Constructor(options); }; }\n\
             module.exports = { gzipSync: gzipSync, gunzipSync: gunzipSync, deflateSync: deflateSync, inflateSync: inflateSync, deflateRawSync: deflateRawSync, inflateRawSync: inflateRawSync, brotliCompressSync: brotliCompressSync, brotliDecompressSync: brotliDecompressSync, gzip: async(gzipSync), gunzip: async(gunzipSync), deflate: async(deflateSync), inflate: async(inflateSync), deflateRaw: async(deflateRawSync), inflateRaw: async(inflateRawSync), brotliCompress: async(brotliCompressSync), brotliDecompress: async(brotliDecompressSync), Gzip: Gzip, Gunzip: Gunzip, Deflate: Deflate, Inflate: Inflate, DeflateRaw: DeflateRaw, InflateRaw: InflateRaw, BrotliCompress: BrotliCompress, BrotliDecompress: BrotliDecompress, createGzip: factory(Gzip), createGunzip: factory(Gunzip), createDeflate: factory(Deflate), createInflate: factory(Inflate), createDeflateRaw: factory(DeflateRaw), createInflateRaw: factory(InflateRaw), createBrotliCompress: factory(BrotliCompress), createBrotliDecompress: factory(BrotliDecompress), constants: { Z_OK: 0, Z_STREAM_END: 1, Z_DEFAULT_COMPRESSION: -1, Z_NO_FLUSH: 0, Z_SYNC_FLUSH: 2, Z_FINISH: 4, BROTLI_OPERATION_PROCESS: 0, BROTLI_OPERATION_FLUSH: 1, BROTLI_OPERATION_FINISH: 2 } }; module.exports.default = module.exports; module.exports.__esModule = true;\n",
        ),
        _ => None,
    }
}
